### ISSUE TITLE
Transition away from creating a block based on the number of transactions in the pool

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1004]
Currently: We attempt to nominate a set of transactions as soon as we have 8 available transactions.

What we want is to create blocks at a regular interval, regardless of the number of transaction.
We want this to be able to use the block height as a measure of time.
Our current thinking targets an interval of  10 minutes between blocks, but this should be configurable through `ConsensusParams` so we can write tests.

Questions to answer:
- How do we take into account the time it takes to nominate a block ?
  - How long before the "deadline" should nomination start ?
  - What timeout strategy do we use for nomination ?
  - How do we ensure the network is always live ?

Useful links:
Search everything related to `Block.TxsInBlock`.

**Comment by AndrejMitrovic** [comment]
I will be working on this.

**Comment by AndrejMitrovic** [comment]
I got a working draft version of this (test-suite passes).

But I don't have answers to the questions yet. Need to research that.

With regards to being able to measure progress of time, I wonder if it would make sense to include a timestamp in the block header.

**Comment by AndrejMitrovic** [comment]
What do we do when there's not enough transactions to form a block? Do we create an empty block?

**Comment by AndrejMitrovic** [comment]
s/not enough/not even 1 transaction.

**Comment by AndrejMitrovic** [comment]
This was moved to done but was not closed.
