### ISSUE TITLE
Node configuration and block storage consistency is not checked

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1006]
Currently we call `setGenesisBlock` from the `FullNod` constructor:
https://github.com/bpfkorea/agora/blob/4fbb4b3738a5e2be6ad03d7cf3bfa3467a5ff03c/source/agora/node/FullNode.d#L124-L135

In addition, we add the genesis block to the block storage if there is no previously existing one:
https://github.com/bpfkorea/agora/blob/4fbb4b3738a5e2be6ad03d7cf3bfa3467a5ff03c/source/agora/node/BlockStorage.d#L277

However, there *can* be a disconnect when the node is started, between what's in storage, and what genesis block we have.
A fact that is made obvious in the following piece of code:
https://github.com/bpfkorea/agora/blob/4fbb4b3738a5e2be6ad03d7cf3bfa3467a5ff03c/source/agora/test/Base.d#L1019-L1048

Here we see that we **both** have to set the hex string in the `NodeConfig`, and add it to the `MemBlockStorage`.
If the `GenesisBlock` was not added to the `MemBlockStorage` and there is no other block, it is okay to not set it in `MemBlockStorage`, as it will automatically load it. However, if it is only set in `MemBlockStorage` and not in the configuration, there will be a bug.

In a real life scenario, this can be triggered by user error:
- User start agora with a certain Genesis block;
- User change config and forget to clear the `.cache`;
- User starts Agora with a different Genesis block;
- Chaos ensure.

**Comment by AndrejMitrovic** [comment]
I think https://github.com/bpfkorea/agora/pull/813 tried to add this check, but then we focused on https://github.com/bpfkorea/agora/issues/821 as a better solution.

**Comment by AndrejMitrovic** [comment]
Is this solved by this now? https://github.com/bpfkorea/agora/blob/4fc127860126d78610676c92d49fdad55576aa66/source/agora/node/Ledger.d#L125-L126

**Comment by Geod24** [comment]
Indeed, good catch.
