### ISSUE TITLE
Add event notification to Agora, starting with block reception

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1033]
> As a developer, I want to programmatically be able to respond to certain events happening in the node.

For the moment, I would recommend to have it simply part of the configuration. In the future we might switch to [SSE](https://en.wikipedia.org/wiki/Server-sent_events) but for the moment let's keep it simple.
The idea is to come up with a list of events, and for each of them, have a section in the config file that specifies an URL to push the payload (HTTP POST) when said event happens.

Suggested events:
- A block is externalized, either via catch-up or direct participation;
- A valid pre-image is received (needed for stoa to continue development);

Definition of done:
- There is a YAML section for as follows:
```yaml
event_handlers:
  block_externalized:
    - http://abcdef.net/push
    - 127.0.0.1:3333/push
  preimage_received:
    - SomeOtherURL
```

When the corresponding event happens, the payload is sent to the URL via an HTTP POST request, with the payload as JSON body. Implementation tip: I would recommend implementing each event handler as a single-method `interface` and use the REST generator, e.g.:
```D
interface BlockExternalizedHandler
{
    @method(HTTPMethod.POST)
    @path("/push")
     // Using `/` for `@path` might be possible, in which case the path is passed to the `RestInterfaceClient`:
     // scope client = new RestInterfaceClient!BlockExternalizedHandler("http://127.0.0.1/push/");
    void push (Block block);
}
```

This way we can easily do dependency injection in the test-suite, and could even build some utilities to use this for testing.

**Comment by AndrejMitrovic** [comment]
> This way we can easily do dependency injection in the test-suite

~I don't follow. How does event handling help with doing dependency injection?~

Edit: Resolved IRL.

**Comment by MichaelKim20** [comment]
Aren't you considering the way Agora responds to external requests?

**Comment by AndrejMitrovic** [comment]
I suggested yesterday that these requests will probably be local only. The Stoa server and the Agora node will run on the same machine.

But maybe @Geod24 thought of other use-cases?

**Comment by MichaelKim20** [comment]
When handling events in D language, which library do you use?

**Comment by AndrejMitrovic** [comment]
I'm not sure why the issue seems complicated. It's just about spawning a separate list of `RestInterfaceClient`'s as set in the configuration. Maybe we need to whiteboard at 4PM.
