### ISSUE TITLE
Agora is producing a never-ending core dump

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1037]
```
$ dub build -c unittest -b unittest-cov --skip-registry=all --compiler=ldc2
$ ./build/agora-unittest &

... wait 5 seconds
$ killall -SIGSEGV agora-unittests
```

If you `ls` into `/cores/` you will see there is an ever-growing core dump. It quickly reaches into hundreds of GB.

Note that a partially dumped core file is unusable, we need to wait for the dump to complete. But there seems to be a bug somewhere causing the dump to never end.

This makes it **impossible** to diagnose the infinite loop bug, because getting the state of the unittest binary in the CI via a forced SIGSEGV doesn't produce a usable core dump.

**Comment by AndrejMitrovic** [comment]
When the unittests start they quickly reserve 165G of memory (virtual). Not all of this is used, obviously. But I think when dumping the entire virtual memory will be dumped even if unused..

**Comment by Geod24** [comment]
Can we bisect the failing test ? Each `spawn` call in LocalRest means allocating a Fiber, and each Fiber has 16Mbs of virtual memory, so yeah, 165G sounds about where it could be.

**Comment by AndrejMitrovic** [comment]
The failing test happens in the CI, not locally. That's why I wanted the core dump..

**Comment by AndrejMitrovic** [comment]
Anyway thanks for the hint, I have an idea.

**Comment by Geod24** [comment]
Is this still an issue ? Haven't seen that for a while since we went to single threaded.

**Comment by AndrejMitrovic** [comment]
Didn't see it in a long time. good to go.
