### ISSUE TITLE
Possible race condition with onValidatorsChanged and the Ledger

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1049]
Currently, when we construct the `Validator`, we pass a callback to `onValidatorChanged` to `super` (the `FullNode` ctor).
This callback is then passed to `Ledger` during its construction, and will be called when the validator set changes (through `addValidatedBlock`.
There is a possible race condition here: If `addValidatedBlock` is called by the `Ledger` before the `Validator` is done instantiating, especially before the `Nominator` is created and set, a call to `onValidatorChanged` will crash Agora.

**Comment by AndrejMitrovic** [comment]
lol I just ran into this while rebasing my PR. 

me 🔫

**Comment by Geod24** [comment]
This was fixed in https://github.com/bosagora/agora/commit/c6a7e45af58cfc052f2a5b28e7030e8060fbc15e
Nowadays `acceptBlock` is the one calling the delegate, and `addValidatedBlock` is called by it.
