### ISSUE TITLE
All forms of loading should be moved out of constructors

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1058]
There is an issue right now that is blocking progress on https://github.com/bpfkorea/agora/pull/1008.

The ledger has to call the `onValidatorsChanged` method at start-up in order to set up the quorum sets. Currently there is already logic in the Ledger constructor which restores the UTXO set if it's empty:

https://github.com/bpfkorea/agora/blob/65650d8b1053bb7d3b574a4bf552493676f54d1d/source/agora/node/Ledger.d#L158-L166

But we cannot add an `onValidatorsChanged` call here - one of the reasons is that `onValidatorsChanged` itself accesses the Ledger instance (which hasn't completed instantiating yet!) so it would segfault. Another reason is the Nominator instance isn't instantiated yet.

I think we need to decouple the instantiating & loading (restoring data) into separate methods: the constructor, and a `load` routine. So I suggest:

- Moving all loading into a `load()` routine for each class which previously did it in its constructor
- Call `load()` as the first routine inside of `start()`

@Geod24 what do you think?

Edit: Please see the idea suggested by @Geod24 below.

**Comment by Geod24** [comment]
Following our IRL conversation, I feel we should turn those delegates into overrides.
E.g. instead of doing:
```D
class Ledger
{
    private DelegateT onChange;

    this (DelegateT cb) { this.onChange = cb; }
    void addValidatedBlock (const ref Block b)
    {
        // Do stuff
        if (this.onChange !is null)
            this.onChange();
    }
}
```

Do:
```D
class Ledger
{
    void addValidatedBlock (const ref Block b)
    {
        // Do stuff
    }
}

class ValidatorLedger : Ledger
{
    public override void addValidatedBlock (const ref Block b)
    {
        super.addValidatedBlock(b);
        // Do the `onChange` thingy
    }
}
```

**Comment by AndrejMitrovic** [comment]
This is a bit more involved. Anyway I have a better solution for #1008.

**Comment by Geod24** [comment]
We now use [`replayStoredBlock`](https://github.com/bosagora/agora/blob/49c7bd7e323325e9b03c7a94463f45c239886c8f/source/agora/node/Ledger.d#L348-L365).
