### ISSUE TITLE
Checking virtual method offset is expensive

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1064]
It takes around 3 minutes to do on CircleCI, which is 1/3 of the run time of the whole CI.
We only need to do that check when we actually change C++/D related code, not for every PR.

**Comment by AndrejMitrovic** [comment]
3 minutes? Isn't there only a few virtual methods? Why is it so slow..

**Comment by Geod24** [comment]
`dub build` is what takes most of the time. The runtime is negligible.

**Comment by Geod24** [comment]
Fixed by https://github.com/bosagora/agora/pull/1734
