### ISSUE TITLE
Leader selection needs to be improved

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1079]
Currently the leader selection in SCP is based entirely on the weight of the node:

https://github.com/bpfkorea/agora/blob/1af3731d063a8b52f1e114a4b31e5ac65ad70869/source/scpp/src/scp/NominationProtocol.cpp#L210
https://github.com/bpfkorea/agora/blob/1af3731d063a8b52f1e114a4b31e5ac65ad70869/source/scpp/src/scp/NominationProtocol.cpp#L265
https://github.com/bpfkorea/agora/blob/1af3731d063a8b52f1e114a4b31e5ac65ad70869/source/scpp/src/scp/LocalNode.cpp#L97

The current algorithm makes the leader selection too predictable. This is especially true in our case because all of our validators are registered and known.

We should take our source of randomness into account when doing leader selection for each round. 

And as a slight optimization we could replace the `getNodeWeight` so it doesn't have to walk through any quorum sets. We know how many times each node appears in a quorum.

-----

Side-note: the reason this is not an issue in Stellar is two-fold: 
1) the validator set is not known and can change at any moment (no registration necessary)
2) Stellar is trust-based, which partially justifies having a predictable leader selection algorithm

**Comment by linked0** [comment]
Blocked by #1166
