### ISSUE TITLE
Networking unittests should test multi-round consensus

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1080]
Currently all of the networking tests reach consensus in 1 round - they were only doing multiple rounds accidentally due to the code before the bugfix in https://github.com/bpfkorea/agora/pull/1078.

We should write some tests where the nodes are deliberately rejecting nominations for several rounds until one is accepted at round R, where R could be arbitrarily high.

**Comment by linked0** [comment]
According to my analysis, I guess these might be what I have to implement.
1. Derive the class from the `Validator` like `LazyValidator` that ignores an envelope in the overridden `receiveEnvelope` function for many rounds.
2. Customize the `Slot::NOMINATION_TIME` value into a much smaller value for network tests.

@AndrejMitrovic Could you add the assumption and expectation for the network test and check my approach is right?

**Comment by AndrejMitrovic** [comment]
It might be possible to just use the `ctrl.sleep` interface in LocalRest.

`mRoundNumber` (the round number) is passed to `computeHashNode` (you have overriden this method in your recent PR). So you just need to capture the round number value in the unittests and assert that it's > 1. And you can force multi-round consensus by deliberately dropping messages - by using `ctrl.sleep`.
