### ISSUE TITLE
Transaction pool & gossiping might need to be slightly improved

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1082]
Thanks to https://github.com/Geod24/localrest/pull/90 I've found an edge-case in the Validator:

Consider a case of 3 validator nodes:
- Nodes reach consensus on block height 1
- Externalize messages are propagated throughout the network
- One node has networking issues towards the other nodes and has not received the externalize message yet
- Node 1 is at block height 0, nodes 2 and 3 are at block height 1.

In this situations nodes [2, 3] will accept transactions which reference UTXOs from block height 1, but node 0 will not. 

Visual example:

```
N2 --- N3
 \    /
   N1
   |
   User
```

In this case the network between N1 and N2&N3 is broken, but the User can still reach N1. If this user sends a payment to N1 then this TX is rejected and **not** gossiped to the rest of the network (regardless of networking issues) and it's also **not** added to N1's pool. Ideally we want N1 to eventually store this TX in its pool.

I can think of several solutions:

A) Periodically sync the TX pools between nodes (might be costly, but could be minimized via techniques such as merkle root)
B) If the transactions are otherwise well-structured keep them in a pending state for some time before purging them (in case the Validator node is behind the rest of the network).

Actually for the B solution what makes things complicated is that we can't verify the TX signature because it signs the UTXO but we don't know which Public key it is until we find that UTXO. And so it can become a DDoS vector.

Open to ideas & discussion.

**Comment by Geod24** [comment]
0) How do others handle it ?
1) Should we build a transaction graph ? It would allow ordering and pruning;
2) The most simple approach is an LRU cache with an upper limit;

**Comment by AndrejMitrovic** [comment]
0. Yes

**Comment by Geod24** [comment]
Found https://www.researchgate.net/publication/344221715_Making_Transaction_Propagation_More_Efficient_Deferred_Transaction_Relay_in_Bitcoin

This turned out to be necessary to remove "register listener"... And CoinNet.

**Comment by omerfirmak** [comment]
I think our nomination and TX catchup scheme makes this issue obselete.

First of all, wallet should be the one responsible of making sure that the node it is communicating with accepts the TX, if not, retry or pick another node. Can do that thru the `hasTransactionHash` endpoint.

If any node accepts a particular TX and it is worthy of externalization (ie pays enough fees), it will be nominated and all peers will download it from that node.

If everyone agrees, we can close this one.

**Comment by hewison-chris** [comment]
We could return a Struct for `postTransaction` which includes an enum and an optional string. 
For example:
`tx` is accepted -> `{ sts : 0 }`
duplicate -> `{ sts : 1  }`
rejected -> `{ sts : 2, err: "Insufficient fees" }`
