### ISSUE TITLE
Ledger routines return boolean status codes but also throw

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1083]
https://github.com/bpfkorea/agora/blob/1af3731d063a8b52f1e114a4b31e5ac65ad70869/source/agora/node/Ledger.d#L207

And also:

https://github.com/bpfkorea/agora/blob/1af3731d063a8b52f1e114a4b31e5ac65ad70869/source/agora/node/Ledger.d#L268-L269

Here the assert might not get triggered because `saveBlock` is not `nothrow`.

All of this has to be fixed.

**Comment by Geod24** [comment]
This has been mostly fixed, there might be one or two inconsistencies left in other classes but not in the mentioned methods.
