### ISSUE TITLE
Remove the confusing log about the `receivePreimage` endpoint

### ISSUE THREAD

**Issue by linked0** [bosagora/agora#1104]
When a pre-image is received, which has the same distance as the existing one in the `ValidatorSet`, the log as follows comes out. This log appears so many times and is kind of confusing by showing the information something wrong happened.

```
node-3_1_90d86e12c2e8 | 2020-08-07 07:39:22,571 Info [agora.consensus.ValidatorSet] - Invalid pre-image data: The height of new pre-image is not greater than that of the previous one. Pre-image: { /*omitted*/ }
```

But the situation is very normal because the pre-image had been just received before a new request is received. So, we should check the pre-image received is already in the `ValidatorSet` and we do not call the `addPreimage` function if it is. And then we can remove the log above.

**Comment by AndrejMitrovic** [comment]
Looks like it's resolved now. Thanks @kchulj.
