### ISSUE TITLE
fixing Log.d that can cause segfaults under special circumstances

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1128]
The current implementation of agora logger in Log.d doesn't handle object lifetime correctly and in some corner cases it can even cause segfaults or log messages might be lost. I will post some code to reprocude those segfaults later.

**Comment by ferencdg** [comment]
Point 1:

the following innocent looking code will segfault, as we try to use the log object in the SimpleModule's destructor and the log object is already destroyed
![image](https://user-images.githubusercontent.com/19815616/90712878-2f202e80-e2ce-11ea-8333-19f72d89085a.png)

the following cause will also segfault, as the log object is not created yet and we try to use it from the SimpleModule's constructor
![image](https://user-images.githubusercontent.com/19815616/90713019-8e7e3e80-e2ce-11ea-847d-8680a0f23739.png)

Point 2:

so far this doesn't seem very serious as they can be detected and corrected easily, however the following situation can lead to very hard to debug bugs: if an object A is created on the heap for thread B and thread B is destroyed, the the runtime will also destroy the logger. We saw that with issue #1122 that object A can outlive the destruction of a static object(like logger in our case). If this happens we will get intermittent segfaults based on GC activity which is very difficult to track down

**Comment by ferencdg** [comment]
the fix will not be easy, the main problem is how to handle the case when an object would like to log in its destructor, but the logger object is already destroyed:

Solutions: 

1. If I allocate the logger object with GC, then it can be destroyed before the last client of that logger would use it: this is the case when the object outlives the destruction of the thread in the current implementation. In order to solve this problem I could just recreate a new logger object in the destructor of any clients that outlives the thread destruction(and the logger destruction). However Ocean's logger allocates GC memory when the lookup method is called(which method call is part of setting up a new logger instance), and allocating GC memory on a GC thread will throw an exception(and destructors hoping to log are usually called on a GC thread) . Without changing Ocean, this idea is doomed.

2. Allocate the Ocean's logger WITHOUT GC and the clients would take care of the ownership of the logger using something similar to C++'s shared pointers: the last client would destroy the logger. The problem here is that even though I could create Ocean's logger on NON GC memory area, the logger itself will allocate memory for various subobjects using the GC. This means that parts of the Logger object can be garbage collected any time... The problem is again with Ocean's implementation. 

I cannot give a 100% perfect solution without changing Ocean's logger, but I can modify the code that it will never SEGFAULTS. However if a client logs from its destructor AND the destructor is called from the GC thread, then that error message will go to stderr instead of the logfile. In addition to that logging from static destructors would work as expected: it would go to the logfile

**Comment by Geod24** [comment]
> the fix will not be easy, the main problem is how to handle the case when an object would like to log in its destructor, but the logger object is already destroyed:

GC-allocated object shouldn't be accessed from GC-run destructors, period. Did you find cases where it was ?

**Comment by ferencdg** [comment]
I haven't checked all the object destructors whether they try to log or not, but this is a potential issue. Also segfaults can occour not just with object destructors, but with static destructors/constructors too(see my example above), and I did see cases from logging from static destructors
