### ISSUE TITLE
integration test: sending SIGINT signal to docker_compose doesn't terminate containers

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1139]
sending SIGINT signal to docker_compose doesn't terminate containers on Ubuntu, so the test never ends

**Comment by ferencdg** [comment]
seems a vibe.d issue, here is a code to reproduce
```D
void main()
{
    runTask({
        requestHTTP("http://192.168.1.42:2828", // make sure this address is not reachable by ping
            (scope req) {
                req.method = HTTPMethod.POST;
                req.writeJsonBody(["name": "My Name"]);
            },
            (scope res) {
                logInfo("Response: %s", res.bodyReader.readAllUTF8());
            }
        );
	});

       runApplication();
}
```

when you hit CTRL+C, you get:
![image](https://user-images.githubusercontent.com/19815616/91145516-ca0a7580-e6df-11ea-9e5a-6905a9930ec2.png)
but it never terminates

**Comment by AndrejMitrovic** [comment]
Maybe related to https://github.com/vibe-d/vibe.d/issues/2463?

**Comment by ferencdg** [comment]
> Maybe related to [vibe-d/vibe.d#2463](https://github.com/vibe-d/vibe.d/issues/2463)?

yes, good point, this is the same issue probably -> this issue causes our integration tests to never terminate

**Comment by AndrejMitrovic** [comment]
I wonder if `"versions": [ "VibeHighEventPriority" ]` would fix any other of our CircleCI problems we have.

**Comment by ferencdg** [comment]
my toy example above did quit with VibeHighEventPriority.... And now getting the all familiar 
Warning (thread: main): leaking eventcore driver because there are still active handles
warings from issue #1136

**Comment by ferencdg** [comment]
as discussed this an upstream issue and we have a workaround
