### ISSUE TITLE
investigating why CircleCI failes with ldc-1.23 

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1167]
Mathias suspects https://github.com/ldc-developers/ldc/pull/3424

related agora PR: https://github.com/bpfkorea/agora/pull/1134

**Comment by ferencdg** [comment]
suspicion was true - I compiled ldc with 
PR included - aaeb7f755fe16e9dad21c7fa778efee973ed0217 -  systemtest-simple build failed
PR ecluded - 24af7a32e7a25f86d6d9d28e4b8345bed5eb24f0  -  systemtest-simple build succeeded

**Comment by Geod24** [comment]
Fixed by #1134
