### ISSUE TITLE
The latest SCP envelopes need to be saved & restored in case of a crash

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1170]
If a validator node crashes during a consensus round then we must restore the node's latest nomination & ballot protocol messages the next time the node boots up.

SCP explicitly supports this exact scenario: https://github.com/bpfkorea/agora/blob/0bb013fbd6e7ed22999fb1bb9a86a92c2cd58fdc/source/scpp/src/scp/SCP.h#L97-L99

We need to store `getCurrentState()` and **not** `getLatestMessagesSend()`. The former contains all the latest messages for each node, while the latter only contains the most recently broadcasted message by this node.

From the SCP whitepaper what we need to save is the `N` from Fig. 14. from the nomination protocol (because `X`, `Y`, and `Z` can be regenerated using it), and the `M` from Fig. 16 from the ballot protocol (latest ballot message from each node).

**Comment by AndrejMitrovic** [comment]
In addition to this we also need to look into what happens to the timer routines. Presumably a crashed node will have to call `scp.nominate` again, however it will start the protocol from nomination round 0 - which may be wrong depending on when the node crashed.

In fact the Stellar devs have recently run into this same problem: https://github.com/stellar/stellar-core/issues/2081

Therefore we should monitor that issue closely and also work towards updating our bindings to the latest SCP version.

**Comment by AndrejMitrovic** [comment]
This issue will solve https://github.com/bpfkorea/agora/issues/640 as well. You can take a look at how Stellar does it:

https://github.com/stellar/stellar-core/blob/e88d1006292cf523b7c6b21c097d1e3cd24db8a6/src/herder/HerderImpl.cpp#L1557

It stores the latest envelopes on disk, and then reloads them. We would do something similar. 

In fact this entire code section is wrong:

https://github.com/bpfkorea/agora/blob/6150d764a227e636b192e5f4196b23939cc5ec6d/source/agora/consensus/protocol/Nominator.d#L250-L268

We should not be restoring SCP state from the blockchain, but from the envelopes themselves. And only the latest envelopes (the latest slot index) are needed. Essentially we would store `getCurrentState()` data to disk, and later load it and call `scp.setStateFromEnvelope` with it.

**Comment by TrustHenry** [comment]
@AndrejMitrovic I confusion has arisen.
Among the envelopes obtained by `getCurrentState()`

```
SCPStatement(0x92a8..., 1, {"nominate":{"accepted":{"base":"[  ]"},"quorumSetHash":{"base":"0x4e73..."},"votes":{"base":
SCPStatement(0xdcaf..., 1, {"nominate":{"accepted":{"base":"[  ]"},"quorumSetHash":{"base":"0x4e73..."},"votes":{"base":
SCPStatement(0x129b..., 1, {"nominate":{"accepted":{"base":"[  ]"},"quorumSetHash":{"base":"0x4e73..."},"votes":{"base":
```

Which envelope should I put in the `scp.setStateFromEnvelope()` ?

**Comment by TrustHenry** [comment]
I've heard from @AndrejMitrovic that all of them store. 👍
