### ISSUE TITLE
Refactor the testsuite to start with the test block

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1176]
Currently, when starting the test-suite (localrest) we specify the number of nodes.
This means that `agora.test.Base` needs to create a different genesis block per test.
I don't think that's something we need. If the test needs to support a specific number of validator, we can simply provide a function to advance the blockchain to the next enrollment cycle, which can be whatever we want.

**Comment by AndrejMitrovic** [comment]
> I don't think that's something we need.

We don't need it anymore. We did need it in the past, but now its very easy to create additional enrollments at a new block height. So 👍 .

**Comment by Geod24** [comment]
PR: https://github.com/bpfkorea/agora/pull/1239
Unfortunately not yet ready.

**Comment by hewison-chris** [comment]
This issue is now being implemented by smaller incremental changes than PR [#1239 ](https://github.com/bpfkorea/agora/pull/1239)
I expect to have all the PRs ready by Wednesday afternoon.

**Comment by Geod24** [comment]
Fixed by #1304
