### ISSUE TITLE
Schnorr verify() can cause a halt if signature is corrupt

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1177]
When verifying a signature the signature scalar needs to be converted to a point:

https://github.com/bpfkorea/agora/blob/be140d581db436edac3c470a2c603730d0a85a8b/source/agora/common/crypto/Schnorr.d#L239

However if the scalar is invalid (for example zero) then this will trigger an assertion failure:

https://github.com/bpfkorea/agora/blob/be140d581db436edac3c470a2c603730d0a85a8b/source/agora/common/crypto/ECC.d#L151-L152

We need to be able to reject malformed signatures without halting the node.

Test-case:

```D
unittest
{
    Signature sig;
    const K = Pair.random().V;
    assert(!verify(K, sig, "foo"));
}
```

```
$ dub test
> core.exception.AssertError@source/agora/common/crypto/ECC.d(152): Assertion failure
```

**Comment by Geod24** [comment]
Do you know if we can enumerate invalid input ?

**Comment by AndrejMitrovic** [comment]
That would imply I have read the Schnorr specification.

**Comment by Geod24** [comment]
Actually, the Curve25519 spec. I **think** there are only 2 invalid values, but don't take my word for it.

**Comment by AndrejMitrovic** [comment]
Yes you are right. It's the curve, schnorr is just the scheme using this curve. Doh.

**Comment by hewison-chris** [comment]
https://libsodium.gitbook.io/doc/advanced/point-arithmetic#scalar-multiplication-without-clamping
If we are using the crypto_scalarmult_ed25519_base_noclamp function then I believe if n is 0 or is greater than L (order of the main subgroup) it will return non-zero and we would assert. Perhaps I can take this issue and add the unit tests once we define the behaviour that we want.

**Comment by hewison-chris** [comment]
https://github.com/bpfkorea/agora/pull/1183 should address this.
