### ISSUE TITLE
Implement `waitForPreimages (Height)` in Base.d : TestAPIManager

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1185]
The need for this becomes more apparent once we start requiring preimages for reaching consensus & validating block signatures.

**Comment by linked0** [comment]
I will take this issue for this sprint after Brian's confirmation. The requirement of this issue is also needed for issue #1079 and I was already planning to implement the function like that as part of #1079. I think the `expectBlock` is a good reference for the implementation.
