### ISSUE TITLE
Replace public key node_id in SCP messages with an index

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1191]
This is an optimization that is similar to https://github.com/bpfkorea/agora/issues/982.

SCP statements currently contain:
- node_id (64-byte key)
- slot_idx
- signature

However because we are using staking we have the opportunity to optimize this and reduce the network load.

`node_id` can be replaced with a 2-byte `ushort` index - which can encode up to `65535` validators (there is a theoretical limit of 1000 validators, might be relaxed later). The index would be used to look up the node's public key, e.g. `PublicKey[ushort]`. We can assume that for a given slot index there is a corresponding mapping between an index and the public key. We can sort the public keys to generate the index of each key.

The new SCPStatement would then compose of:
- ushort node_idx => maps to the PublicKey
- slot_idx
- signature

In addition to changing SCP code, this will require changes to the Nominator:
- When verifying statement signatures we must have an associated `node idx => public key` map to extract the public key from and thereafter verify the signature
- We might need to keep the last N slot index mappings. In other words, `slot idx => node idx => public key` for the last N slots - where N could be define later. The reason why this is needed is to allow late collection of block signatures. If for example slot 1 was externalized and slot 2 began nomination then we might receive a late schnorr block signature for block 1. In this case we need to be able to verify the SCPStatement's signature.

**Comment by Geod24** [comment]
Unblocked thanks to #2134 being fixed (soon ™️ )

**Comment by linked0** [comment]
**How to implement**
1. Provide methods to find an index for a UTXO used as NodeID, or a UTXO for an index at a specific height as follows.
https://github.com/linked0/agora/blob/6003d0af7dcc7907a006feeaaf376e9725620649/source/agora/consensus/EnrollmentManager.d#L716-L736
2. Change the `SCPStatement` structure as follows.
```
struct SCPStatement {
    uint16_t nodeIndex;
    uint64_t slotIndex;
    _pledges_t pledges;
}
```
3. Before adding a `SCPStatement` or getting it from/into `SCPEnvelope`, we should convert the `nodeIndex` of a `SCPStatement` to a real `NodeID` and vice versa. There are more things to research about this.

**Comment by linked0** [comment]
If we change the type of `NodeID` from `Hash` to `ulong`,  we should add a variable like `update_height` to `SCPQuorumSet`. It's because the index of the validator change when there is a change in enrollments. If there's something I'm missing, please let me know.
