### ISSUE TITLE
Upstream our changes to isQuorumSetSane

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1198]
To make upgrade more smooth. Work was done here: https://github.com/bpfkorea/agora/pull/549
It needs to be upstreamed to https://github.com/stellar/stellar-core/ in proper C++.

**Comment by AndrejMitrovic** [comment]
I suspect we don't actually need this changeset anymore. Now that the quorums are auto-generated isQuorumSetSane should never fail.

**Comment by Geod24** [comment]
Still would be good to have, and probably not too hard.
Also this: https://github.com/bpfkorea/agora/commit/2b787c8fde8999854347072134e0bc9c34e58399
