### ISSUE TITLE
does  source/scpp  realize all 16 THEOREMS writing  in  "The Stellar Consensus Protocol"

### ISSUE THREAD

**Issue by sdhczw** [bosagora/agora#1201]
we also want to use the stellar consensus protocol in our project,  does source/scpp  support the full stellar consensus protocol with all 16 THEOREMS in  paper？

**Comment by Geod24** [comment]
The code in `source/scpp` was taken verbatim from `stellar-core` (as stated in the README). So yes, it should be faithful to the white paper implementation.

**Comment by AndrejMitrovic** [comment]
Please be aware that we have made some modifications to it. It's recommended to look at the source at https://github.com/stellar/stellar-core/tree/master/src/scp

**Comment by sdhczw** [comment]
if we want to use it ,do we just migrate stellar-core/src/scp to our project ，furthermore we see you are testing bogb/scp，does it fulfill all scp in go？

**Comment by AndrejMitrovic** [comment]
> if we want to use it ,do we just migrate stellar-core/src/scp to our project

Yes, however I don't know how well you can integrate a C++ project into a golang project.

> Furthermore we see you are testing bogb/scp，does it fulfill all scp in go？

No it does not. `bobg/scp` is a prototype implementation written in golang, it is not a production-ready library. We only used it for brief secondary testing of various quorum configurations - however I do not recommend using it in production.

**Comment by sdhczw** [comment]
in our team our pan have some difference，one think we just migrate  src/scp ，another is migrate all stellar code，but remove network and ledger.  I agree with the first，because it is light。but another engineer say just migrate src/scp not fulfill all 16 theorems in paper, and use all source files can cover them. Unfortunatly, i am not familiar with stellar code .

**Comment by AndrejMitrovic** [comment]
For questions about using or adapting the SCP protocol I recommend asking here:
- https://groups.google.com/forum/#!forum/stellar-dev
- https://stellar.stackexchange.com/

As for a general overview of how SCP works, there are many resources:
- https://www.scs.stanford.edu/~dm/blog/simplified-scp.html
- https://www.stellar.org/developers-blog/intuitive-stellar-consensus-protocol
- https://medium.com/stellar-development-foundation/on-worldwide-consensus-359e9eb3e949
- http://www.scs.stanford.edu/~dm/blog/safety-vs-liveness.html
- https://medium.com/stellar-developers-blog/why-quorums-matter-and-how-stellar-approaches-them-547336c1275

As for your initial question:

> does source/scpp realize all 16 THEOREMS writing in "The Stellar Consensus Protocol"

Yes. But please be aware we do not offer any support if you end up using our own fork of SCPP in https://github.com/bpfkorea/agora/tree/v0.x.x/source/scpp - it contains modifications and may be outdated compared to the stellar SCP source repository. We recommend using https://github.com/stellar/stellar-core/tree/master/src/scp instead, which is the latest version that is up to date and known to work.

Thank you for your interest in the project.
