### ISSUE TITLE
Add the dlang bindings from issue #1202 to DRuntime

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1203]
depends on #1202 and needed by #1173

**Comment by AndrejMitrovic** [comment]
The title should reference a concept or code that is in mainline. As it stands `InetUtils` doesn't exist yet (it's not in `v0.x.x`). Maybe we'll even rename it. So, I'd rename the issue to: `Add ability to retrieve all public IPs of the local machine under MacOS`.

**Comment by Geod24** [comment]
Fixed: https://github.com/dlang/druntime/pull/3215
