### ISSUE TITLE
Upstream our SCP changes to abstract the hash function

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1220]
Currently we have a file to abstract away this (https://github.com/bpfkorea/agora/blob/v0.x.x/source/scpp/src/crypto/Hash.h).
This poses some problem when upgrading and it would be good if we could move those changes upstream.
Upstream will probably want this in `SCPDriver` as [there are precedents](https://github.com/stellar/stellar-core/blob/49a14db54ecb15154f5a7af9b7c0d2e8b6862707/src/scp/SCPDriver.h#L73-L80), but that's up for discussion.
Assigning @AndrejMitrovic since he made the abstraction.

**Comment by AndrejMitrovic** [comment]
I'm gonna file an issue upstream and ask if they would be ok with such a change, and if they have a preference on how to do it.
