### ISSUE TITLE
Replace transaction set and enrollments in ConsensusData with hashes and/or a merkle root

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1228]
This is the counter-issue to https://github.com/bpfkorea/agora/issues/993. #993 should likely be closed and this issue should be worked on instead. 

Voting on entire transaction sets is not scalable. This will become more apparent when:

- There are many transactions in the pool to nominate
- The block size limit is increased (imagine voting on 4MB transaction sets, it could take minutes to transfer this data)
- There are dozens, hundreds, or even thousands of validator nodes

As a first step we can do the following:
- Add an API end-point for a node to be able to retrieve a set of transactions from another node's transaction pool. What should the API look like? If we design it as `getTransaction (Hash tx)` then this may cause many requests to the node. It could be `getTransactions (Set!Hash txs)`. There might be other alternatives.
- Replace ConsensusData internal fields to be hashes of tx'es and hashes of enrollments.

Then we must also fix the nominator:

- Carefully inspect the `Nominator` validation routine. SCP supports returning `kMaybeValidValue` in the [validateValue](https://github.com/bpfkorea/agora/blob/bbf523199b6efd1667ee0e3d79ad59d4c3ea93c2/source/agora/consensus/protocol/Nominator.d#L539) SCP routine. See [this comment](https://github.com/bpfkorea/agora/blob/406a22df4c33dfd2f2e3a61811fe6e73aea94852/source/scpp/src/scp/SCPDriver.h#L56-L58). One possible approach is: Find as many transactions from the `ConsensusData` transaction hash set inside of the transaction pool. If all transactions are found and all are valid => return `kValidValue`. If some transactions were not found, but they all still valid, return `kMaybeValidValue`. If **any** found transaction is invalid => return `kInvalidValue`.

-----

As a final step we should consider replacing the hash set of transactions with a merkle root. It's possible to skip the intermediate development step of changing `transaction/enrollment set => hash set => merkle root` and go directly to the idea of changing `transaction/enrollment set => merkle root`, but I'm afraid this might become a multi-sprint issue. Doing this piece-meal might be better.

**Comment by omerfirmak** [comment]
> If some transactions were not found, but they all still valid, return kMaybeValidValue

As far as I can see, stellar-core never does this. It does not make any decision about an envelope until it has all the necessary information.  They also vote on tx set hashes, not individual tx hashes.

I am thinking that we can adopt a similar but a more relaxed approach. Validator can return `kMaybeValidValue` for the nominations that it is missing some TXs.  If network manages to nominate some values for balloting phase, it's all good.  But if no nomination can be validated by a quorum, we will be stuck in nomination forever. For example, if every node has different TXs in their pool no one will be able to fully verify any values. 

If we cant proceed to balloting, we should make nodes run a catch-up mechanism for TX pool. This will let some nodes to eventually catch up on the missing TXs.  But since we discarded the earlier nominations at this point, we need to let nodes nominate more than once in the nomination phase. I think, [this ](https://github.com/bpfkorea/agora/blob/e71a41523551cfaa6645a22503273dd56b268283/source/agora/consensus/protocol/Nominator.d#L347 )prevents it at the moment. Correct me if I am wrong.
 
I am not really familiar with merkle trees. I did some quick googling, I completely get their use in validating a TX set. But can we really use it in reverse to build the TX set as well? Is it what proposed here or I am missing something?

**Comment by AndrejMitrovic** [comment]
> As far as I can see, stellar-core never does this. It does not make any decision about an envelope until it has all the necessary information.

https://github.com/stellar/stellar-core/blob/54b03f755ae5d5aa12a799c8f1ee4d87fc9d1a1d/src/herder/HerderSCPDriver.cpp#L313-L320

> They also vote on tx set hashes, not individual tx hashes.

Yep. And it seems to be quite complex how they derive this hashing: https://github.com/stellar/stellar-core/blob/54b03f755ae5d5aa12a799c8f1ee4d87fc9d1a1d/src/herder/TxSetFrame.cpp#L454

It's probably very stellar-specific in this case. 

> I think, this prevents it at the moment. Correct me if I am wrong.

I think it should be possible to cancel the nomination and then try a new one with a different set of transactions. But I'm not sure if this would break the SCP protocol rules. What does Stellar do? Do they have the same problem where nodes can get stuck if each one tries to nominate an entirely different tx set hash? Or do they attempt to download unknown tx sets and re-nominate?

> I am not really familiar with merkle trees. I did some quick googling, I completely get their use in validating a TX set. But can we really use it in reverse to build the TX set as well? Is it what proposed here or I am missing something?

I think I might have misappropriated them here. In Stellar's case they just sort the transactions and hash-concatenate them all together. They don't actually build a merkle tree. So it may not be necessary. My very abstract idea was to be able to somehow derive which tx's the node is missing based on the merkle tree, and then only fetch those missing transactions from other nodes. But I don't know if that's doable with merkle trees.

**Comment by omerfirmak** [comment]
> https://github.com/stellar/stellar-core/blob/54b03f755ae5d5aa12a799c8f1ee4d87fc9d1a1d/src/herder/HerderSCPDriver.cpp#L313-L320

Oh, I meant that they never return `kMaybeValidValue` for missing TXs, sorry. In that specific case the reason they do that is that the network and node is at different heights. https://github.com/stellar/stellar-core/blob/54b03f755ae5d5aa12a799c8f1ee4d87fc9d1a1d/src/herder/HerderSCPDriver.cpp#L237

>  Or do they attempt to download unknown tx sets and re-nominate?

They save the envelopes in a `pendingEnvelopes` list and only vote on them when the node has all the necessary information. If they can't fetch the tx set, node votes against that envelope. https://github.com/stellar/stellar-core/blob/54b03f755ae5d5aa12a799c8f1ee4d87fc9d1a1d/src/herder/HerderSCPDriver.cpp#L358-L380

**Comment by AndrejMitrovic** [comment]
So do you think we can at least switch to voting on transaction hashes / tx set rather than transaction sets? Similar to how they do it in Stellar? 

The main issue of #1228 is that of bandwidth. If we consider a block size limit of even just 1MB then voting on a 1MB transaction set becomes very slow. All that data is currently passed over the network even if the other nodes already have all the transactions that are being voted on.

**Comment by omerfirmak** [comment]
> do you think we can at least switch to voting on transaction hashes

Oh we definitely can. The question is how defensive we will be in our implementation. If we think that missing TX case would not be wide spread in the network, we can even ditch fetching the TXs. If a small number of nodes are missing some TXs, they can simply wait for the rest of the nodes to create a block. And then they can catch up. This is the least defensive approach.

The other end of the spectrum is not voting on an envelope until we have all the TXs or a timeout is reached. I would go with this and experiment with more relaxed approaches in the future.

> The main issue of #1228 is that of bandwidth

Yep, currently we are voting on almost complete blocks :)

**Comment by omerfirmak** [comment]
`extractValidValue` [here](https://github.com/bpfkorea/agora/blob/bab193fb880a2ee1638a848e5aacb5213450320c/source/scpp/src/scp/NominationProtocol.cpp#L383) looks interesting as well. A node can extract the known TXs from a nomination and re-nominate a subset.
