### ISSUE TITLE
Implement the ability to continuously generate transactions and send them to Agora nodes

### ISSUE THREAD

**Issue by kchulj** [bosagora/agora#1230]
This is one feature to simulate activity on an Agora network.
The tool should have the ability to continuously generate new valid transactions and send these to one (or more) Agora nodes. This process should be automated.

Part of #1227

**Comment by AndrejMitrovic** [comment]
> An Agora node should have the ability to continuously generate new valid transactions 

Not the node. A tool.

**Comment by TrustHenry** [comment]
Expand `agora-cli` ?
Or will you make a separate tool?

**Comment by kchulj** [comment]
> Expand `agora-cli` ?
> Or will you make a separate tool?

For this feature, I'm thinking of expanding `agora-cli`.

**Comment by Geod24** [comment]
> Part of #1227

It seems to me that it completely overlaps with #1227 . What does #1227 have that this does not ?

**Comment by kchulj** [comment]
> > Part of #1227
> 
> It seems to me that it completely overlaps with #1227 . What does #1227 have that this does not ?

To me, #1227 looks like a "tool suite" with extended features such as double-spending, DDoS with good/bad API requests, etc.
This issue focuses on generating and sending valid transactions, so I broke it down to a smaller issue.

**Comment by Geod24** [comment]
Is it deployed ? ;)
