### ISSUE TITLE
Expose an endpoint for exporting stats to prometheus

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1238]
In order to allow developers to better monitor the application, we should export some stats.

Essentially, we want to expose an HTTP endpoint under `/metrics` which provide Prometheus-formatted metrics.
Luckily, Ocean already has an implementation of a [Collector](https://github.com/sociomantic-tsunami/ocean/tree/v5.x.x/src/ocean/util/prometheus/collector), so all we need is the HTTP endpoint that does to link (example [here](https://github.com/sociomantic-tsunami/ocean/tree/v5.x.x/src/ocean/util/prometheus/server)), and to actually collect the stats.

Prometheus uses a pull model, which means it will call us, we don't "export" to it (although the later is possible, if needed).
Our Prometheus instance use the default interval for collection of 15 seconds;

Metrics we should collect (those are suggestions and can be discussed):
- Transactions: Received, accepted to TxPool, rejected (perhaps even with reason), TxPool size, total amount in pool;
- Endpoints: Number of request received per endpoints (e.g. `GET /public_key`);
- Blocks: For each externalized block, new enrollments, transactions, tx total amount;
- Validators: Number of validator, number of pre-images known ahead of time;

Additionally, some non-static data might need to be known, for example the deployed version. For this we should use [this technique](https://www.robustperception.io/exposing-the-software-version-to-prometheus).

**Comment by AndrejMitrovic** [comment]
I predict it's gonna be a little bit difficult to integrate those ocean classes with vibe.d's event loop.

**Comment by Geod24** [comment]
Check the  code, the Collector part is separate and doesn't depend on epoll.

**Comment by AndrejMitrovic** [comment]
Yep, I misread it at first. 👍

**Comment by Geod24** [comment]
Fixed in #1249
