### ISSUE TITLE
Make the order of inputs and outputs in a transaction well-defined

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1248]
As mentioned by @Geod24 in Slack:

> Mathias Lang: KuChul Jung and I discussed something yesterday in the whiteboarding session. If we force inputs to be in ascending order of UTXO, we can simplify our double spend prevention by simply checking that each entry is > to the previous one. This also reduces the amount of valid transactions that can be send to us, possibly helping with the transaction nomination thing we talked about. Thoughts ?

Once this is completed then a transaction will require that the inputs and outputs are sorted. 
For inputs the sort is by `utxo hash` and for outputs it is the `lock` (`lockType` then `bytes`) followed by the `value bytes`.

**Comment by Geod24** [comment]
Yeah that doesn't actually work. Because even though we can check it on a transaction level, we'd have to create an array with all inputs for this to work.

**Comment by Geod24** [comment]
Changed the issue title and scope to just make the transaction more rigorous about the order of things.
