### ISSUE TITLE
Validator does not re-enroll after cycle expires

### ISSUE THREAD

**Issue by kchulj** [bosagora/agora#1254]
Currently, the `validator_cycle` is set to 20. The validator does not re-enroll after 20 blocks so more blocks cannot be created.

```
Fatal [agora.consensus.protocol.Nominator] - tryNominate(): Invalid consensus data: Enrollment: Insufficient number of active validators.
```

Triggered by `Ledger.d` :
```D
if (block.header.enrollments.length + active_enrollments < Enrollment.MinValidatorCount)
    return "Enrollment: Insufficient number of active validators";
```

There should also be an option in which the validator does not want to re-enroll.

**Comment by AndrejMitrovic** [comment]
@Geod24 what happens when the operator wants to exit? How do we force the node not to re-enroll when the enrollment is about to expire?

I think this can be done by just sending a spend tx for the freeze tx (through the wallet), and then the Validator node would pick that up and realize it can't re-enroll so it would stop trying to enroll. Sounds good?

**Comment by Geod24** [comment]
> I think this can be done by just sending a spend tx for the freeze tx (through the wallet), and then the Validator node would pick that up and realize it can't re-enroll so it would stop trying to enroll. Sounds good?

Sounds good. We could also do it through the admin interface, but for the time being, just sending the TX is good.

**Comment by Geod24** [comment]
This is still happening: the live system is currently stuck at 1999 blocks and the logs are spammed with:
> Jan 10 18:12:17 eu-002 docker[2332]: 2021-01-10 18:12:17,741 Fatal [agora.consensus.protocol.Nominator] - tryNominate(): Invalid consensus data: Enrollment: Insufficient number of active validators. Data: { tx_set: [{ type: TxType.Payment, inputs: [{ utxo: 0x84f7c196c6ee6da38a26b15fbed2614dfb85d2d7c1cd47f0e86f9c16d7a68190052a60f0b35e67f61b97b6257221f5178230bcd7fee287f78438e8255b6894fa, signature: 0x0aafd0cd5aa15fe95cda1abf0acc19bb5c16ac98b6356d41dfd76d5a5372eae0032638d4857f7d623910fe3c6ebc0d3c246b3db02b9e176ba184b995fcb19abf }, { utxo: 0x18364e92c952a621211956b7b3af95dbdb184ad041e0d9bc06ee4cfd5350785c408fe709f88a509ea29ef716fb68fa860e4291b1e809303a309cd5ba612b57b8, signature: 0x095e1c2ce64339176357ec17654624dda1fad04ab12a78d71bb1aebb5309202fa08aa3b611261ac058d66b5009a3945e24e25e0ea304ceb1f0ce2f2d305e3e00 }, { utxo: 0xcb58b09480912b68527903ccd3d5121c1df57f6b1657e593383fbcc03cd007beb6429ceb14b704837460a71ae95505d6d19f51081df59ad400a88714ce911c8c, signature: 0x0f5a2f036b91a5b169632085d0f9b2aa287cdca920de2bb87d2638bc080feecaeb6587de25efba36cf1a8542b958ca60d4a156d9e058eb2ed40dcad8c3a7003a }, { utxo: 0x6433df6989500b78172533ae9e3a41c3a2224d4555bd55e6a4e52b42dd3f19d4d0b4469a0bde44a1b7b7cc774f70d77524a20b5ebb5e4dac10dea61c7144aab0, signature: 0x0fc3425035f823cec593b7cca8226060a16b2b7c2bb3c11852ad5aa9299dffef9665e03e9cb7c21af3cfd1a4bf31761aa3bef6015c9214bc6fd936721e50efea }, { utxo: 0xdc0c5a022b8e9622d95a5315631f200bd3373e64104f5855391c81770643cd1139d4b06c3efde8502eb52e0e180686517385dfa5c22cdcb6ab5fb5acad1914f5, signature: 0x00c141012e5d8a8a172f9494315e35175b896af211d7aaf842ab676abc78ec02c43b153384ab40fa756db6e0e542498470db6ac4317bcb130275008d9a5cfdd4 }, { utxo: 0x71b18fff926826c7230278ccbfab076a6b8dc02d4e1b4ddd7e8d8e3940bd75c5a5fd52ddd6e6fe1b4d8fbbde935bfca88ac4e77b7b66692b4ec2caff9b6b01de, signature: 0x0d9554a5748b95111ca6cd5c903728d2cbb49d6c16766bc53b542de50226119dc9cb14931c3dd59cb321578c6decb31895220950eb8a6f95c9c8a0f0017d1bd9 }, { utxo: 0x131182c72c90d025cf2cc799821bcb8f64e19c8e4850a76bc4dd37d0cd455ef8ca98576fd1a5ce1cf061497104ef915375c666d827adfc0c0540a7727fd6d9b0, signature: 0x0eb05b22c568a7dd5d7b017efb2f8ea87b1da94a14fb5468bed0e9422a1dbc1efd78cd6a62f9d3b244d501603bd5f3579a202463ee4af83ecb08fc8052376c02 }, { utxo: 0x0b4143e999579ef4bd0cc81cc55551980ebc38f6713b3c3b5d0af01e441763956af8ffe89de5dba14e774d918990a9dd61f2d49db29a7f2768635b90375c7a86, signature: 0x0c7c993fbe701e8d831b7335821f842ff372a2f2f1efd2e4430d00f35e93306769130aeb6292c78383ba1da8889e0a2fb513720cd9c9c0851487fa432e59ba29 }, { utxo: 0x83f70fed3e47822419b2cde4ae848edb73dcbaf0500487e333876fbf659ed931b79472c03c74ac8338b96736830dfea430f28c051e17905b4cdd5ddfca4f0f53, signature: 0x08b7a1c0d16d961b96f78d3506c009cc50d5345bd34fd00df3f850fd9c502c99f0d0ae2001b4a5a680e460d6c4a48dba07ba8f7a43be938242b7902348a85664 }, { utxo: 0x71e370df0e555652217fe9fe6b4a92d0eada978f5c265f868c64f6b3c50b7638284b9fe62a12abe7af43a0b94850c29936b9099aa01205a9e0a301744416a05d, signature: 0x0b6bfa1726155dc334d44734c593f740ef73ce5b90096ab62f91e7ffe09a59ba1163ffd6785fbd7a849b6ed859e31c879148feaa0186fdbfbd5b321298bf7aeb }, { utxo: 0x783c2668deb2c9cdc2cbea239e1e568e77e5c0d64fa2d2814ba9be40f9f8d9d340708564e1454ce368b54ce50d7e0b045974d94a2b6f405b7acc9ecf70e6cc87, signature: 0x068b1d86f80cdc8fcb73b4623a84cabc520d3533a69c54c38a8b42e4bf669dad307911fb45f226f2548a11dd992e24c2016abc91808dc4a03b27071307fc9fab }, { utxo: 0x7b169f4f134c0db6861dd96590e8f84fd32977fc79357a482ea12bd660b51649ecfece32a2321c82a33d88ae15ddc879a4978cd9f427e8ba00f1f038f52d9423, signature: 0x0aa6854b6df6c105744efafb38d172bf31906c3299c5016561c8c5cb3261d4787ad8da3e8f7c5e131fc0a7a0f0bb5a522bbfc59a5fe38682ef71354949819656 }, { utxo: 0x5adaf60de4987124ddeedd536fada05a4d48e34c679631aeef6ce2ed573a212419131d673b898cf28a4969f5d1e7c231bc6d79c242e105e631cff096827c1c84, signature: 0x0db7f05e1bc3d60b7e357c42fc1f1bd4d30381a37bfda1704ba9dd6ae0e664992141bb261d9bc75e4b3bc72954d63cf46159dc67b57f6429135cfe812952a50f }, { utxo: 0x54e8cfe6164fe4106f74f55a8ce3ba7af0515129ecd4e5e0efb9f7ee7c8fecb9cf940198f2f5f95eeafacbfea94aa7360063c6296cd9e72268b7cbd6abedf0b0, signature: 0x0d50a3e0b740e94edbd33b2d4bc1157f62e6ad967e81ffc71aa461289e832401894a9edfbe2a701bb63930dd2090f9975df50b233ca766e411996111418eb0ab }, { utxo: 0x170c53a2ecc838a31eab2ad0924de4ac60cbdc3c7b2618b2e1512425b863cb6ce1bc5fbebfb6f3d4cb0df7d8d804d40fbfafda97a5440372939cba27af765204, signature: 0x0c51efecbeb1f7f49e27b9af696bdbd2051276d220fb90153ff38b64851e367939c2554a502ac7d6ecc02f418b5217c09056049be1a553d2ea987bf5a7b66237 }, { utxo: 0x8964fac5de3e58c59075b5d527882ecc810bee65d40dacc1214cb0d89e25151d72604baad412c0dba64e00e3eded9c7c7eeeaa42ce28f81ad2cfd19c571d9065, signature: 0x0edf7fe2fbac75ccffd9a5cbe7c1f25164b87f62877fa986a2e1183475fb07843712ca8fb236c3ec0e1c099764ffcca153eee9f68e65fb501a9f3f5d08765629 }], outputs: [{ value: 1225510816143153, address: GDCL22VTWCM2K3TJO3IX3FSQVSAIHLHN46GOIRNNLA3CMARCOR4SP4PA }], payload:  }], enrolls: [], missing_validators: [], timestamp: 1610302337 }

**Comment by omerfirmak** [comment]
We probably hit one of the edge cases we discussed [here](https://github.com/bpfkorea/agora/pull/1293).

**Comment by omerfirmak** [comment]
I don't think https://github.com/bpfkorea/agora/pull/1293/commits/76c923877199db7d7e3ca39072e49f91e2a0b51c is working as expected. I don't see any attempt to enroll when nodes get restarted at height 1999.

**Comment by omerfirmak** [comment]
I think this is the correct way of doing it. We should check if we need to enroll regardless of the enrollment status. We could be restarted on the last block of our cycle.

``` diff
diff --git a/source/agora/node/Validator.d b/source/agora/node/Validator.d
index 431b6f2d..4fb9b7fc 100644
--- a/source/agora/node/Validator.d
+++ b/source/agora/node/Validator.d
@@ -234,7 +234,7 @@ public class Validator : FullNode, API
 
         if (this.enroll_man.isEnrolled(&this.utxo_set.peekUTXO))
             this.nominator.startNominatingTimer();
-        else if (this.config.validator.recurring_enrollment)
+        if (this.config.validator.recurring_enrollment)
             this.checkAndEnroll(this.ledger.getBlockHeight());
     }
```

Nodes should've sent an enrollment request when Block #1999 was externalized tho. I dont see any enrollments in the nominated `ConsensusData` . Also, I think logs are not persistent. I can't see the point where #1999 was externalized.

**Comment by AndrejMitrovic** [comment]
Oh oops, I should have caught that in the review.

**Comment by omerfirmak** [comment]
It's an easy mistake to both miss and make :smile: I'll have a small PR for this with a couple of improvements on this issue.

**Comment by omerfirmak** [comment]
This evolved into https://github.com/bpfkorea/agora/issues/1500, we should track it there.
