### ISSUE TITLE
[Upstream] Implement support for custom serialization in Vibe.d

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1263]
Currently, Vibe.d's REST generator expects JSON-formatted input and outputs JSON-formatted output.
This is quite restrictive, as one may wish to implement something based on the content type. Also, REST is not JSON.
We have two use cases for this already: the name server, and the QR code generator. The name servers suffers from the impossiblity to control the output formatting, and the QR code generator just needs to write an SVG.

**Comment by ferencdg** [comment]
done by: https://github.com/vibe-d/vibe.d/pull/2492
