### ISSUE TITLE
Fix linking issue with QuorumIntersectionChecker.create()

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1265]
There is still an unresolved issue with linking on Windows. Currently the Windows test for `verifyQuorumsIntersect()` is a no-op.

The unittests on all platforms already test the exact quorum layout output, so there shouldn't be any uncaught bugs. But it would be good to resolve this issue regardless.

https://github.com/bpfkorea/agora/blob/b56e22526f4c6f74f609035fbb2490599f57e8a2/source/agora/consensus/Quorum.d#L598

**Comment by Geod24** [comment]
Closing as we disabled Windows for the time being, as it is too resource intensive for the CI and the user base is almost inexistant (and can use WSL instead).
