### ISSUE TITLE
Test Agora node with unexpected data

### ISSUE THREAD

**Issue by kchulj** [bosagora/agora#1270]
We need to see how Agora handles different cases.

Below are some scenarios that have been suggested:
- DDoS a node with well-formed API requests
- DDoS a node with malformed API requests
- Send a very large payload e.g. an invalid transaction with many outputs

Please feel free to suggest more features.

Part of #1227

**Comment by Geod24** [comment]
This is too broad an issue to be tackled, so closing as INVALID. Fuzz testing would likely come with #203 or something related.

**Comment by ferencdg** [comment]
There is a very good summary of what bitcoin client nodes are doing to prevent/mitigate DDOS:
https://en.bitcoin.it/wiki/Weaknesses#Denial_of_Service_.28DoS.29_attacks

Seems like a big piece of work.
