### ISSUE TITLE
Spurious failure in Byzantine test

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1290]
> core.exception.AssertError@source/agora/test/Byzantine.d(318): The block should have been confirmed! Perhaps the delay needs to be increased

Seeing this more in the test-suite. I think that might come from the change to the default timeout @hewison-chris ?

**Comment by hewison-chris** [comment]
Created [PR1295](https://github.com/bpfkorea/agora/pull/1295) to address this

**Comment by hewison-chris** [comment]
Has anyone seen this error in CI recently? Perhaps we can close it now. I doubled the wait for first envelope in the test.

**Comment by Geod24** [comment]
Fixed by #1295 indeed.
