### ISSUE TITLE
registry_address` from `TestConf` is not used

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1294]
https://github.com/bpfkorea/agora/pull/1293#r513308839_

It's set to a default in `TestConf`, but in the `ValidatorConfig` it's set to an empty string.

**Comment by kchulj** [comment]
Would this solve it?

```diff
--- a/source/agora/test/Base.d
+++ b/source/agora/test/Base.d
@@ -1591,13 +1591,14 @@ public APIManager makeTestNetwork (APIManager : TestAPIManager = TestAPIManager)
     }

     Config makeValidatorConfig (size_t idx, KeyPair key_pair,
-        Address self_address, Address[] addresses)
+        Address self_address, Address[] addresses,
+        Address registry_address = test_conf.registry_address)
     {
         Config conf =
         {
             banman : ban_conf,
             node : makeNodeConfig(self_address),
-            validator : ValidatorConfig(true, key_pair, [self_address]),
+            validator : ValidatorConfig(true, key_pair, [self_address], registry_address),
             network : makeNetworkConfig(idx, addresses),
         };
```

**Comment by AndrejMitrovic** [comment]
Yes it would. However there is a bigger problem here. The registry address was null, and yet the tests still passed? That means there are no tests for the registry address (or they don't run properly).

**Comment by ferencdg** [comment]
> Yes it would. However there is a bigger problem here. The registry address was null, and yet the tests still passed? That means there are no tests for the registry address (or they don't run properly).

checked the code and the network tests doesn't need the address
```D
    public override RemoteAPI!NameRegistryAPI getNameRegistryClient (Address address, Duration timeout)
    {
        auto tid = this.registry.locate("name.registry");
        if (tid != typeof(tid).init)
            return new RemoteAPI!NameRegistryAPI(tid, timeout);
        assert(0, "Trying to access name registry at address '" ~ address ~
               "' without first creating it");
    }
```

we currently don't have docker based tests where that address might be useful
let me know if I misunderstood something

**Comment by Geod24** [comment]
Maybe a better issue would have been to just use the network registry in the LocalRest tests.
This however requires #1263 to be fixed AFAIK.

**Comment by ferencdg** [comment]
> Maybe a better issue would have been to just use the network registry in the LocalRest tests.
> This however requires #1263 to be fixed AFAIK.

We do have a LocalRest test for NameRegistry: agora.test.NameRegistry

If there are no objections, I would suggest closing this issue.
