### ISSUE TITLE
Enrollments are susceptible to replay attacks

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1297]
Currently the Enrollment consists of:

```
Hash utxo_key;
Hash random_seed;
uint cycle_length;
Signature enroll_sig;
```

A Validator may re-enroll with the same UTXO key as a previous Enrollment. But that also means they can re-use their signature. In other words, they could just re-send the exact same Enrollment as before, and it would be accepted under current protocol rules.

This presents a problem: An attacker could take a previous Enrollment belonging to a Validator (perhaps a Validator that has un-enrolled long ago) and gossip it. There is a big risk to this: if an attacker collects enough Enrollments for a set of un-enrolled Validators which still have those UTXOs frozen, the attacker could cause a quorum shuffle where most of the newly created quorum network is offline. Therefore we lose liveness. And if we have any slashing rules for inactive validators then we risk punishing innocent users.

As discussed with @Geod24 there are a few ways of fixing this:

- Check that the `random_seed` is different from the previous enrollment. But this requires keeping this state in memory for as long as the frozen UTXO exists (which could be arbitrarily long).
- Add a `max_block_height` to the Enrollment. When a node submits an Enrollment we can check if `block_height + enroll.cycle_length < enroll.max_block_height`, and then only accept the enrollment into a block if this condition is satisfied. This would also mean that if the Enrollment was rejected the node would have to create a new Enrollment with a new `max_block_height`.

There might be many more ways of fixing this. It would be good to research and come up with an optimal solution.

**Comment by omerfirmak** [comment]
I might be wrong but, unless the `max_block_height` is strictly equal to `block_height + enroll.cycle_length + 1`, the attack could still be possible, right?

**Comment by AndrejMitrovic** [comment]
Yes, it's not a good solution after all.

If the current block height is 0, and you create an enrollment with `max_block_height = 10 + cycle_length`, it will mean your enrollment can be accepted within the next 10 block heights. But it also means if your enrollment is accepted at height 1 someone could also re-enroll you at height 9, so it's still a problem.

**Comment by AndrejMitrovic** [comment]
> If the current block height is 0, and you create an enrollment with max_block_height = 10 + cycle_length, it will mean your enrollment can be accepted within the next 10 block heights. But it also means if your enrollment is accepted at height 1 someone could also re-enroll you at height 9, so it's still a problem.

Ah actually my math was wrong here. It can be re-enrolled for all the blocks until that height. So yeah this solution doesn't fly. We have to think of something else.

**Comment by omerfirmak** [comment]
Maybe having a `valid_until` field would be better? Instead of both `cycle_length` and `max_block_height`. Enrollment will be valid until `valid_until`th block regardless. So depending on the which block your enrollment is added to the chain, your cycle length would change.

**Comment by AndrejMitrovic** [comment]
That could work. Except that `cycle_length` is implicitly hardcoded to `1008` blocks. I'm not sure what the consensus is on this right now. cc @Geod24.

**Comment by Geod24** [comment]
Well, one thing which would be fool-proof would be to have `index` be an ever-increasing value. We still need to lookup old enrollments though, but just one, not all of them.

Another approach we discussed with @AndrejMitrovic would be to state that a new `Enrollment`  must be a pre-image of the last revealed pre-image. It would follow what we currently do, and help simplify the code. It would have the same requirement as an `index` without the space overhead, and allow applications built on top of the chain (e.g. Votera) to rely on this. One running out of pre-images would simply have to change their UTXO, but since it's something that will happen after years, if not decades, I think that's okay.

Opinions ?

**Comment by hewison-chris** [comment]
> Well, one thing which would be fool-proof would be to have `index` be an ever-increasing value. We still need to lookup old enrollments though, but just one, not all of them.
> 
> Another approach we discussed with @AndrejMitrovic would be to state that a new `Enrollment` must be a pre-image of the last revealed pre-image. It would follow what we currently do, and help simplify the code. It would have the same requirement as an `index` without the space overhead, and allow applications built on top of the chain (e.g. Votera) to rely on this. One running out of pre-images would simply have to change their UTXO, but since it's something that will happen after years, if not decades, I think that's okay.
> 
> Opinions ?

I think this last approach of enforcing the new enrollment to be a pre-image of the last revealed pre-image might be a good way to tackle this issue.

**Comment by AndrejMitrovic** [comment]
> Another approach we discussed with @AndrejMitrovic would be to state that a new Enrollment must be a pre-image of the last revealed pre-image.

Yes I forgot to even mention this in my comment. It could work.

**Comment by AndrejMitrovic** [comment]
> Another approach we discussed with @AndrejMitrovic would be to state that a new Enrollment must be a pre-image of the last revealed pre-image.

I have an even better idea, I just discussed it with @hewison-chris who had the same idea. It should not be just the preimage of the last revealed preimage, but also +N blocks where that validator was not enrolled. This would help solve the gaps in enrollments and would make it trivial to validate old blocks.

For example, if we had these blocks:

```
[enr1] [pre1] [pre2] [ ] [ ] [ ] [ ] [enr2] [pre3] [pre4] [ ] [ ] [ ] [ ]
```

In the original suggestion we wanted `enr2` to be the preimage of  `pre2`. But this can leave gaps, making it hard to send just the last known preimage for a given utxo for validation of historic blocks. Instead we can make the rule that `enr3` must contain the preimage of the previous block height.

In the above example, the preimage at `enr2` would be hashed 4 times to reach `pre2`, rather than just being hashed one time. 

This way gaps are easily resolved for any one given UTXO. We just need to keep the last known preimage of a validator and the last known enrollment. Then it becomes trivial to calculate the preimage for any historic block height when new nodes download historic blocks and validate them.

**Comment by linked0** [comment]
> In the original suggestion we wanted enr2 to be the preimage of pre2. But this can leave gaps, making it hard to send just the last known preimage for a given utxo for validation of historic blocks. Instead we can make the rule that enr3 must contain the preimage of the previous block height.

I agree with your suggestion. It seems very similar to my original work for managing preimages, which was that all the height for a UTXO has its own preimage. There's one different thing that the first pre-image of a UTXO appears in the time when the first enrollment is created in the current implementation of preimages.

**Comment by omerfirmak** [comment]
> Enrollment must be a pre-image of the last revealed pre-image.

> enr3 must contain the preimage of the previous block height

I feel like these pack so much information for me to understand with the minimal background knowledge I have :) So let me briefly explain my position, so someone can help me out and point out stuff I got wrong.

 So, a Validator picks a random secret and hashes it `n` times, then starts revealing from the `n`th hash and periodically continues revealing earlier hashes until it reaches the random secret. This is what we call a `PreImage` in `agora`.

The 2 quotes above mean different things to me. First one , to me, suggests that `Enrollment` should be included in the hashing process, while generating the preimages. With the second one I understand that `Enrollment`s should include the preimage that corresponds to the height that `Enrollment` is being proposed on, essentially revealing a new preimage.

Hopefully I dont have it all wrong :)

**Comment by AndrejMitrovic** [comment]
The `Enrollment` struct itself is not involved in any hashing. It just marks the commitment to the blockchain. You commit to some value and promise to reveal its next X preimages. So you could have a million hashes of a value and gradually release the preimages (from the last hash back to the original value, or half way there, etc..).

Currently each enrollment (and re-enrollment) can have any commitment in it. We want to change this so it's more easy to derive the preimage for any past block height. Let's give a contrived example where the hash function is `h(value) => value + 1`

```
[commitment: 20] <- [19] <- [18] <- [17]
```

Currently a single node can re-enroll at many points in the blockchain with various different commitments. For example:

```
height: 10:  [commitment: 15] <- [14] <- [13] <- [12]
height: 500:  [commitment: 99] <- [98] <- [97] <- [96]
```

Now the original proposal was to change this so any future re-enrollment must follow the previous one. Continuing from the previous example:

```
height: 10:  [commitment: 100] <- [99] <- [98] <- [97]
height: 500:  [commitment: 96] <- [95] <- [94]
height: 1234:  [commitment: 93] <- [92] <- [91] <- [90] <- [89]
```

See how in this rule the nodes must continue where they left off? Obviously they would have to generate a lot of hashes in order to be able to derive many preimages, but this is a fairly inexpensive process. There's an optimized module for this here: https://github.com/bpfkorea/agora/blob/v0.x.x/source/agora/consensus/PreImage.d

Now, my newest suggestion is to actually take the block height into account. As an example:

```
height: 0:  [commitment: 100] <- [99] <- [98] <- [97] <- [96] <- [95] (last height 5)
height: 15:  [commitment: 85] <- [84] <- [83] <- [82] <- [81] <- [80] (last height 20)
height: 50:  [commitment: 50] <- [49] <- [48] <- [47] <- [46]
```

With this scheme all we really need to know is the very last known revealed preimage of a validator (for a given UTXO that's enrolled). So that would be `46` with which you can easily derive the preimage at height `11` by just hashing it N times, where N is `current height - target_height`.

I hope that made sense. I'm writing this late and my numbers might be off.

**Comment by AndrejMitrovic** [comment]
Edit: I fixed one of the heights in the last paragraph.

**Comment by omerfirmak** [comment]
> I hope that made sense. I'm writing this late and my numbers might be off.

Thanks a lot, appreciate it. Now it makes perfect sense :)

**Comment by Geod24** [comment]
> It should not be just the preimage of the last revealed preimage, but also +N blocks where that validator was not enrolled.

Well we tried that originally, the problem is, what happens if the Enrollment is not included immediately ?

**Comment by AndrejMitrovic** [comment]
If I understand you correctly, if it's not included then it won't be valid for any of the the next block heights as the `random_seed` won't match for that new block height, so they'd have to create a new enrollment.

**Comment by omerfirmak** [comment]
>  so they'd have to create a new enrollment.

IIRC, the re-enrollment mechanism we implemented should already take care of that part.

**Comment by AndrejMitrovic** [comment]
> IIRC, the re-enrollment mechanism we implemented should already take care of that part.

Yes but that just re-enrolls, we would need to create a new enrollment if it was not included in the target height.

**Comment by omerfirmak** [comment]
> > IIRC, the re-enrollment mechanism we implemented should already take care of that part.
> 
> Yes but that just re-enrolls, we would need to create a new enrollment if it was not included in the target height.

It already should, since we check if the Validator is enrolled after every block is created. It would try to enroll if the enrollment is about to expire or if it is not enrolled at all.

**Comment by AndrejMitrovic** [comment]
Yes that's good! We would just need to change `createEnrollment` so it follows the suggested rule.
