### ISSUE TITLE
Possible issues with current `Signature`

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1311]
With the current `Signature` type, I see two main caveats:
- The signature **actually includes the public key**, so it's 32 bytes bigger than it could be;
- The first byte is always 0;

Recording this if anyone wants to eventually pick it up.

**Comment by AndrejMitrovic** [comment]
> The signature actually includes the public key, so it's 32 bytes bigger than it could be;

It includes the `R`, not the public key.

That is why I made this commit before: https://github.com/bpfkorea/agora/pull/1188/commits/c0cee1b9f3593d84797b8ae2f29c92a7fd7804b2

**Comment by Geod24** [comment]
Fixed by @hewison-chris when he revamped that Schnorr signature handling.
