### ISSUE TITLE
Take advantage of d lang scoped imports

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#1317]
Currently we have far too many imports at file and global level (more so in the unit test code). In d it is possible to use scoped imports which can bring many benefits including self dependency management of a block of code. I think it can also help reduce executable size and help with compilation speed.

**Comment by Geod24** [comment]
This is a bit too wide ranging, and it's an "issue" that will crop back as development proceed. We regularly clean up the code, so marking this as WONTFIX.
