### ISSUE TITLE
[Upstream] Fix DUB issue 2012: Nested dub invocation behaves randomly

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1323]
Link: https://github.com/dlang/dub/issues/2012

To do:
- Make sure nested `DUB` invocations use the provided compiler by default. Add documentation to `code.dlang.org` (repository here: https://github.com/dlang/dub-registry) explaining the behavior.
- Make sure the `dub` does not pick up the wrong `dub.selections.json`;
- Do not propagate any DFLAGS unless passed explicitly (`$DUB $DFLAGS`);

**Comment by omerfirmak** [comment]
PR for Issue 1: https://github.com/dlang/dub/pull/2047

**Comment by omerfirmak** [comment]
PR#2: https://github.com/dlang/dub/pull/2048

**Comment by omerfirmak** [comment]
What is the problem with `dub.selections.json` exactly? When I test with projects, not single file operation, dub seems to use the local `dub.selections.json` of each project. Is there a specific case with the single file mode?

**Comment by Geod24** [comment]
Oh the original message had a typo: I meant `dub.settings.json` (`dub` picks up the parent `dub.settings.json`). But this last bug does not actually block us, so this issue is done, thanks for your work!
