### ISSUE TITLE
[Upstream] DUB: Automatically exclude `mainSourceFile` from other configurations

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1324]
One of the main pain-point with `dub` at the moment is the need to duplicate the exclude list for `mainSourceFile`.
We have those:
https://github.com/bpfkorea/agora/blob/7a7a5b186443de3b2bc676ff08247f67bdb98551/dub.json#L84
https://github.com/bpfkorea/agora/blob/7a7a5b186443de3b2bc676ff08247f67bdb98551/dub.json#L90
https://github.com/bpfkorea/agora/blob/7a7a5b186443de3b2bc676ff08247f67bdb98551/dub.json#L118

Etc... This doesn't make sense, and we should make a PR so that `dub` excludes `mainSourceFiles` from unused configuration by default. If one wish for those to be included, it should be done by including them automatically using `sourceFiles`.

**Comment by omerfirmak** [comment]
Upstream PR: https://github.com/dlang/dub/pull/2039
