### ISSUE TITLE
[Upstream] DUB: Make `excludedSourceFiles` recursive

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1325]
`excludedSourceFiles` uses globbing, but that doesn't work quite well, as subpackages are not included by default.
Example:
https://github.com/bpfkorea/agora/blob/7a7a5b186443de3b2bc676ff08247f67bdb98551/dub.json#L109-L111

This is just stupid, as it's very unlikely (and frankly, bad practice) that one would want to exclude a package but not its sub-packages. So I suggest that we allow `excludedSourcePaths` to be recursive iff the path ends with a trailing slash, e.g. in the example above we would use `source/agora/cli/`.

**Comment by omerfirmak** [comment]
Why dont we simply `source/agora/cli/*` wouldnt that work?

**Comment by Geod24** [comment]
Well that's the point :D
`source/agora/cli/*` will *NOT* excludes files in subdirectories, only source files in `source/agora/cli/`. Give it a shot.

**Comment by omerfirmak** [comment]
`BuildSettings.removePaths(["path1", "root/path1", "root/path2/test.d", "root2/path1"], ["root/*"]);` outputs `["path1", "root2/path1"]`. I will try it in dub.json as well.

**Comment by omerfirmak** [comment]
File tree:

- source
   - app.d
   - folder1
       - test.d
       - failfolder
           - fail.d

fail.d containts a compile error.
with `"excludedSourceFiles": ["source/folder1/*"]`, project compiles successfully. Am I missing something here?

**Comment by omerfirmak** [comment]
`std.path.globMatch` might have fixed its own end.

**Comment by Geod24** [comment]
If it works nowadays, could you raise a PR against `dub.json` then ?

**Comment by Geod24** [comment]
And perhaps take a look at older dub. Using the install script, you can do `~/dlang/install.sh dub-1.20.0` and then use `~/dlang/dub-1.20.0/bin/dub` to compile, and test if we need to require a minimum version of `dub`.

**Comment by omerfirmak** [comment]
> https://github.com/bpfkorea/agora/blob/7a7a5b186443de3b2bc676ff08247f67bdb98551/dub.json#L109-L111
> 
> This is just stupid, as it's very unlikely (and frankly, bad practice) that one would want to exclude a package but not its sub-packages. So I suggest that we allow `excludedSourcePaths` to be recursive iff the path ends with a trailing slash, e.g. in the example above we would use `source/agora/cli/`.

If I am not mistaken, those usages are correct. They always exclude 3 subdirectories, leaving 1 subdirectory included.

**Comment by Geod24** [comment]
Indeed. I did some tests locally and all looks good. Either I misremember, or was confused because of the non-exclusion of other config's `mainSourceFile`. In any case, thanks for checking, we can close this!
