### ISSUE TITLE
[Upstream] DUB: Fix issue 1913: sourcePath does not behave as documented

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1326]
See https://github.com/dlang/dub/issues/1913

TODO: Make the configuration's `sourcePaths` behaves normally in the absence of top-level `sourcePaths`.

**Comment by omerfirmak** [comment]
Upstream PR: https://github.com/dlang/dub/pull/2041

**Comment by Geod24** [comment]
Folded into #561
