### ISSUE TITLE
Simple test fails with `expectBlock` when adding second set of transactions

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1336]
```diff
diff --git a/source/agora/test/Simple.d b/source/agora/test/Simple.d
index 8d88f8d7b..d77c01104 100644
--- a/source/agora/test/Simple.d
+++ b/source/agora/test/Simple.d
@@ -41,4 +41,8 @@ unittest
     auto txes = genesisSpendable().map!(txb => txb.sign()).array();
     txes.each!(tx => node_1.putTransaction(tx));
     network.expectBlock(Height(1));
+
+    txes = txes.map!(tx => TxBuilder(tx).sign(TxType.Payment)).array();
+    txes.each!(tx => node_1.putTransaction(tx));
+    network.expectBlock(Height(2));
 }
```

```
dtest=agora.test.simple dub test
```

This fails with exceptions about missing preimages. It seems that some overloads of `expectBlock` call `waitForPreimages`, while others do not.

**Comment by AndrejMitrovic** [comment]
Workaround:

```D
network.expectBlock(Height(2), network.blocks[0].header);
```

Also, I would not be surprised if this is the cause of the CI failures. The existing call in master for `network.expectBlock(Height(1));` can also fail based on timing.

**Comment by linked0** [comment]
I think `network.expectBlock(Height(1));` never fails because an enrollment already has a commitment which is used for a distance of 0 which is for a height of 1 like this case.

**Comment by AndrejMitrovic** [comment]
You're right. Then it's only a problem with all the future heights.

**Comment by linked0** [comment]
I think only the function having the block header as a parameter should remain. Please use the workaround first. I will take this issue later and I will remove the unnecessary function.

**Comment by AndrejMitrovic** [comment]
In the meantime the simple test was change to use `generateBlocks(Height)`, so it's fine now.
