### ISSUE TITLE
We should have a different prefix for addresses used for testing and live networks

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#1354]
Perhaps we should adopt a scheme like all addresses used when running in test mode have prefix T.
Maybe we could generate vanity addresses for our tests to use:-
TV1, TV2... for test validator nodes 
TF1, TF2... for test full nodes
TC for commons budget address
TG for Genesis (Foundation address)

Bitcoin addresses for example:- https://en.bitcoin.it/wiki/List_of_address_prefixes

**Comment by Geod24** [comment]
This is still to be done despite #2008
