### ISSUE TITLE
The number of transaction per block should not be hardcoded to 8.

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#1356]
Originally blocks were created every 8 transactions. Now blocks are created based on a time interval configured in the ConsensusParams. However in the code there is also a check that there are exactly 8 transactions before nominating a new block. This check should be removed and as long as there is at least one transaction nomination should proceed at the block time interval. 
We may want to set an upper limit to the number of transactions in a block but this can be added later.

**Comment by AndrejMitrovic** [comment]
Yep. It was a stop-gap measure while changing the algorithm to nominate based on time.

How many transactions you can include in a block depend on many things, including the max block size (not defined yet), and #407.

So I wouldn't call this issue "easy".

**Comment by hewison-chris** [comment]
It is easy to do the first step of not having a restriction on the number of transactions in a block (other than having at least one). This Issue is to just remove the limitation of having to have 8 per block.

**Comment by TrustHenry** [comment]
That's right. That's what we want.
It's a difficult problem because we don't have a miner.

If this does not limit the number of transactions,
On what basis do each node select transactions and create blocks?

**Comment by AndrejMitrovic** [comment]
> It is easy to do the first step of not having a restriction on the number of transactions in a block (other than having at least one). This Issue is to just remove the limitation of having to have 8 per block.

Sure. I was just thinking about long-term

**Comment by AndrejMitrovic** [comment]
> If this does not limit the number of transactions, On what basis do each node select transactions and create blocks?

That's what #407 is for. Someone needs to take that issue at some point.

**Comment by hewison-chris** [comment]
> That's right. That's what we want.
> It's a difficult problem because we don't have a miner.
> 
> If this does not limit the number of transactions,
> On what basis do each node select transactions and create blocks?

A block should be externalised at a regular time interval defined by `block_interval_sec` in `ConsensusParams`.

**Comment by TrustHenry** [comment]
> > That's right. That's what we want.
> > It's a difficult problem because we don't have a miner.
> > If this does not limit the number of transactions,
> > On what basis do each node select transactions and create blocks?
> 
> A block should be externalised at a regular time interval defined by `block_interval_sec` in `ConsensusParams`.

I think that's the most ideal.
However, the number of transactions received per node may be different and time differences may occur.
And each node may have a different distribution of accepted transactions.
The process of building blocks by consensus can take a long time.

**Comment by hewison-chris** [comment]
I think this first step of removing the hardcoded 8 transactions per block will make our life easier for testing our system and writing tools to generate data.
