### ISSUE TITLE
Agora accepts genesis blocks with no enrollments

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1361]
Originally found in: https://github.com/bpfkorea/infrastructure/issues/89 (private)

We accidentally deployed an old config to our server, which meant the `testing` field in the `Config` was set to `false`:

https://github.com/bpfkorea/agora/blob/c0f000595de29fbe8ce837f7e0eb8a88e3d10c10/source/agora/common/Config.d#L115

When faucet was deployed, the nodes accepted the transactions. That's because currently, CoinNet and TestNet have the exact same genesis funding transactions:

https://github.com/bpfkorea/agora/blob/c0f000595de29fbe8ce837f7e0eb8a88e3d10c10/source/agora/consensus/data/genesis/Test.d#L135-L145

and:

https://github.com/bpfkorea/agora/blob/c0f000595de29fbe8ce837f7e0eb8a88e3d10c10/source/agora/consensus/data/genesis/Coinnet.d#L52

**However**, the CoinNet genesis block doesn't have **any** enrollments.

So the question is, why did the nodes load the CoinNet genesis block and accepted it, even though it has no enrollments in it? This is the reason:

https://github.com/bpfkorea/agora/blob/c0f000595de29fbe8ce837f7e0eb8a88e3d10c10/source/agora/consensus/validation/Block.d#L218-L220

In fact I made a comment about it when the PR was made:

https://github.com/bpfkorea/agora/pull/884#discussion_r437218299

**Comment by TrustHenry** [comment]
I remember, #884 merged first.
It should have been activated at #875.

**Comment by AndrejMitrovic** [comment]
Could you submit a PR with a fix? That would be great.

**Comment by TrustHenry** [comment]
Why not.

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/agora/blob/dc1ee7af924eddc6da59f978234dedcbe17eb346/source/agora/consensus/data/genesis/Coinnet.d#L24-L34
To solve this issue, we need the following.
- freezing transaction of Genesis block
- Enrollment of Genesis block

We are using a test Genesis block for testing, but this is a Coinnet.
**The first block start policy is required.**

**Comment by TrustHenry** [comment]
We are validating the Coinnet Genesis block in a unit test.
It is necessary to adjust the amount of existing payment transactions in order to create temporary freeze transactions and include an enrollment.
During the confirmation process, our white paper confirmed that the initial issuance of Genesis Block was 450 million.
I will create an issue related to this separately.
But it can be related to the issue.
https://github.com/bpfkorea/agora/issues/1411
