### ISSUE TITLE
Agora sometimes emits a socket error

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1362]
```
Nov 13 08:06:13 eu-002 docker[14457]: sock error 104!
```

It seems to originate from here: 

https://github.com/vibe-d/eventcore/blob/a462db4e04ea4c2f4f227dbf5fc74c605e469340/source/eventcore/drivers/posix/sockets.d#L412

I'm not sure why it's using the `print` function in https://github.com/vibe-d/eventcore/blob/a462db4e04ea4c2f4f227dbf5fc74c605e469340/source/eventcore/internal/utils.d#L8, is this supposed to be a non-recoverable error?

**Comment by kchulj** [comment]
Update: This error is spurious and not reproducible.

**Comment by kchulj** [comment]
Any thoughts on this issue?

**Comment by AndrejMitrovic** [comment]
Does it still happen or not?

**Comment by kchulj** [comment]
It does, but happens at random times and the error # is various.

**Comment by AndrejMitrovic** [comment]
If it's not blocking anything you can unassign from this issue. But we should keep it open until it can be resolved by someone who can tackle this.

**Comment by ferencdg** [comment]
does this happen in the rest client or server?

**Comment by ferencdg** [comment]
I wonder if this 104 error is just a sideeffect of some agora instances crashing and the client side would still try to read from the (unproperly closed) socket. Did any crash happen around the time when this error message appeared? Also I saw the same problem WITHOUT using docker and just using faucet, it would probably be better to run it outside of docker for the test.

I also checked that after fixing this: vibe-d/vibe.d#2506 (which regularly crashed agora server), I stopped seing this 104 issue.

Also this ticket also talking about crashing and seeing this 104 error: vibe-d/vibe.d#1714

**Comment by AndrejMitrovic** [comment]
> I wonder if this 104 error is just a sideeffect of some agora instances crashing and the client side would still try to read from the (unproperly closed) socket. 

Yes I think this might be the reason. I remember other nodes crashing at the time.

> I also checked that after fixing this: vibe-d/vibe.d#2506 (which regularly crashed agora server), I stopped seing this 104 issue.

Perfect. Then let's just update Agora with the latest vibe.d submodule and close the issue. Thank you for fixing this!

**Comment by ferencdg** [comment]
+ @omerfirmak

**Comment by ferencdg** [comment]
thx @omerfirmak for solving the original #2506 issue together

**Comment by omerfirmak** [comment]
> thx @omerfirmak for solving the original #2506 issue together

It was a pleasure :)

**Comment by omerfirmak** [comment]
After integrating https://github.com/vibe-d/vibe.d/issues/2506, we might want to increase our timeout duration as well. To minimize the overhead of dropping connections.

**Comment by AndrejMitrovic** [comment]
Is there anything else that needs to be updated other than vibe.d & vibe-core? I'm getting errors:

> submodules/vibe.d/data/vibe/data/serialization.d(487,8): Error: no property formattedWrite for type std.array.Appender!string

**Comment by omerfirmak** [comment]
It was building fine with only `v0.9.2` + the fix we proposed. We are on `master` now, vibe.d `master` might be broken.

**Comment by omerfirmak** [comment]
https://github.com/vibe-d/vibe.d/blame/e350f3221c477fb7a3c9a1a209b305894d8786aa/data/vibe/data/serialization.d#L487
Weirdly, it is missing a `import std.format : formattedWrite;`
I will open a PR for it.

**Comment by ferencdg** [comment]
might also be worth adding a unit test that specifically triggers compilation of that branch
we already have a unit tests that triggers this branch I think: 
https://github.com/vibe-d/vibe.d/blame/e350f3221c477fb7a3c9a1a209b305894d8786aa/data/vibe/data/serialization.d#L484

**Comment by ferencdg** [comment]
> Is there anything else that needs to be updated other than vibe.d & vibe-core? I'm getting errors:
> 
> > submodules/vibe.d/data/vibe/data/serialization.d(487,8): Error: no property formattedWrite for type std.array.Appender!string

should be fixed by adding the import as @omerfirmak suggested
https://github.com/vibe-d/vibe.d/pull/2510
added some extra tests too

**Comment by kchulj** [comment]
`sock error 54!` is often emitted in a local environment with latest versions of agora and stoa. It happens in the beginning.

**Comment by kchulj** [comment]
Do we still see this?

**Comment by ferencdg** [comment]
agora crashing?
https://github.com/bosagora/agora/issues/1362#issuecomment-741802077

**Comment by Geod24** [comment]
Not seen for a while, closing.

**Comment by ferencdg** [comment]
talked about this with Ku, and it only happens during restart(when some agora nodes stops/some still do requests even though all instances were instructed to stop by ansible), so this is similar to the case when agora instances crashing
