### ISSUE TITLE
Logging the node short hash isn't as useful as it could be 

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1363]
e.g.:

```
Nov 13 08:06:52 eu-002 docker[14457]: 2020-11-13 08:06:52,28 
Info [agora.consensus.protocol.Nominator] - Rejected invalid envelope: 
{ statement: { node: GDNO...LVHQ, slotIndex:...
```

Node that `GDNO...` in this case is actually `GDNODE2...`, but we can't easily tell that because it's shortened in the output. We can still identify the nodes by their ending `...LVHQ`, but it's not debugging-friendly.

**Comment by hewison-chris** [comment]
Maybe we should consider generating new vanity addresses with TV1, TV2 ...(Test validators), TF1, TF2 ... (Test fullnodes)
This is something also mentioned in [Issue 1354](https://github.com/bpfkorea/agora/issues/1354)

**Comment by AndrejMitrovic** [comment]
Yes that sounds good to me!

**Comment by linked0** [comment]
Two issues could be merged into one issue, I think. The main thing is that the nodes on a log should be identified clearer.

**Comment by Geod24** [comment]
Or we just show the first 8 chars instead of first 4 and last 4 ? The choice I made was arbitrary and based on Stellar, but it doesn't make much difference for us.
