### ISSUE TITLE
Execution engine: Lock scripts should be syntactically checked (+ conditional opcodes checks)

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1380]
While writing the networking tests I've realized the lock scripts' conditionals are only checked once they're executed together with the unlock scripts. But that presents a danger of allowing badly formed lock scripts into the blockchain. Someone could have their funds locked forever due to a bad script such as:

```
IF
    ...
ELSE
   ...
// missing END_IF
```

The above only becomes an error once the unlock script is presented. We need to syntactically validate new lock scripts in the `lock + unlock => [new lock]` scenario and not just `lock + unlock` combos.

**Comment by AndrejMitrovic** [comment]
There is one problematic case. If we also validate that the Key in the lock script is correct (the `Point.isValid()` check), then this will disallow sending funds to a burn address where the address is defined as being `Point.init`.

Is there any other address we can use for burning purposes? Or should we avoid doing curve validation of a point for a lock script until its spent (in other words, when the lock+unlock are executed together)?

**Comment by Geod24** [comment]
> Is there any other address we can use for burning purposes?

Any address that has a pattern so predictable it cannot be the result of a random process will do. `0x0000000000000000000000000000000000000000000000000000000000000001` could be the burn address, and so could `0x02A2A2A2A2A...` or some `0x0DEADBEEF`.

**Comment by ferencdg** [comment]
special opcode like OP_RETURN?
https://en.bitcoin.it/wiki/OP_RETURN

**Comment by AndrejMitrovic** [comment]
@ferencdg you're right, good idea.
