### ISSUE TITLE
Nominator is not guaranteed to nominate anything for slot X causing Byzantine test failure

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1431]
if a 
nominator is NOT the round leader for slot X AND 
nominator already has ALL the transaction gossiped to him for slot X AND
haven't received any nominations envelopes from any leaders for slot X yet, 
then after its nomination timer kicks in for SLOT X it might never nominate ANYTHING for slotX, even if he later recives envelopes from round leaders

look at Validator 2:
https://gist.github.com/ferencdg/3a3bc5de7305e65d7253e656f743ddb2
1. received all transactions
2. nomination timer kicks in
3. no envelop is emitted due to not being round leader and not receiving any nomination envelopes yet
4. later it will not renominate a correct envelope
5. validator 2 will end up nominating/re-nominating nothing for this round 

I looked at the code and this is how SCP is implemented, not neccessarily a bug

However our Byzantine tests fail because of this.... we excpect all validators to nominate at least one envelop

**Comment by ferencdg** [comment]
thinking more about it, I think the real issue is in Agora... if the sequence I described above happens to 5 out of the 6 nodes in the quorum, then there will be only 1 node(the leader) voting for the entire round and 1 vote will not trigger re-nomination in any of those 5 nodes... And we will stuck forever... In the SCP implementation in the 'nominate' function there is a call to the 'updateRoundLeaders' method I think that would change the round leader for slotX so we would not be stuck forever... I think we are supposed to call this 'nominate' function in SCP periodically/multiple times from Agora, but currently we call it once per slot

I just checked and it seems 'updateRoundLeaders' would only update leaders if QuorumSet changes, please let me know if I am wrong.

**Comment by ferencdg** [comment]
even if we call the scp's 'nominate' function multiple times/round it doesn't mean SCP implementation will emit a new envelop for all of those call, it will only emit a new one, if there is any change

**Comment by AndrejMitrovic** [comment]
> I just checked and it seems 'updateRoundLeaders' would only update leaders if QuorumSet changes, please let me know if I am wrong.

The round number (which changes within a single slot based on timer timeouts) change the hashing of the node, which affects the round leaders. See here: https://github.com/bpfkorea/agora/blob/a92aead454b8e93a79ef7c9fccec7f1d4aaacabe/source/scpp/src/scp/NominationProtocol.cpp#L253

So within one slot the round leaders change, it just takes some time. The delay is at first 1 second, then 2, 3, etc..

**Comment by ferencdg** [comment]
> > I just checked and it seems 'updateRoundLeaders' would only update leaders if QuorumSet changes, please let me know if I am wrong.
> 
> The round number (which changes within a single slot based on timer timeouts) change the hashing of the node, which affects the round leaders. See here:
> 
> https://github.com/bpfkorea/agora/blob/a92aead454b8e93a79ef7c9fccec7f1d4aaacabe/source/scpp/src/scp/NominationProtocol.cpp#L253
> 
> So within one slot the round leaders change, it just takes some time. The delay is at first 1 second, then 2, 3, etc..

it is still strange because Validator 2 did receive a good envelope from Validator 4, but Validator 2 didn't re-emit it, even though I suppose Validator 4 was the leader(at least from Validator 4's perspective) and Validator 2 had no candidates at that moment. So it looks like Validator 2 thought 4 was not a leader. I checked and they called the nominate method almost at the same time, so I suppose they aggreed on who are the leaders.

**Comment by ferencdg** [comment]
> > > I just checked and it seems 'updateRoundLeaders' would only update leaders if QuorumSet changes, please let me know if I am wrong.
> > 
> > 
> > The round number (which changes within a single slot based on timer timeouts) change the hashing of the node, which affects the round leaders. See here:
> > https://github.com/bpfkorea/agora/blob/a92aead454b8e93a79ef7c9fccec7f1d4aaacabe/source/scpp/src/scp/NominationProtocol.cpp#L253
> > 
> > So within one slot the round leaders change, it just takes some time. The delay is at first 1 second, then 2, 3, etc..
> 
> it is still strange because Validator 2 did receive a good envelope from Validator 4, but Validator 2 didn't re-emit it, even though I suppose Validator 4 was the leader(at least from Validator 4's perspective) and Validator 2 had no candidates at that moment. So it looks like Validator 2 thought 4 was not a leader. I checked and they called the nominate method almost at the same time, so I suppose they aggreed on who are the leaders.

so it seems different nodes might chose different leaders, and that explains why node 2 didn't re-nominate what it received... The question now is whether having different round leaders is expected or not. From the code it seems expected: each node treats itself preferentially compared to other nodes.

**Comment by ferencdg** [comment]
red herring, the issue was with the Byzantine test and solved by PR 1449
