### ISSUE TITLE
BlockStorage should not include block validation

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#1439]
The problem is now the `BlockStorage` itself has block validation in it. For example comparing the merkle roots. The block storage should just be a plain dumb (optimized) data store, it should not have any validation in it. That belongs elsewhere like in the Ledger for example.

_Originally posted by @AndrejMitrovic in https://github.com/bpfkorea/agora/pull/1398#discussion_r546496373_

**Comment by Geod24** [comment]
Removed in https://github.com/bpfkorea/agora/pull/1671
