### ISSUE TITLE
In a freeze transaction, output corresponding to a refund shall not freeze.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#1440]
Currently, all outputs contained in a freeze transaction are treated as frozen UTXO.
However, the UTOX equivalent of the refund money should not be frozen and can be reused.
If a person wants to freeze only 40,000 BOA in UTXO with 50,000 BOA,
The refund equivalent of 10,000, another output of the same transaction, shall not be frozen.

**Comment by AndrejMitrovic** [comment]
I see the problem. But how would you solve it?

**Comment by MichaelKim20** [comment]
I've thought about a few things, but it's not enough to suggest such a good method.
1. To add a type to a transaction output
2. To set a rule that only the first item of transaction outputs is frozen

I've only thought about these solutions yet.

**Comment by AndrejMitrovic** [comment]
I've had the same thoughts.

The reason why we didn't do `1.` initially, is because it would increase the size of the transactions.

The second rule might work.
