### ISSUE TITLE
Frozen UTXO shall be released by the same address.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#1441]
Currently, there is no rule for the address of the output of the transaction when frozen UTXO is released. As a result, 
frozen UTXO can be released and transferred to another address and locked from that address for a period of time.
The frozen funds are not allowed to be used for a period of time after being released.
However, if the address changes after it are frozen, it may be considered that the payment has already occurred. 
Therefore, even after freezing, the address must be the same as the input of the transaction.

**Comment by AndrejMitrovic** [comment]
> However, if the address changes after it are frozen, it may be considered that the payment has already occurred.

Why would it "be considered"? The UTXO is frozen and can't be spent regardless of the destination address.

**Comment by AndrejMitrovic** [comment]
As far as I see you're talking about the case where someone melts a locked utxo to a different address. So the wallet of the second address would need to detect that it's a melting transaction, therefore it cannot be spent yet.

This is the same as if the user melted the utxo to itself. The wallet would still need to know this UTXO is not spendable until the melting period is over.

So even if you add a protocol rule that utxo can only be melted to the same address, the wallet would still need to be able to detect this melting transaction and make sure that the "balance" shows that melting is not spendable yet.

**Comment by MichaelKim20** [comment]
I had the same thought as @AndrejMitrovic  before I thought of the following case. 
However, when a person purchases an item using frozen UTXO, the person who receives the payment will unfortunately suffer.
This issue is to prevent such mishaps.

**Comment by AndrejMitrovic** [comment]
> the person who receives the payment will unfortunately suffer.

Their wallet should let them know the UTXO is not spendable.

**Comment by MichaelKim20** [comment]
Shouldn't Agora support verification of transactions created without using a wallet?

**Comment by AndrejMitrovic** [comment]
But it already does?

**Comment by Geod24** [comment]
As mentioned by @AndrejMitrovic , the wallet should support this. I was partial to the argument that this could constitute a payment though, but then, one could perform a payment by selling their private key just the same.
