### ISSUE TITLE
Combining candidates should be better implemented

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#1460]
We currently just pick the first candidate in `combineCandidates`

With https://github.com/bpfkorea/agora/issues/407 https://github.com/bpfkorea/agora/issues/993 and https://github.com/bpfkorea/agora/issues/1332 implemented, we should update our transaction pool and create a new candidate from scratch with the mechanism in https://github.com/bpfkorea/agora/issues/407. Since all nodes will receive each others best candidates, we should reach a network wide optimum transaction set.

**Comment by ferencdg** [comment]
I am not sure I understand this correctly, but this ticket might have just been implemented recently/being impelemnted currently

https://github.com/bosagora/agora/issues/2024
This will chose the candidates with
1. least missing validators
2. if point 1 ties, then chose candidate with with highest fees
3. if point 2 ties, then chose candidate with lowest hash

(I am not sure we should come up with a brand new candidate in the combineCandidate function, at least Stellar doesn't do that)

---

Chose double spend transaction with highest(size adjusted) fee from the pool when trying to nominate candidates:
https://github.com/bosagora/agora/pull/1881

was that what you also meant in this ticket?

**Comment by omerfirmak** [comment]
Closing this in favor of #2024. 

This was merely for pointing out the problem, #2024 suggests an actual solution.
