### ISSUE TITLE
An Improvement on JSON serialization of `Lock` and `Unlock`

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#1489]
Lock and Unlock have a member named `bytes`. Its data type is `const(ubyte)[] bytes`
When this is serialized to JSON, the output is as follows:
It is represented by an array of integers as shown below.
How about representing bytes using base64?
If it is possible to use base64, how about using base64 for transaction data payload?

```JSON
{
  "type": 0,
  "inputs": [
    {
      "utxo": "0x4655b3b615a77c2b38649be6007e7c8eb1570ae8a3f2de67768d3afd8d29ad766fa0bd8816a776085f4312ce9ab00c9c37f7909efb776bcad43b253e827a1ef4",
      "unlock": {
        "bytes": [
          128,36,128,122,171,195,62,180,145,15,56,77,95,49,249,199,93,245,171,194,234,148,121,240,238,33,122,206,25,34,198,
          187,76,51,73,215,216,46,248,178,102,92,199,162,224,52,12,23,148,168,254,78,150,51,194,224,151,95,53,55,60,36,52,5
        ]
      },
      "unlock_age": 0
    }
  ],
  "outputs": [
    {
      "value": "610000000000000",
      "lock": {
        "type": 0,
        "bytes": [
          157,2,56,224,161,113,64,11,198,214,138,157,155,49,106,205,81,9,100,145,19,160,92,40,79,66,150,210,179,1,34,245
        ]
      }
    }
  ],
  "payload": "",
  "lock_height": "0"
}
```

**Comment by AndrejMitrovic** [comment]
I need to rebase the `flash-layer` branch against the latest changes in `v0.x.x`. After that I'll add the base64 serialization.

**Comment by AndrejMitrovic** [comment]
I've rebased the branch. I will add base64 serialization soon.

**Comment by AndrejMitrovic** [comment]
@MichaelKim20 actually I think that now with the rebased branch base64 should already work. Can you test it and let me know if it works?

**Comment by ferencdg** [comment]
already merged into the vibe.d repo, here is the usage example
https://github.com/vibe-d/vibe.d/blob/aaff28b0b92b8394980efdb0cb9fd1f7da01daf8/web/vibe/web/rest.d#L195-L207

you can also use Base64ArrayPolicy independently from the REST by passing it to 
```d
serializeWithPolicy!(Serializer, Base64ArrayPolicy)(serializer, value); function
```
