### ISSUE TITLE
Create Flash Layer documentation for Whitepaper

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#1510]
Create Flash Layer documentation that can be added to our existing whitepaper.

**This document must state the following:**
- Why was this added after the release of the original whitepaper
- Purpose of this development
- Impact it will have on the platform and its userbase
- 2-3 possible use cases

**Comment by AndrejMitrovic** [comment]
> Why was this added after the release of the original whitepaper

This I don't really know. I thought a second-layer solution was always planned from the very beginning?

**Comment by Geod24** [comment]
The rationale as to why it's missing in the original WP is fairly simply:
- The original whitepaper was released in late 2016, when second layer solutions were just beginning to be researched, and on-chain scalability was the focus at the time;
- The whitepaper targeted a 5s confirmation time and a throughput of 1k tx/s, however, this would be insufficient by today's standards;

**Comment by AndrejMitrovic** [comment]
I thought we're talking about the whitepaper we published on our website, which was released after the boscoin one.
