### ISSUE TITLE
PreImageCycle implementation is dependant on the NumberOfCycles

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#1516]
Changing `NumberOfCycles`, for example to 25, results in wrong preimages being revealed.

**Comment by omerfirmak** [comment]
False alarm, it's just that the commitments in genesis were generated with 100 cycles.

**Comment by hewison-chris** [comment]
I think this is still an issue as I also saw this problem. The `numberOfCycles` is not the same as `cycle_length` which is what is included in the enrollment.

**Comment by kchulj** [comment]
Isn't the `numberOfCycles` the number the `cycle_length` is multiplied by?

**Comment by hewison-chris** [comment]
> Isn't the `numberOfCycles` the number the `cycle_length` is multiplied by?

Yes, to determine the number of Preimages to generate. I wanted to create a test with a lower `numberOfCycles` but found it was not possible. Perhaps I was mistaken but would like to re-check this is not a problem.

**Comment by hewison-chris** [comment]
Perhaps the `numberOfCycles` should be a consensusParam.

**Comment by hewison-chris** [comment]
Fixed by PR #2068
