### ISSUE TITLE
Flash layer: Determine fee rate algorithm

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1527]
In Lightning the fee is a fixed base fee plus a percentage of the transaction value. Therefore, in Lightning the payment fee increases with payment value.

We should have a similar fee rate in the Flash layer.

**Comment by omerfirmak** [comment]
First we need an update message, similar to the LN

https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-channel_update-message

**Comment by omerfirmak** [comment]
Resolved in #1790
