### ISSUE TITLE
Banning should be an Info, not a Trace call

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1540]
```
2021-01-25 13:47:30,294 Trace [agora.common.BanManager] - 
BanManager: Address http://node-4:4826 banned until 1611636450
```

This info is lost unless `Trace` is enabled in the logs. But banning is important enough to warrant an Info level.

**Comment by Geod24** [comment]
Banning a validator should even be higher.

**Comment by AndrejMitrovic** [comment]
The thing is, it bans a node for failing to connect to it. So this is before even determining the node is a validator or not.
