### ISSUE TITLE
Eliminate unnecessary Enrollment requests during catch up.

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#1546]
If a Validator is N blocks behind the network, it will try to enroll N times during catch up and fail. Validator should not emit unnecessary requests when it knows that will fail for sure.

**Comment by omerfirmak** [comment]
From what I have gathered so far, this situation is a bit hairy.

We currently check if we need to enroll for every accepted block, without checking if it was externalized or downloaded from a peer, and send a request if needed. While catching up we can't rely on any information other than the fact that we just validated a block and added to the chain. There is no way we can be sure that there is an already externalized block for the next height, so that we can skip sending an enrollment request. The heights that other nodes say they are at are not to be trusted, if we rely on that information a bad node can make us never enroll by telling there is always a more recent block.

The best option I can think of is sending an enrollment request after a certain amount of time from the moment we last accepted a new block. If we accept a new block within that period, enrollment request for the previous block will be discarded.

**Comment by Geod24** [comment]
> The heights that other nodes say they are at are not to be trusted, if we rely on that information a bad node can make us never enroll by telling there is always a more recent block.

Correct, but we can rely on the signatures more than just the height. Also, we can know when we're "far" behind (because of the time offset of the newly accepted block).

**Comment by omerfirmak** [comment]
> time offset of the newly accepted block

Completely forgot those existed. I think this is the best solution.
