### ISSUE TITLE
Agora should ensure that validator cycle and "preimage cycle" are consistent

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1548]
The preimage cycle (a.k.a. number of blocks that will belong to the same pre-image "chain") must be evenly divisible by the validator cycle otherwise we'll have a nasty edge case.

**Comment by Geod24** [comment]
In hindsight, I think we should just remove that field from the Enrollment.

**Comment by kchulj** [comment]
> In hindsight, I think we should just remove that field from the Enrollment.

This is the solution that was decided.
