### ISSUE TITLE
Coinbase only TX sets should not validate

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#1601]
Currently there are no rules against network creating blocks consisting of Coinbase TXs only. This is probably not ideal. We should both not create such nominations and invalidate any nominations/blocks that only include Coinbase TXs.

**Comment by TrustHenry** [comment]
When there is no transaction on the Agora network,
If we don't create blocks with Coinbase tx, our block creation latency will increase indefinitely.
The node rewards defined in the white paper will be reduced and the rewards compared to the time we expected will be reduced.

I've seen a blockchain that has no transactions before.

**Comment by omerfirmak** [comment]
If we don't have any new TXs for a while we probably have a bigger issue IMO.

But if we want to allow this, we should probably remove the checks in validation but still not nominate coinbase only values in our reference implementation.
