### ISSUE TITLE
Flash: handle failed payment routing and re-try with a different path

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1623]
This is related to https://github.com/bpfkorea/agora/issues/1528. But I think it can be implemented as two separate features.

Currently when a routing request fails, the sender just attempts to send it again. In fact there is no special ErrorCode for rejecting an HTLC. 

[This page](https://github.com/lnbook/lnbook/blob/develop/path-finding.asciidoc) shows the common LN implementation flow:

> If the payment settles, the sender updates its topological knowledge based on this new information for future payments. The algorithm terminates.
> 
> If the payment fails, the sender updates its topological knowledge based on this new information. It then selects a different path and starts the process again from the beginning.

So we need to have the ability for a hop to reject the HTLC. And the sending node should then forward this failure state back to *its* sender.

That means there can be a situation such as:
- Alice (htlc) => Bob (accepted)
- Bob => Charlie (rejected)

In this case Bob has already notified Alice that it accepted the HTLC via `proposeUpdate()`. So it cannot return an `ErrorCode` anymore when Charlie rejects its HTLC. Instead we should add a new API specifically for cancelling HTLCs, similar to how LN does it.

**Comment by omerfirmak** [comment]
> This is related to #1528. But I think it can be implemented as two separate features.

I would say #1528 depends on this. As the sender has to know which channel failed to avoid it in the next payment attempt.

**Comment by omerfirmak** [comment]
Similar to the LN, we need a mechanism to return error messages to the origin of the payment.

https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#returning-errors
