### ISSUE TITLE
Switch address format from Stellar-style to bech32

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1655]
See https://en.bitcoin.it/wiki/BIP_0173 for details. This probably should be addressed only after #1645 has been addressed.

**Comment by linked0** [comment]
Bech32 Alphabet: `q p z r y 9 x 8 g f 2 t v d w 0 s 3 j n 5 4 k h c e 6 m u a 7 l`
Base32 Alphabet: `A B C D E F G H I J K L M N O P Q R S T U V W X Y X 2 3 4 5 6 7`

We should change all the well-known keys according to the Bech32 alphabet, which means that the `PublicKey` will start with `x` and the `SecretKey` will start with `j`. 

A Bech32 string is at most 90 characters long and consists of:
**The human-readable part**, which is intended to convey the type of data, or anything else that is relevant to the reader. This part MUST contain 1 to 83 US-ASCII characters, with each character having a value in the range [33-126]. HRP validity may be further restricted by specific applications.
**The separator**, which is always "1". In case "1" is allowed inside the human-readable part, the last one in the string is the separator.
**The data part**, which is at least 6 characters long and only consists of alphanumeric characters excluding `1`, `b`, `i`, and `o`.

I'd like to get some information on the `agora.cli.vanity.main` and discuss whether `The human-readable part` is needed for our key types.
