### ISSUE TITLE
Review default values in configuration

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1657]
Currently we have quite a few default values in our config files which are just "here", but are extremely suggestive, such as the ban rules (https://github.com/bpfkorea/agora/blob/4c7f32d9a84a8ea666bdf362f742a5a931ec058c/source/agora/common/BanManager.d#L37-L45), or the timeout (https://github.com/bpfkorea/agora/blob/4c7f32d9a84a8ea666bdf362f742a5a931ec058c/source/agora/common/Config.d#L152-L162). Those should be reviewed and corrected to match the expected CoinNet flow.

**Comment by Geod24** [comment]
Four places to review:
- Infrastructure (TestNet);
- In code (`Config.d`);
- In the example file (`config.yaml`);
- In the system test;

**Comment by linked0** [comment]
Should we review the `data_dir` value?

```
/// Path to the data directory to store metadata and blockchain data
public string data_dir = "/var/lib/agora/";
```

**Comment by Geod24** [comment]
That's a good default for Linux, but not for Windows indeed. Neither for OSX.

**Comment by Geod24** [comment]
Addressed

**Comment by Geod24** [comment]
Where are we on this ?
