### ISSUE TITLE
Remove `createEnrollmentData`, use regular enrollment rules

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1659]
https://github.com/bpfkorea/agora/blob/0b4304b800cfbe373442cf5de17596999e375610/source/agora/test/Base.d#L1300-L1310

This is a unittest special case that needs to be removed to better match the real system.

**Comment by linked0** [comment]
I don't see the purpose of this issue. We can not enroll a node as a validator without the function because there is no API endpoint to trigger a node to enroll. Could you explain what you intend on this issue? Or we could have a whiteboard again. :)
