### ISSUE TITLE
Lock script validation should happen during transaction addition

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1667]
Currently 'executeBasicScripts' validates both the Lock and Unlock scripts, however it might make more sense to validate the Lock script when the transaction is first proposed. This would guard against certain software bugs for example in wallet software that produces invalid scripts. (and as a result all that money would be lost)

**Comment by AndrejMitrovic** [comment]
Yes, it's a known issue: https://github.com/bpfkorea/agora/issues/1380
