### ISSUE TITLE
Store number of enrolled validators in block header validators field

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#1669]
I propose to wrap the `BitField!ubyte` field with a `BlockValidators` struct which includes the number of the validators enrolled that could potentially sign the block. This struct could also provide some useful functions to simplify code. For example a function to count the number of validators that signed or to return the indexes of the validators who signed.
It will also enable safe guarding against accessing the bits beyond the `active` set of bits.

**Comment by ferencdg** [comment]
I think the BitField!ubyte could store(and serialize) the actual number of the elements in the Bitfield(the same number that was passed to the BitField constructor). Currently BitField is only storing its capacity which is less than or equal to the actual number of elements.

**Comment by AndrejMitrovic** [comment]
Wouldn't this come at the cost of increasing the size of the block?

**Comment by hewison-chris** [comment]
> Wouldn't this come at the cost of increasing the size of the block?

Yes probably a couple of bytes extra would be needed. Depends on the maximum number of validators we want to support.

**Comment by ferencdg** [comment]
Yes, it would increase it by 4 or 8 bytes, but if we think our block size will be 10 - 100MB anyways, then this size increase might not be that much, and could really simplify our code.

If we want to really save space for example, then we don't even need to store CB(fee only) transaction on the chain: we could do this, but it would make implementation more difficult.

**Comment by hewison-chris** [comment]
The chosen solution was to create a new `struct` named `BitMask` which has a length value, which is set when constructed, and a byte array with required bytes to have a bit per active validator. When the bit is set then the validator's signature has been added.
