### ISSUE TITLE
using 'shared' variables without synchronization

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1676]
Some of our intermittent test failures might be caused by not using synchronization(locks/atomic operations) while using 'shared' variables for example:

SlashingMisbehavingValidator uses
private shared bool* reveal_preimage;
from multiple threads without any syncronization

Some other affected tests:
Byzantine.d
EnrollmentManager.d

**Comment by linked0** [comment]
In SlashingMisbehavingValidator.d, the pointer @ferencdg mentioned is just a pointer to a `static` variable originally as follows.
```
static class BadAPIManager : TestAPIManager
{
    public static shared bool reveal_preimage = false;
```

Can it cause our intermittent test failures?

**Comment by ferencdg** [comment]
> In SlashingMisbehavingValidator.d, the pointer @ferencdg mentioned is just a pointer to a `static` variable originally as follows.
> 
> ```
> static class BadAPIManager : TestAPIManager
> {
>     public static shared bool reveal_preimage = false;
> ```
> 
> Can it cause our intermittent test failures?

I think it can cause intermittent failures, the following line is executed on the thread the unit test is run:

```D
// all the validators start revealing pre-images
    LazyAPIManager.reveal_preimage = true;
```

while the nodes run on their own threads and might never be able to see that reveal_preimage is set to true: an easy fix would be to use atomic stores and loads of that variable

**Comment by Geod24** [comment]
Hum, I don't think that boolean is the problem, although it should definitely use `atomicOp` and `atomicLoad`.
What concerns me most is the usage of a `shared` UTXO set: https://github.com/bpfkorea/agora/blob/c6a7e45af58cfc052f2a5b28e7030e8060fbc15e/source/agora/test/SlashingMisbehavingValidator.d#L68
