### ISSUE TITLE
inconsistent voting during SCP protocol run

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1690]
in Nominator.validateValue method we will validate the transactions and part of that validation is whether the transaction is present or not in our local pool. If it is not present, we will return kInvalidValue from validateValue. Later we might receive the missing transaction through the gossiping protocol and also receive an identical ConsenusData candidate to our previous ConsensusData. This this we will vote with kFullyValidatedValue contradicting the previous kInvalidValue.

**Comment by AndrejMitrovic** [comment]
I mentioned this in my comment previously https://github.com/bpfkorea/agora/pull/1495#discussion_r557451465
