### ISSUE TITLE
signature related datastructures inside EnrollmentManager are not restored

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1703]
If the validator is restarted and the UTXO array is provided while creating the Ledger object, then 'key_to_index' and 'index_to_key' datastructeres are not recovered(left empty) for past blocks. Those datastructures are recovered though if the Ledger is created without the UTXO array. 

@hewison-chris could you please confirm this? I haven't tested, just found this while looking at the code.

**Comment by Geod24** [comment]
> and the UTXO array is provided while creating the Ledger object

What UTXO array ? You mean the Ledger loads UTXOs ?

**Comment by ferencdg** [comment]
> > and the UTXO array is provided while creating the Ledger object
> 
> What UTXO array ? You mean the Ledger loads UTXOs ?

should have said:

UTXO array is provided while creating the Ledger object = 
UTXOSet(utxo_set) is passed to the Ledger's constructor

when the utxo_set is passed a different code path will update the  'key_to_index' and 'index_to_key' arrays...

I am not sure whether the current code requires those 2 arrays for PAST blocks or only requires for future blocks... However I will need the values for the PAST blocks for ticket #246
