### ISSUE TITLE
Node should try to gossip transactions after network state is complete

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1726]
Consider this scenario:

- User boots up their FullNode / Validator
- They have their wallet send a transaction to only their own node
- The node hasn't completed network discovery (maybe it's slow, network is delayed..). Therefore `putTransaction` accepts the tx in the pool but does not gossip it because it has nobody to gossip to.

End result: the tx is now stuck forever in the pool.

If there are incoming transactions which are accepted in the pool but the network state is incomplete then the node should queue these transactions for gossiping later.

**Comment by omerfirmak** [comment]
For the Validator this is not really a problem, if the TX makes it to a nomination it will be known to all Validators. If it does not get included in a nomination, it is probably not really worth to be gossiped anyways.

But we should probably come up with a solution for the FullNode case.

**Comment by omerfirmak** [comment]
What would you guys think of moving the `gossip_queue` and all the stuff associated with it in `NetworkClient` to `NetworkManager`?

That way we can make sure we have atleast a single peer before gossipping and avoid duplicating gossiped data for each peer.

**Comment by AndrejMitrovic** [comment]
I think that might work.

**Comment by omerfirmak** [comment]
> What would you guys think of moving the `gossip_queue` and all the stuff associated with it in `NetworkClient` to `NetworkManager`?

I tried this but the current per-client-fiber approach seems to be performing better. We may need a second queue at the `NetworkManager`.
