### ISSUE TITLE
Flash: Add version bits

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1743]
This also includes error reporting. For example in LN:

```
A node:
upon receiving a higher version packet than it implements:
  MUST report a route failure to the origin node.
  MUST discard the packet.
```

**Comment by omerfirmak** [comment]
I think https://github.com/bpfkorea/agora/pull/1802 was the all we can do for this issue.
AFAICS, LN does not do any versioning of their API. Only onion packets have a versioning scheme.

**Comment by AndrejMitrovic** [comment]
Alright, that's good enough for now!
