### ISSUE TITLE
Agora cannot recover Enrollments from scratch if a node has been slashed

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1750]
Not tested, but the following seems a bug leading to a potential crash during agora startup

1.
UTXOs are passed to Ledger constructor, but validator count is 0, so we try to recover the enrollments: 
https://github.com/bpfkorea/agora/blob/2db3509097a9b89b6bb148aadaa9aec1fcb4697a/source/agora/node/Ledger.d#L210

we assume UTXOs are are correct up until the latest height of X, and we also assume that UTXO U was enrolled at height Y (X - cycle length < Y < X), and we also assume that this UTXO U was slashed at height Z(Y<Z<X). As a result of this, we will not have UTXO U in the utxo_set at height X.  

2.
the following line will assert during restoration of the validator set:

https://github.com/bpfkorea/agora/blob/2db3509097a9b89b6bb148aadaa9aec1fcb4697a/source/agora/node/Ledger.d#L505

Let me know if I misread the code.

**Comment by Geod24** [comment]
This is correct. Renamed the issue for clarity.

**Comment by omerfirmak** [comment]
After a couple of days of tinkering (sadly), I realized that both `UTXOSet` and `EnrollmentManager` uses the `stateDB`, so the case here will probably never happen unless someone messes up the database externally. At that point we should not trust the existing UTXO set either.

**Comment by Geod24** [comment]
Currently we have code to recover Enrollments if their length is 0, but still use the `UTXOSet`. With that assumption, we probably need to do a deep reset if either is empty.
