### ISSUE TITLE
Assert triggered in OnionPacket.d:169

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1772]
We have the following path:
https://github.com/bpfkorea/agora/blob/93b4db119f8809b7cb8681c9f7db098232dbf2d1/source/agora/flash/Node.d#L891-L897

And `getPaymentPath` may return `null`. However the above code doesn't handle it, and we later hit an `assert`:
https://github.com/bpfkorea/agora/blob/93b4db119f8809b7cb8681c9f7db098232dbf2d1/source/agora/flash/OnionPacket.d#L169

This is "possibly a timing issue" according to @AndrejMitrovic (seems to trigger more often on OSX machines which are indeed slower), and can be observed frequently in the CI.

**Comment by omerfirmak** [comment]
Do we have a full stack trace? Multiple tests could trigger that.

**Comment by Geod24** [comment]
https://github.com/bosagora/agora/blob/309989a54529ec708ecab235547662aabdc5740d/source/agora/flash/OnionPacket.d#L172

<img width="1340" alt="Screen Shot 2021-03-31 at 9 47 59" src="https://user-images.githubusercontent.com/2180215/113074565-46c97900-9206-11eb-939e-d60be062f37b.png">

Looks like this isn't fixed yet.

**Comment by AndrejMitrovic** [comment]
Does it say which line in the test file it's coming from?

**Comment by Geod24** [comment]
Unfortunately there's no more log than what you see above :(
It's currently still running: https://github.com/bosagora/agora/pull/1850/checks?check_run_id=2232746880

**Comment by omerfirmak** [comment]
I think we should remove that assert anyways and propagate the failure to the caller.
Would probably give a more helpful error message.

**Comment by AndrejMitrovic** [comment]
Making a PR soon for it.

**Comment by AndrejMitrovic** [comment]
If this doesn't happen again in the next few days then we can close it.

**Comment by Geod24** [comment]
> If this doesn't happen again in the next few days then we can close it.

It didn't.
