### ISSUE TITLE
`WellKnownKeys` have SecretKey values which are not valid ECC Scalar values.

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#1776]
The problem is that the `WellKnownKeys` have SecretKey values which are not valid Scalar values. I will create a PR to address that specifically first.

_Originally posted by @hewison-chris in https://github.com/bpfkorea/agora/pull/1759#discussion_r592833950_

**Comment by Geod24** [comment]
I'm pretty sure this was introduced by https://github.com/bpfkorea/agora/pull/1702 ? In which case maybe figuring out what went wrong will be faster than regenerating them. And provably correct too :)

**Comment by hewison-chris** [comment]
> I'm pretty sure this was introduced by #1702 ? In which case maybe figuring out what went wrong will be faster than regenerating them. And provably correct too :)

I suspect that they have always been wrong. I will add the same check to a branch pre #1702 commit to verify. As sign and verify works even though the secret is not a valid Scalar we just didn't realise until the double signing with same `r` test added in PR https://github.com/bpfkorea/agora/pull/1759.

**Comment by Geod24** [comment]
> I suspect that they have always been wrong.

We confirmed this. Values are mostly `> L`.
