### ISSUE TITLE
Version script should return non-zero on error

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1832]
Currently version/main.d(version script) has a main function returning `void`. Even if we have an exception propageted outside the main, the program will return 0 as if everything is okay. This prevents us to terminate agora builds early as the rely on the return value of the version script.

**Comment by Geod24** [comment]
> Even if we have an exception propageted outside the main, the program will return 0 as if everything is okay.

No it won't, an uncaught Exception will lead to non-zero return code.

**Comment by ferencdg** [comment]
re-tested and uncaught exception is non-zero, turns out D isn’t *that* stupid
