### ISSUE TITLE
Transactions are 'free' in release build

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1855]
https://github.com/bosagora/agora/blob/f8211d9c6b216837c47a6be47f1c41904a40803e/source/agora/consensus/Fee.d#L438

https://github.com/bosagora/agora/blob/f8211d9c6b216837c47a6be47f1c41904a40803e/source/agora/consensus/Fee.d#L442

I will solve this as part of #245

**Comment by Geod24** [comment]
Oh yeah, one tenet of D: Don't perform side-effects in `assert`, it's almost always a bug.
We won't ship with `-release` anytime soon tho.
