### ISSUE TITLE
[Upstream] Investigate, report, and fix issue with code coverage

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1868]
Agora, when running in the integration test with coverage enabled, will produce files with mode `600`.
This results in Codecov not being able to upload the files:
```
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    -> Found 3010 reports
==> Detecting git/mercurial file structure
==> Reading reports
codecov.sh: line 1546: ./agora/tests/system/node/7/source-scpd-scp-SCPDriver.lst: Permission denied
Warning: Codecov warning: The process '/usr/bin/bash' failed with exit code 1
```

See https://github.com/bosagora/agora/pull/1867/checks?check_run_id=2243386596

**Comment by omerfirmak** [comment]
Well, `druntime` is clearly setting mode `600`.

https://github.com/dlang/druntime/blob/6c3adb102a2a804c802649156ca27cc878aad5d7/src/rt/cover.d#L459-L462

We could simply update it to set `644` but I don't get why we are running the tests and coverage uploader as 2 separate users.

**Comment by Geod24** [comment]
> but I don't get why we are running the tests and coverage uploader as 2 separate users.

Tests run in docker, coverage uploader does not.
And 600 is just wrong. We should be using the default `umask`.

**Comment by Geod24** [comment]
Done: https://github.com/dlang/druntime/pull/3421
