### ISSUE TITLE
Give meaningful names to well-known keypairs

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1878]
Since the move to Bech32, our well-known addresses no longer match an easy to recognize pattern.
We need to come up with a new pattern to use (`node` will not work, `o` is forbidden in bech32), change the vanity program, and mine them.

**Comment by hewison-chris** [comment]
Mentioned in planning (6th April 2021) that probably mining will not be required if we use HRP (Human Readable Part) to include names for well-known addresses.

**Comment by hewison-chris** [comment]
Should probably be done after https://github.com/bosagora/agora/issues/1354

**Comment by Geod24** [comment]
Fixed by #2008
