### ISSUE TITLE
Stats interface is somehow non-responsive despite node being up

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1888]
The stats endpoint on the live system is not responsive ATM, despite all nodes working correctly.
This might be related to #1887  or another HTTP endpoint not working.

**Comment by omerfirmak** [comment]
They seem to be all working fine at the moment. Even with debug logs enabled on NODE2, I can't find anything in the logs as well.

**Comment by Geod24** [comment]
Perhaps it had to do with the registry being down ?

**Comment by Geod24** [comment]
The root cause of this issue is the same as #1887 so closing as duplicate.
