### ISSUE TITLE
Improve message about leaking FD from Vibe.d

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1901]
Currently we see this message quite a bit:
```
Apr 05 08:17:02 eu-002 docker[85088]: [main(----) INF] Stopped to listen for HTTP requests on 0.0.0.0:2826
Apr 05 08:17:02 eu-002 docker[85088]: Main thread exiting
Apr 05 08:17:02 eu-002 docker[85088]: Warning (thread: main): leaking eventcore driver because there are still active >
Apr 05 08:17:02 eu-002 docker[85088]:    FD 18 (streamListen)
Apr 05 08:17:02 eu-002 docker[85088]:
Apr 05 08:17:02 eu-002 docker[85088]: There were still 2 tasks running at exit.
Apr 05 08:17:02 eu-002 docker[85088]: Warning (thread: main): leaking eventcore driver because there are still active >
Apr 05 08:17:02 eu-002 docker[85088]:    FD 18 (streamListen)
Apr 05 08:17:02 eu-002 docker[85088]:
```

However we don't know where those come from. It's also a scary message for our users to see.
What we should do:
1) Improve the message so we actually where in the user code the FD was instantiated;
2) Fix the underlying issue(s);

This issue is mostly after doing 1, as 2 comes and goes.

**Comment by ferencdg** [comment]
If, I remember this one is caused by not calling: http_listener.stopListening(); during agora shutdown. Did we add any new rest endpoint to Agora recently? 

Never mind, port 2826 hardly new...

**Comment by ferencdg** [comment]
related PR: https://github.com/bosagora/agora/pull/1146/files

**Comment by omerfirmak** [comment]
Upstream: https://github.com/vibe-d/eventcore/pull/183

**Comment by omerfirmak** [comment]
Done in https://github.com/vibe-d/eventcore/pull/183
