### ISSUE TITLE
Integration tests: it must be part of code

### ISSUE THREAD

**Issue by denizzzka** [bosagora/agora#191]
Same as unittests preferably if possible in particular case.

runner.d - is no good at all, it is even compiled with other compilation directives/versions like ommited version (Have_vibe_core).

**Comment by denizzzka** [comment]
```
[stderr]	/home/denizzz/Dev/agora/submodules/vibe.d/inet/vibe/inet/url.d(221): Error: cannot implicitly convert expression `GenericPath(null).this(urlDecode(this.m_pathString))` of type `GenericPath!(PosixPathFormat)` to `GenericPath!(InetPathFormat)`
[stderr]	/home/denizzz/Dev/agora/submodules/vibe.d/inet/vibe/inet/url.d(325): Error: none of the overloads of `path` are callable using argument types `(GenericPath!(InetPathFormat))`, candidates are:
[stderr]	/home/denizzz/Dev/agora/submodules/vibe.d/inet/vibe/inet/url.d(217):        `vibe.inet.url.URL.path()`
[stderr]	/home/denizzz/Dev/agora/submodules/vibe.d/inet/vibe/inet/url.d(232):        `vibe.inet.url.URL.path(GenericPath!(PosixPathFormat) p)`
```

**Comment by Geod24** [comment]
Runner.d is very simple at the moment. We should add more things there if it's missing `version`. `dub describe` probably exposes it.

**Comment by denizzzka** [comment]
Forgotten to write my proposal:

Just use `__integration_test()` functions inside of each needed to test module. it is oblivous, simple and powerful.

So, we can call something like `__integration_test_node_regression_123(addr, port){ ... }` to test particular cases.

**Comment by denizzzka** [comment]
> Runner.d is very simple at the moment. 

Run each test as separate application is ~weak idea because in this case you can't find bugs related to accidentally leaved states of objects (pointers to globals, wrong maintenance of DB tables, etc).

**Comment by denizzzka** [comment]
Also, this approach allows to check full needed matrix of compilation options and compilers as well as the release code. At trivial (and more appropriate as for me) case you can simply write:
```D
version(AgoraIntegrationTests)
{
   integration_tests_caller_or_just_tests_list();
}
else
{
  void main()
  {
  ...
  }
}
```

**Comment by Geod24** [comment]
> Run each test as separate application is ~weak idea because in this case you can't find bugs related to accidentally leaved states of objects (pointers to globals, wrong maintenance of DB tables, etc).

This is not the point of integration testing though. And having them separate means you can parallelize them.

**Comment by denizzzka** [comment]
> This is not the point of integration testing though.

Not agreed. If some code uses externals (such as DB) here is only one way to do testing of this - integration testing.

> And having them separate means you can parallelize them.

In my proposal it is also possible.

**Comment by Geod24** [comment]
The way it is currently implemented is rather simple, and not final.
The test runner (`test/runner.d`) is intended to be for small module, typically the BlockStorage.
For full-fledged integration tests, we will have docker containers running `agora`. I am working on this at the moment.
