### ISSUE TITLE
Flash: Channel updates are ignored unless channel open message was received first

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1910]
There is a race condition where channelOpen and channelUpdate messages are sent at roughly the same time. Any node which receives them out of order will currently reject the channel update message.

The only reason this doesn't happen in the tests is because most of the APIs were blocking and therefore assumed a certain order of messages.

**Comment by Geod24** [comment]
Any update on this ?

**Comment by AndrejMitrovic** [comment]
Will probably be moved to next sprint.

**Comment by AndrejMitrovic** [comment]
So I looked into this more, and I believe the issue is invalid. https://github.com/bosagora/agora/pull/1913 actually resolved the blocking issues. And there are two additional causes of updates being sent:

1. In [here](https://github.com/bosagora/agora/blob/b8ab53a1e115f888b435c1c3117d11d703d11384/source/agora/flash/Node.d#L616) just after a channel is detected as open. It's ok for counter-parties to ignore this update because they will manually reconstruct it once they receive the channel open message later in [here](https://github.com/bosagora/agora/blob/b8ab53a1e115f888b435c1c3117d11d703d11384/source/agora/flash/Node.d#L612).
2. Updates sent after the fee is updated dynamically. This typically happens much more later after a channel is initially open, therefore there should be no timing issues here.

Closing this as invalid.

**Comment by omerfirmak** [comment]
>     2. Updates sent after the fee is updated dynamically. This typically happens much more later after a channel is initially open, therefore there should be no timing issues here.

We do send them back to back to initialize the fees though. Would not that still be a problem for the other non-participating nodes? 

https://github.com/bosagora/agora/blob/b8ab53a1e115f888b435c1c3117d11d703d11384/source/agora/flash/Node.d#L615-L616

https://github.com/bosagora/agora/blob/b8ab53a1e115f888b435c1c3117d11d703d11384/source/agora/flash/Node.d#L656

> In here just after a channel is detected as open. It's ok for counter-parties to ignore this update because they will manually reconstruct it once they receive the channel open message later in here.

They only reconstruct their own update, right? They may still need the update for the opposite direction.

**Comment by AndrejMitrovic** [comment]
> They only reconstruct their own update, right? They may still need the update for the opposite direction.

Ah I haven't considered that. Do you want to try to tackle this issue?
