### ISSUE TITLE
Flash: Need to use proper lock height for settlement txs and add validation

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1927]
https://github.com/bosagora/agora/blob/ca80a17ca6dd33981cc86f0f8de606cc7055edeb/source/agora/flash/OnionPacket.d#L214

Note how the settle time is checked here during construction time:

https://github.com/bosagora/agora/blob/ca80a17ca6dd33981cc86f0f8de606cc7055edeb/source/agora/flash/Node.d#L657

But it is not set properly here:
https://github.com/bosagora/agora/blob/ca80a17ca6dd33981cc86f0f8de606cc7055edeb/source/agora/flash/Node.d#L1140

And it's also not checked in this routine:

https://github.com/bosagora/agora/blob/ca80a17ca6dd33981cc86f0f8de606cc7055edeb/source/agora/flash/Channel.d#L1296

So there might be several functions to change. Maybe even `createOnionPacket` wouldn't take the `lock_height` parameter, but would instead automatically calculate this from each channel's settlement time.

**Comment by omerfirmak** [comment]
Do we really need to put lock height in the onion packets? Nodes can propose different lock heights to their peers anyways, as long as they can agree on them, right?

**Comment by AndrejMitrovic** [comment]
Yes you're right about that.

**Comment by omerfirmak** [comment]
@AndrejMitrovic , do you think this can be closed now?

**Comment by AndrejMitrovic** [comment]
I think so!
