### ISSUE TITLE
EnrollmentPool should clear no-longer-usable enrollments

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1944]
Currently, in the `EnrollmentPool`, we have an `avail_height`, which is the lower bound on when an enrollment is available.
Unfortunately, it's also the upper bound, as an `Enrollment` contains a pre-image which must match exactly with the previous `Enrollment`. It seems that something doesn't work ATM:
- We should be clearing expired `Enrollment`;
- We should be re-sending `Enrollment` when we detect they are no longer valid;
- We should be propagating the pre-image that comes with an `Enrollment` (optional);

This test is only valid if validators re-send their enrollments:
https://github.com/bosagora/agora/blob/24c7efe3cf18333feb54416ec6b3e7cd5e963538/source/agora/test/ValidatorRecurringEnrollment.d#L234-L235

However, the height test seems invalid:
https://github.com/bosagora/agora/blob/24c7efe3cf18333feb54416ec6b3e7cd5e963538/source/agora/test/ValidatorRecurringEnrollment.d#L233-L234

`GenesisValidatorCycle` is 20, which means genesis validators will validate 20 blocks, with height `[1; 20]` (inclusive).
This means that `Enrollment`s needs to happen on the last block they validate to be valid (at height 20), however we test for height 21.

**Comment by omerfirmak** [comment]
That test limits the enrollments per block. So some of the validators can't get re-enrolled at height 20. They resend their request and get enrolled at height 21. So what you are describing is the expected outcome.

> We should be clearing expired Enrollment;

IIRC they are cleared all at once. When the Validator is finally enrolled.

**Comment by Geod24** [comment]
Done as part of #1902
