### ISSUE TITLE
Agora mempool is unlimited in size

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1959]
this could easily lead to DoS attacks, we should 
. limit the size of the pool
. evict old entries periodically
. replace transactions in the mempool based on (tx fee/size) when a new transaction is goshiped to us and the pool is at it's maximum size
. transactions received through getTransaction during consensus should probably be included in the pool even, if the pool would go above the limit

**Comment by omerfirmak** [comment]
> . limit the size of the pool

I don't think this is an ideal solution. We should make it infeasible to spam the mempool through double-spent filtering and tx replacement with fees.

> . evict old entries periodically

This would need wallet implementations to keep track of their pending TXs. We could maybe put a `valid_until` argument to the `putTransaction` interface and evict the TX if it is not externalized by that block.

> replace transactions in the mempool based on (tx fee/size) when a new transaction is goshiped to us and the pool is at it's maximum size

We should be doing this regardless of our mempool size anyway.

>  . transactions received through getTransaction during consensus should probably be included in the pool even, if the pool would go above the limit

see my first comment


Thoughts?
