### ISSUE TITLE
Suspicious assert in validateBlock()

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#1964]
https://github.com/bosagora/agora/blob/e6f3591f557dbf1eac4f2f76749732428505c9a0/source/agora/node/Ledger.d#L875

Unless I'm misunderstanding the code, it seems like this assert can be triggered if we provide a valid block with zero signatures to `validateBlock()`.

**Comment by Geod24** [comment]
Do we ever pass a block with no signature ? There has to be someone having signed it (actually, > 50% having signed it) for it to be passed to the Ledger, no ?

**Comment by hewison-chris** [comment]
In fact I think it would be bad if we didn't assert in this case.

**Comment by AndrejMitrovic** [comment]
Couldn't you receive a block like this from periodic catchup?

**Comment by hewison-chris** [comment]
> Couldn't you receive a block like this from periodic catchup?

You could but it should fail in block.isInvalidReason before reaching the signature checks.

**Comment by AndrejMitrovic** [comment]
I didn't see where in `block.isInvalidReason` it checks for the validator signatures.

**Comment by hewison-chris** [comment]
> I didn't see where in `block.isInvalidReason` it checks for the validator signatures.

Sorry it is here `if (signed <= enrolled_validators / 2)` in the validateBlock before the assert.

**Comment by AndrejMitrovic** [comment]
Ahh ok. Was hard to find. Then I'll close the issue.
