### ISSUE TITLE
TransactionPool and EnrollmentPool should accept "future" transactions

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1975]
One issue that is showing in our tests is the following scenario:
- Nodes produce blocks, arriving towards the end of their cycle (let's assume cycle = 20);
- One node becomes non-responsive after externalizing height 18;
- A frozen tx is sent at height 19 and externalized;
- Node comes back online;
- An enrollment is sent using said frozen tx;
- Node will reject enrollment;

This is for enrollment, but transactions suffer from the same issue. The tx pool should be greatly improved to deal with those scenarios.

**Comment by linked0** [comment]
@Geod24 Could you comment about what should be done on this issue whenever you have time?
We discussed this issue at the whiteboard on 31 August and you said you had a different opinion from mine.

**Comment by Geod24** [comment]
So, following other developments to the `TransactionPool`, it would be counter-productive to accept arbitrarily future transactions, however we should be able to *accept enrollments* that refer to transactions in the pool (so that both can be externalized in the same block.

**Comment by linked0** [comment]
The main thing for enrollment of this issue can be solved with issue #755 because [the PR](https://github.com/bosagora/agora/pull/2441) for the latter is restoring enrollments from other nodes periodically. A network test of the PR tests the situation where a node missed a transaction and an enrollment that uses a UTXO of the transaction. So I think this issue can also be closed with the PR.

**Comment by linked0** [comment]
@Geod24 Can you leave your opinion about [^this](https://github.com/bosagora/agora/issues/1975#issuecomment-914778438)?

**Comment by Geod24** [comment]
I don't think so. We currently do not accept an enrollment that refers to a non-externalized freeze tx, do we ?

**Comment by linked0** [comment]
Right, we do. But we can fetch the missing enrollments from other nodes from the implementation of [the PR](https://github.com/bosagora/agora/pull/2441). I'm afraid there could be so many fake enrollments that could be stored in the pool and verifying enrollments without UTXOs could make the validation code complex. I thought the main thing is nodes not having missing enrollments.

**Comment by linked0** [comment]
@Geod24 I think I can solve this issue with this code you told me yesterday. Ty.
https://github.com/bosagora/agora/blob/597904fc7c4b0f236094d2b517d41a383b2baa6d/source/agora/consensus/validation/Block.d#L141-L155
