### ISSUE TITLE
Blocks can be created by an attacker at any time

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#1994]
An attacker could modify the Agora code, and start a nomination right after the last block was created. If I read the code correctly, there is nothing preventing the nodes from externalizing that block before the 10 mins block duration ends. If the attacker also enrolls as a validator, he can earn the block reward at a much faster rate.

**Comment by AndrejMitrovic** [comment]
Isn't this because the check was removed in `validateValue` in https://github.com/bosagora/agora/commit/33d73ad09372e0cd9910f7f1278f0054963bfb6d?

**Comment by ferencdg** [comment]
I think that code block didn't work correctly. Just because a nomination arrives before time, we shouldn't mark it as invalid. If we vote with 'no' to it, just because it arrived too early, but everything was okay with it, we can no longer vote 'yes' to it even if we receive the same envelope later.

I think we should just either 'cache the early envelope' in the receive envelope or 'ignore it'(worse)

**Comment by ferencdg** [comment]
this might not even be an issue as it seems NominationProtocol::processEnvelope checks if we are in a nominating state for a particular slot(and that nominating state is only on, after calling NominationProtocol::nominate)

Also SCP implementation is nice enough to cache all the envelopes that belongs to slots on which nomination hasn't started yet

**Comment by ferencdg** [comment]
just as I thought, in latest SCP code: envelopes arriving before nomination are cached and have no effect

https://github.com/stellar/stellar-core/blob/9c3e67776449ae249aa811e99cbd6eee202bd2b6/src/scp/NominationProtocol.cpp#L388
