### ISSUE TITLE
Implement inbound connection banning support in vibe.d

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#202]
As a Developer, I need to prevent one form of DDoS attacks from other nodes, we need support for banning inbound connections from specific addresses.

**Definition of Done:**
- [x] When a request reaches the server, it can be made to be rejected before any significant processing / memory allocation happens
- [x] The functionality supports dynamically banning
- [x] The functionality supports dynamically unbanning
- [x] The functionality does not add much overhead on the request processing

**Comment by ferencdg** [comment]
done by vibe.d PR #2496

**Comment by Geod24** [comment]
Ping @ferencdg : This just needs some adaptation from Agora's side.

**Comment by ferencdg** [comment]
fixed by https://github.com/vibe-d/vibe.d/pull/2510

**Comment by ferencdg** [comment]
we do have to modify Agora to make sure that internally we would never deal with dns names, as vibe.d can only check if a node is banned or not by IP
