### ISSUE TITLE
Add freezing capability to UTXO

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#204]
As a node operator, I can create a transaction that marks my UTXO as “frozen” so that I can use it as collateral for running a validator node.

**Definition of Done:**
- [x] An UTXO can be marked as "frozen"
- [x] When a transaction spending a frozen UTXO comes in, it marks the UTXO as "melting" for 2016 blocks
- [x] Transactions attempting to spend melting UTXO are invalid
- [x] After the UTXO has melt, the new UTXO can be spent without delay
- [x] The amount must be exactly 40,000 BOA (for the moment)

**Comment by MichaelKim20** [comment]
### Transaction & UTXO in Freeze
The design was based on **Definition of Done**.
Illustrated the changing situation over time for **Block / Transaction / UTXOSet.**

<img width="920" alt="Transaction & UTXO in Freeze" src="https://user-images.githubusercontent.com/11639939/65112733-9c22a880-da1b-11e9-9f1b-55f4b00098c5.png">
<img width="896" alt="" src="https://user-images.githubusercontent.com/11639939/65110791-82319780-da14-11e9-9367-2f8eac1c87f0.png">



![Block_Tx_UTXO 001](https://user-images.githubusercontent.com/11639939/65367182-a7b6df00-dc68-11e9-9e56-224fe5c6b5ff.jpeg)

![Block_Tx_UTXO](https://user-images.githubusercontent.com/11639939/65367153-219a9880-dc68-11e9-89ae-39ac288ef2ee.gif)

![FreezingAndUTXO](https://user-images.githubusercontent.com/11639939/65403828-b213dd00-de10-11e9-9ac9-1e0bc328e7b5.gif)

**Comment by MichaelKim20** [comment]
### Define of Subtask
1. Add type to struct `Transaction`
2. Implement UTXOSetValue to be used by UTXOSet
3. Implement  validation when receive transaction 'freeze'  in melted and , receive transaction 'payment'  in frozen.(TX2, TX3 in upper diagram)
4. Implement  validation when receive transaction 'payment' in various status (melting, melted)(TX4, TX5 in upper diagram)

**Comment by Geod24** [comment]
Well done!
