### ISSUE TITLE
Implement support for secp256k1

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#207]
As a user, I need to be able to use my TokenNet key in CoinNet in order to use CoinNet without going through YAA (Yet Another Airdrop).

**Definition of Done:**
- [ ] There is a `crypto_scalarmult_secp256k1` similar to `crypto_scalarmult_ed25519` with secp256k1
- [ ] There is a `crypto_scalarmult_secp256k1_base` similar to `crypto_scalarmult_ed25519_base` with secp256k1
- [ ] There is a `noclamp` version of those scalarmult functions

**Comment by Geod24** [comment]
Depends on #208

**Comment by AndrejMitrovic** [comment]
Should this be unblocked?

**Comment by Geod24** [comment]
We should also take a look at the implementation of Schnorr in Bitcoin Cash

**Comment by Geod24** [comment]
After discussing more extensively about the transition process, we decided not to go through with this.
