### ISSUE TITLE
When the encrypted key is provided, it should be changed to use the pre-image of the actual validator.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#2074]
The encrypted key is used to vote in Votera. 
The pre-image of the validator is not included in the process of creating the encrypted key.
We need to modify to generate an encrypted key using the pre-image associated with that node.

**Comment by Geod24** [comment]
@TrustHenry : Could you fix it, since you originally implemented it ?
https://github.com/bosagora/agora/blob/dc5f739c64768e978deb65b4d2b5b8470976d8a7/source/agora/node/admin/AdminInterface.d#L186-L188

**Comment by TrustHenry** [comment]
@Geod24 Of course. 
`Height(Vote closing height) + PreimageRevealPeriod`  Should I release the pre-image with this formula?
