### ISSUE TITLE
makeTestNetwork doesn't properly connect nodes

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2078]
I might be mistaken, as I didn't test, but it seems 'makeNetworkConfig' makes a network of validators where each validator are connected and also a separate network where all the FullNodes are connected, but these two network doesn't seem to have any common node. Not what I would expect when using NetworkTopology.FullyConnected

**Comment by AndrejMitrovic** [comment]
I think the full nodes connect to all other validators and all other full nodes. https://github.com/bosagora/agora/blob/7408cb51d225aa7b88f7080beeeb78db07b13a47/source/agora/test/Base.d#L2148

But the validators do not connect to all other full nodes. Normally that isn't an issue because validators don't care about establishing a connection to full nodes, only the other way around (at least in the tests).

**Comment by ferencdg** [comment]
hmmm that is right... but it gets a little confusing with the MinimallyConnected when the validators form their own chain while the first full node will connect to the last validator.

V1 <- V2 <- V3 <- V4 <- V5 <- F1 <- F2 <- F3 <- F4

V1 will point to V5 so the full chain will be
V5 <- V1 <- V2 <- V3 <- V4 <- V5 <- F1 <- F2 <- F3 <- F4

bit of a headache that we have to keep this in mind

**Comment by AndrejMitrovic** [comment]
This layout was initially created back when we started using SCP. SCP had a circular layout as one of the tests, so we copied it just to make sure it works. That's the only reason we have this test. Perhaps it's unnecessary if our quorum generator will never create these types of cyclic quorums.

**Comment by ferencdg** [comment]
> This layout was initially created back when we started using SCP. SCP had a circular layout as one of the tests, so we copied it just to make sure it works. That's the only reason we have this test. Perhaps it's unnecessary if our quorum generator will never create these types of cyclic quorums.

thanks, I am just testing a network crawler that we will use for 
https://github.com/bosagora/agora/issues/251
and then started to look into how the minimally connected network works. I would be nice to keep this network for the crawler network tests.
