### ISSUE TITLE
Collecting signatures from slashed nodes bug

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2102]
I don't see anything in our code that would prevent us from collecting signatures from slashed validators: that means I can no longer assume that the Header.validators contains only enrolled and non-slashed validators.

**Comment by hewison-chris** [comment]
Are you aware that there are queries in ValidatorSet that exclude the slashed nodes?
https://github.com/bosagora/agora/blob/dc5f739c64768e978deb65b4d2b5b8470976d8a7/source/agora/consensus/state/ValidatorSet.d#L315

**Comment by ferencdg** [comment]
The part I cannot find is where exactly are we checking if the validator is slashed in the 'receiveBlockSignature' method? 

Either a bug in the agora implementation or just a malicious validator could produce a signed block even though the validator is slashed. If that signed block is processed later in 'receiveBlockSignature' then it would mess up header.validators

**Comment by ferencdg** [comment]
My original intention here was that map `slot_sigs` should only valid contain signatures from non-slashed validators, so it is easier to reason about/use `slot_sigs`. Sadly `slot_sigs` is updated even during the balloting phase when the externalized value is not yet decided upon. Instead of trying to fix this, I will just leave a comment on `slot_sigs` that it might contain signatures from slashed validators too.

The original reason of why I wanted to use `slot_sigs` is block rewards are distributed to non-slashed validators who also signed.

**Comment by ferencdg** [comment]
> My original intention here was that map `slot_sigs` should only valid contain signatures from non-slashed validators, so it is easier to reason about/use `slot_sigs`. Sadly `slot_sigs` is updated even during the balloting phase when the externalized value is not yet decided upon. Instead of trying to fix this, I will just leave a comment on `slot_sigs` that it might contain signatures from slashed validators too.
> 
> The original reason of why I wanted to use `slot_sigs` is block rewards are distributed to non-slashed validators who also signed.

**Comment by hewison-chris** [comment]
> My original intention here was that map `slot_sigs` should only valid contain signatures from non-slashed validators, so it is easier to reason about/use `slot_sigs`. Sadly `slot_sigs` is updated even during the balloting phase when the externalized value is not yet decided upon. Instead of trying to fix this, I will just leave a comment on `slot_sigs` that it might contain signatures from slashed validators too.
> 
> The original reason of why I wanted to use `slot_sigs` is block rewards are distributed to non-slashed validators who also signed.

I think it is best to use the `validators` field in the block header to identify who has signed. The map is just a local map of signatures that is not synched between the nodes.

**Comment by ferencdg** [comment]
> > My original intention here was that map `slot_sigs` should only valid contain signatures from non-slashed validators, so it is easier to reason about/use `slot_sigs`. Sadly `slot_sigs` is updated even during the balloting phase when the externalized value is not yet decided upon. Instead of trying to fix this, I will just leave a comment on `slot_sigs` that it might contain signatures from slashed validators too.
> > The original reason of why I wanted to use `slot_sigs` is block rewards are distributed to non-slashed validators who also signed.
> 
> I think it is best to use the `validators` field in the block header to identify who has signed. The map is just a local map of signatures that is not synched between the nodes.

Ugh, I just checked and I was using the `validator` field in the block header in the block reward ticket.
