### ISSUE TITLE
use leveldb instead of our handcrafted blockstorage

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2116]
leveldb is used by other blockchains like Ethereum for example, and has a lot of advantages over our current block storage implementation:

- caching of frequently accessed data in memory (last N blocks)
- data is compressed before written to disk, but kept uncompressed in the memory cache
- proabably more efficient implementation
- atomic writes, so data is not corrupted if agora shuts down during writes

leveldb has C bindings, so we could easily generate the D bindings: 
https://github.com/google/leveldb/blob/master/include/leveldb/c.h

**Comment by Geod24** [comment]
While it's something we probably need to consider in the future, the block storage is currently working well and not causing any issue. So closing as WONTFIX until the need arises.
