### ISSUE TITLE
Network tests: Remove override of `prepareNominatingSet`

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#2128]
In some of the network unit tests the test config field `txs_to_nominate` is used in an overridden `prepareNominatingSet` which effects if it is ready to nominate and how many transactions will be included in the nominating set. This behavior is too different to the production code so the tests are less useful. Most tests no longer use this method but `setTimeFor(Height)` which advances the current time to the network time for nomination at the given height.
The remaining tests should be ported to use this overridden clock method.

**Comment by Geod24** [comment]
The PR hasn't been merged yet ?
