### ISSUE TITLE
Validators not nominating

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#2169]
Currently when running the single node Agora using `build/agora -c devel/config-single.yaml`. On startup the validator is checking in `agora.node.Validator:regenerateQuorums` to see if it is enrolled and deciding that it is not and therefore not starting the nomination timer.

**Comment by Geod24** [comment]
Need a bit more details. It's obviously nominating in a lot of cases, since all tests would fail otherwise.

**Comment by hewison-chris** [comment]
> Need a bit more details. It's obviously nominating in a lot of cases, since all tests would fail otherwise.

Yes I can only confirm it is an issue for single node at the moment so have updated the details above.

**Comment by hewison-chris** [comment]
Was solved with seed update in yaml file.
