### ISSUE TITLE
Agora can crash given invalid transactions

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#2194]
While testing Agora using Faucet it was found that it is possible to cause Agora to crash.

**Comment by kchulj** [comment]
Does this still occur?

**Comment by hewison-chris** [comment]
> Does this still occur?

I think we need to try and make it crash in more tests before closing this one.

**Comment by hewison-chris** [comment]
I switched to the Faucet branch I created the last time when Agora crashed due to segv caused by bad transactions from Faucet. I could not reproduce the crash seen before. I will close this issue.
