### ISSUE TITLE
Flash: off-chain transactions should include fees

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#2200]
Flash nodes pre-sign the off-chain transactions, later to be used in a non-collaborative close attempt. Since this involves timelocks, timely externalization of those transactions are key to the security of Flash Layer. In a congested network, including fees to the TX is the only way to somewhat ensure that.

Trigger/update/settlement transactions should include some (probably dynamically determined) fees to be able to function properly.

**Comment by omerfirmak** [comment]
We could interface with Stoa as it already [provides](https://github.com/bosagora/stoa/blob/7107c0a63ff66a0f6a3d2e188b598d41a18f7ad9/src/Stoa.ts#L139) a fee calculation interface. Assuming it will be dynamic, we can probably use that and add a margin on top of that just to be sure.

**Comment by omerfirmak** [comment]
From https://github.com/bosagora/agora/pull/2227;

> Any fees associated with a non-collaborative closing attempt should be handled differently and paid by the peer that is attempting to close the channel.

With our current sequence signatures using the whole TX hash, it is not possible to add new inputs/outputs to a settlement/update TX after it is signed. We should come up with a scheme that allows adding new inputs/outputs but ensures that we cannot modify the existing ones. Since existing inputs/outputs are of equal value, there will be no risk of channel funds being stolen/rerouted.

**Comment by omerfirmak** [comment]
I have decided to only hash the channel funds related inputs/outputs and use TX `payload` field to determine which ones are to be hashed or not. Will probably have a PR soon.

**Comment by omerfirmak** [comment]
> 
> 
> I have decided to only hash the channel funds related inputs/outputs and use TX `payload` field to determine which ones are to be hashed or not. Will probably have a PR soon.

See https://github.com/bosagora/agora/pull/2227/commits/d698dd14352adab0441ff740386780a4178cb16a

**Comment by omerfirmak** [comment]
#2227 implements this for funding and closing TXs but it is better to implement fees for update/settlement TXs after #2281 is resolved. So this issue is half in-review half blocked.

**Comment by Geod24** [comment]
Fixed in #2383
