### ISSUE TITLE
Nomination: Nodes should reject higher nomination with larger missing validators

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2201]
Currently, our consensus protocol does not reject a new nomination from a node that uses a different `missing_validators`.
We should always make sure that any nomination for a new round includes at most all missing validators from the previous round, but no new ones.

For example, this is valid (assuming 6 validators):
```
- Round 0: [1, 3, 5]
- Round 1: [1, 3, 5]
- Round 2: [1, 5]
- Round 3: [5]
- Round 5: []
```

But those are not valid:
```
- Round 0: [1, 3, 4]
- Round 1: [1, 3, 4, 5]
```
```
- Round 0: [1, 3, 4]
- Round 1: [1, 3, 5]
```
```
- Round 0: [1, 3, 4]
- Round 1: [2]
```

**Comment by ferencdg** [comment]
"Currently, our consensus protocol does not reject a new nomination from a node that uses a different missing_validators" -  I am not sure it is true, whenever a node receives an evelope it will check if the value(regardless of wheteher it is nomination or ballot) in the 

validateValue->validateConsensusData->validateSlashingData->isInvalidPreimageRootReason

in isInvalidPreimageRootReason we will check the missing validators(I am not saying that particular check is correct though)

---

the negative examples you described would never happen in our current implementation I think
- Round 0: [1, 3, 4]
- Round 1: [1, 3, 5]

A well-behaving node that once voted on [1, 3, 4] would never vote on [1, 3, 5] as it means he 'forgot' the preimage for validator 5

---

I think a much more fundamental issue(that would solve this ticket too) would be to implement https://github.com/bosagora/agora/issues/2152 according to this comment:  https://github.com/bosagora/agora/pull/1902#discussion_r622752934

**Comment by Geod24** [comment]
> A well-behaving node that once voted on [1, 3, 4] would never vote on [1, 3, 5] as it means he 'forgot' the preimage for validator 5

But a well behaving node should check that the envelope it gets is not obviously wrong.

**Comment by ferencdg** [comment]
> > A well-behaving node that once voted on [1, 3, 4] would never vote on [1, 3, 5] as it means he 'forgot' the preimage for validator 5
> 
> But a well behaving node should check that the envelope it gets is not obviously wrong.

and it does in 
validateValue->validateConsensusData->validateSlashingData->isInvalidPreimageRootReason

if Node99 accepted the cadidate [1, 3, 4] into its candidate set, then it is guaranteed that isInvalidPreimageRootReason was called at least once and passed(guaranteed by SCP). It also means Node99 knew the preimage for Node5. If Node99 now receives an envelope [1, 3, 5], then it is guaranteed to fail as isInvalidPreimageRootReason is called again(and fail, because Node99 didn't forget the preimage for Node5) . This is current implementation(again the implementation has a lot of problem), I am just saying the current implementation already handles those cases.

**Comment by ferencdg** [comment]
also I see 'Rounds' here I think rounds are only in the balloting phase of the protocol, however the candidates are validated in places like CombineCandidate as well and that CombineCandidate method is called during the nomination phase

**Comment by ferencdg** [comment]
I think this have been solved by https://github.com/bosagora/agora/pull/2235
