### ISSUE TITLE
Invalid consensus data proposal: enrollment utxo shouldn't be spent in the same proposal 

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2214]
Currently we don't check whether the new enrollment utxo in the consensus data is also spent as a payment transaction in the same proposed block

**Comment by Geod24** [comment]
We do. For the same reasons mentioned [here](https://github.com/bosagora/agora/issues/2278#issuecomment-880326511).
We provide a UTXO finder to the block validation function:
https://github.com/bosagora/agora/blob/a9018c440550e464ae6154e03936decc47a5e7b1/source/agora/node/Ledger.d#L770

That UTXO finder will memoize the transactions looked up during tx validation:
https://github.com/bosagora/agora/blob/a9018c440550e464ae6154e03936decc47a5e7b1/source/agora/consensus/validation/Block.d#L132-L138

And then, when validating Enrollments, we use a combination of the current UTXO finder and the new outputs in the block (to allow for freeze and enroll at the same height):
https://github.com/bosagora/agora/blob/a9018c440550e464ae6154e03936decc47a5e7b1/source/agora/consensus/validation/Block.d#L151-L172
