### ISSUE TITLE
Make the `signature` catchup `block` distance well defined 

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#2230]
When a block has been externalized the maximum block distance to accept signatures from Validators who sign late should be defined and implemented. This needs some discussion still if it will be related to the cycle length or the rewards block interval.
With @Geod24 it was agreed that we will only catchup signatures for blocks since last payment block.

**Comment by hewison-chris** [comment]
In PR https://github.com/bosagora/agora/pull/2241 we are using Consensus parameter `PayoutPeriod` to determine the last payment block.
When issue https://github.com/bosagora/agora/issues/246 is completed this may need to be updated.
For that reason this issue will be kept open after PR 2241 is merged.

**Comment by Geod24** [comment]
Fixed
