### ISSUE TITLE
Leaking validator's private key by signing multiple ballot message

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2251]
recently I came accross with this:
https://www.scs.stanford.edu/~dm/blog/simplified-scp.html

if I understand correctly, if ValidatorA signs 2 different blocks at the same height, then it's private key is leaked. From our code, it seems when we are about to emit a SCP_ST_CONFIRM message we sign the block that is about to be created. 

However from the link above it doesn't seem that reaching the SCP_ST_CONFIRM state means the block that we just signed will definitely be to block that will eventually be externalized. I think the doc and the SCP code is a little bit out of sync, but the SCP_ST_CONFIRM seems to correspond in the doc with this:
'COMMIT ⟨n, x⟩: This states that value x is chosen in ballot n.'

you can also look at the SCP balloting code and see:

![image](https://user-images.githubusercontent.com/19815616/124898058-d2c71a00-e019-11eb-9bce-f293aa1a6ec1.png)

doesn't seem the federeated voting on the 'COMMIT (n,x)' (which has several steps) has finished while we are already sending and receiving SCP_ST_CONFIRM messages(and signing different blocks left and right at the same height and **LEAKING private keys**)

please comment

**Comment by ferencdg** [comment]
doesn't seems voting is finished...

![image](https://user-images.githubusercontent.com/19815616/124899460-1a9a7100-e01b-11eb-838b-170a0c0a8b91.png)

**Comment by hewison-chris** [comment]
I see two possible options which might solve this:-
1) Include the ballot number in the signature noise so that a node can only sign a single block each ballot round of SCP_ST_CONFIRM.
2) Only create block signaturtes in the SCP_ST_EXTERNALIZE phase.

**Comment by ferencdg** [comment]
I think we should keep it simple and would prefer option 2. However even option 2 can be insecure and reveal the private key in the following scenario:

ValidatorA's quorum has enough validator's under the control of an attacker. This attacker could trigger a valueExternalized event in ValidatorA's quorum and as a response ValidatorA would sign that block. Of course this block will not never have 50% of total signatures of ALL validators in the network, so will never be added to ValidatorA's ledger. Later ValidatorA will catch up and receive the real block agreed upon by the majority of the network. This block is different from what ValidatorA has already signed, and based on the current implementation I think ValidatorA will sign this new block too, again revealing its private key.

**Comment by Geod24** [comment]
> ValidatorA's quorum has enough validator's under the control of an attacker. This attacker could trigger a valueExternalized event in ValidatorA's quorum and as a response ValidatorA would sign that block.

That scenario shouldn't be possible possible though (well, highly unlikely).

**Comment by ferencdg** [comment]
I think it is a possible scenario and even mentioned in the SCP whitepaper under the name of befouled node

**Comment by ferencdg** [comment]
any chance of leaking the private key regardless of how likely it is should be tackled I think. Or we should somehow be able to calculate the probablility of such event and decide if that is acceptable

**Comment by Geod24** [comment]
I think, regardless of this issue, we should make sure, in the node, that we do not sign the same block twice.
Currently we don't because nodes are well behaved and simply won't do it, but as a mean to prevent any bug from having disastrous consequences on end user, there should be a failsafe mechanism.

**Comment by ferencdg** [comment]
I mentioned a corner case saying just blindly signing an externalized message is still dangerous if during the catchup (or at any point of time) the node signs a different block(which I assume it does currently). A well-behaving node can run buggy agora implementation, it is not about the node's intention.

**Comment by ferencdg** [comment]
> > ValidatorA's quorum has enough validator's under the control of an attacker. This attacker could trigger a valueExternalized event in ValidatorA's quorum and as a response ValidatorA would sign that block.
> 
> That scenario shouldn't be possible possible though (well, highly unlikely).

So if the calculation below is correct then after **10 days** there is a **30%** chance of at least 1 node to end up in a quorum where he can potentially be befouled and potentially **leak it's private key** unless we solve the corner case I mentioned. I think this is far from being very unlikely.

Here are the assumptions that are used that are based on our current implementation (with some simplification).
There are 1000 validators, 50 of them are under the control of an attacker. Each validator stakes the same amount of money, and so being equally likely to be chosen as a quorum member. Each quorum consists of exactly 7 nodes, and the 5 nodes out of the 6 nodes is enough for the remaining 1 node to be convinced. I assume that there are at least 1 validator in every 10 minutes that chose to enroll or at least 1 node whose enrollment expires. This will (according to our current implementation) trigger a quorum reshuffling in every 10 minutes. I assumed that the number of total validators always stays 1000 and the number of attackers stays 50. 

P<sub>at least 1 validator is befouled after X quorum suffling</sub> = (1 - (P<sub>no validators are befouled after 1 quorum suffling</sub>)<sup>X</sup>)

P<sub>no validators are befouled after 1 quorum suffling</sub> = (P<sub>one randomly chosen validator is not befouled after 1 quorum shuffling</sub>)<sup>950</sup>

P<sub>one randomly chosen validator is not befouled after 1 quorum shuffling</sub> = (1 - (P<sub>one randomly chosen validator is befouled after 1 quorum shuffling</sub>))

P<sub>one randomly chosen validator is befouled after 1 quorum shuffling</sub> = (50 / 1000) * (49 / 1000) * (48 / 1000) * (47 / 1000) * (46 / 1000) + (50 / 1000) * (49 / 1000) * (48 / 1000) * (47 / 1000) * (46 / 1000) *  (45 / 1000)

P<sub>at least 1 validator is befouled after 10 days</sub> = 
( 1 - ((1 - (50 / 1000) * (49 / 1000) * (48 / 1000) * (47 / 1000) * (46 / 1000) + (50 / 1000) * (49 / 1000) * (48 / 1000) * (47 / 1000) * (46 / 1000) * (45 / 1000))^950)^(10 * 24 * 6)) = 0.30473860327

Let me know if my calculation is incorrect and in fact it is me who got befouled.

**Comment by hewison-chris** [comment]
```
 // `valueExternalized` is called at most once per slot when the slot externalize its value.
    virtual void
    valueExternalized(uint64 slotIndex, Value const& value)
```
https://github.com/stellar/stellar-core/blob/master/src/scp/SCPDriver.h#:~:text=//%20%60valueExternalized%60%20is%20called,Value%20const%26%20value)

**Comment by hewison-chris** [comment]
I think if we sign after the externalize phase and the above event is called from the `SCPDriver` we are ok.

**Comment by ferencdg** [comment]
I think so too, but we still have to make sure we never again sign a block at the same block height(for example during catchup). As the block we signed during the externalize phase might not be the right block(if the node is befouled)

**Comment by hewison-chris** [comment]
> I think so too, but we still have to make sure we never again sign a block at the same block height(for example during catchup). As the block we signed during the externalize phase might not be the right block(if the node is befouled)

Yes I was also thinking about that. I think we might need to save to a file our `signature` for `block height` and read from this file on catchup so that we can not be tricked into signing a different `block hash` for the same height.

**Comment by hewison-chris** [comment]
There is still an edge case where we do a clean restart and then we have to trust catchup information from other nodes. Maybe we should not sign blocks in that scenario to be on the safe side.

**Comment by ferencdg** [comment]
The problem is that the validator should remember that he signed a block and never forget it. But what if 

1. I just copy my entire handrive with all the validator's data into a new computer (so it will not look like a fresh restart)
2. start validating on my old computer and got befouled and signed a block, later I switch off this computer
3. start my new computer that starts to catchup (doesn't look like a fresh restart), and sign a different block a the same height as I cannot remember what I signed.

**Comment by hewison-chris** [comment]
> The problem is that the validator should remember that he signed a block and never forget it. But what if
> 
> 1. I just copy my entire handrive with all the validator's data into a new computer (so it will not look like a fresh restart)
> 2. start validating on my old computer and got befouled and signed a block, later I switch off this computer
> 3. start my new computer that starts to catchup (doesn't look like a fresh restart), and sign a different block a the same height as I cannot remember what I signed.

Then the only safe thing is to not sign blocks during catchup in any scenario.

**Comment by ferencdg** [comment]
Yes, that is what I was thinking too.
