### ISSUE TITLE
Merge 'dns' and registries

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2256]
Currently our configuration allow to have a DNS seed, as well as registries.
This is a clear duplication of functionality, and they should most likely be merged.
Additionally, the registry currently only accept one address, and we might want to extend that as well as move it to another section so a full node can use it.

**Comment by Geod24** [comment]
In order for this issue to be fixed, we need:
- To be able to lookup a node from its key using our own DNS client (https://github.com/bosagora/agora/issues/2558)
- Our client needs to be recursive and caching, which probably can reuse work done on https://github.com/bosagora/agora/issues/2449;
- The registry needs to support `agora://`, `https://` and `http://` scheme, hence we need https://github.com/bosagora/agora/issues/2566

More infos in https://github.com/bosagora/agora/pull/2516

**Comment by Geod24** [comment]
Note that https://github.com/bosagora/agora/issues/2320 is also closely related.

**Comment by hewison-chris** [comment]
@mkykadir : Can we add here why this is blocked?

**Comment by mkykadir** [comment]
@hewison-chris 

Currently `dns` field in config is used as a seed value; after #2874 is resolved we can remove it and resolve this issue. I don't think this issue should present in the Sprint before resolving the other issue.
