### ISSUE TITLE
Quorum threshold is set in the wrong way, or is it?

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2262]
I am a bit baffled by this quorum threshold setting:

https://github.com/bosagora/agora/blob/2900db893d82ccaa9016ad834ffb0fe8052ef1ef/source/agora/consensus/Quorum.d#L116

the bigger the quorum, the bigger the threshold we set. But the more validators are in the quorum it is less likely they will all work correcly/are online. Also the more validators are in a quorum, the less likely that the nodes become befouled, so I would have expected the threshold to be lowered.

Isn't this should be the other way? Like if we have 4+ validators in a quorum, then the threshold should be let's say 50%. If there are 7 validators in a quorum, then it should be enough for 4 validators to convince an other validator.

if there are less than or equaly than 4 validators in a quorum, then we require the threshold to be 75%. So if we have exactly 4 validators, then we need 3 validators to convince an other validator.

This looks like the safer solution.

**Comment by hewison-chris** [comment]
I think `params.QuorumThreshold` is a percentage and the `quorum.threshold` here is the number of validators in a quorum that need to confirm the block for that quorum to agree consensus. That is why the number is bigger when there are more nodes.

**Comment by ferencdg** [comment]
ugh you are right, I see in SCP it is not pct, but the actual node count
