### ISSUE TITLE
Investigate slow responses to stats query

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2266]
On the live system, we're seeing the following behavior when nodes reach their maximum height (currently 1999):
<img width="1606" alt="Screen Shot 2021-07-13 at 11 59 28" src="https://user-images.githubusercontent.com/2180215/125383148-ed124680-e3d1-11eb-87a7-9b2d671e4999.png">

The red line represent the alert firing, the green represents it recovering.
We get 'Instance availability alert'(s) because we are frequently (but not regularly) missing some stats for nodes.
This only happen when they reach their max height and get stuck. Those nodes do not crash, they are simply very slow to respond to request on their stats endpoint, leading to Prometheus timing out.
We've seen the same issue happening before, and it's only visible now because of another issue, but should be investigated.

**Comment by ferencdg** [comment]
isn't this the never ending nomination and constant transaction validation that starves the CPU?

**Comment by omerfirmak** [comment]
> 
> 
> isn't this the never ending nomination and constant transaction validation that starves the CPU?

Wasnt that fixed?

**Comment by omerfirmak** [comment]
I feel like this is the root cause of this issue

```/receive_preimage 46 ms, 738 μs, and 6 hnsecs```

Our `/receive_preimage` endpoint runs for up to 50ms and when network reaches the maximum height, nodes constantly try to reveal new preimages. Once enough requests queue up, it can block the node for hunderds of milliseconds.

Sad part is that almost all of that time is spent in `vibe.d` code.

**Comment by omerfirmak** [comment]
Parsing a simple `PreImageInfo` from Json takes 40-50ms. Very cool

**Comment by Geod24** [comment]
How??

**Comment by omerfirmak** [comment]
What I am seeing might be the network delay, but still. I'll do some further digging.

**Comment by Geod24** [comment]
Not an issue anymore, most likely was due to the gossip bomb.
