### ISSUE TITLE
The administration page does not open in the docker environment.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#2267]
I used a configuration file `config-single.yaml`.
I executed the docker container using the following command.
```
docker run -p 127.0.0.1:2826:2826/tcp -p 127.0.0.1:2827:2827/tcp -v `pwd`/devel/:/agora/etc/ agora -c etc/config-single.yaml
```

When entering the URL (http://localhost:2827/) in the browser, the following results were obtained.

```
404 - Not Found

Not Found

Internal error information:
No routes match path '/'
```

I checked that the file exists in the folder '/usr/share/agora/talos/' in the docker image.

This is log 
```
No response written for /
No response written for /favicon.ico
```

**Comment by Geod24** [comment]
What were you trying to do ? Talos is the initialization interface, only available when using `--initialize=$ADDR`.
But if you use `--initialize`, you wouldn't use a specific config.

**Comment by Geod24** [comment]
I believe this is solved through offline discussions.
