### ISSUE TITLE
Double spending is possible

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2278]
I might be wrong, as I didn't reproduce the problem, but just by looking at the code, it seems double spend by an attacker is possible.

Current Agora transaction pool can store multiple double spend transaction and a well-behaving node running our Agora code would only include 1 of those double spend transaction into the ConsensusData during voting. However I see no protection at all agains an attacker who choose to include a double spend transaction. It seems there is no check neither in validateConsensusData during nomination nor in isInvalidReason during block addition. 

To make things even worse, UTXOCache.updateUTXOCache seems to add every double spend transaction to the UTXO cache, making double spend attacks possible, but correct me if I am misreading the code.

**Comment by Geod24** [comment]
Just reading the code, I don't see how that'd be possible.
In the ConsensusData validation, we call this:
https://github.com/bosagora/agora/blob/a9018c440550e464ae6154e03936decc47a5e7b1/source/agora/node/Ledger.d#L647-L648

Which then call this:
https://github.com/bosagora/agora/blob/a9018c440550e464ae6154e03936decc47a5e7b1/source/agora/node/Ledger.d#L1125-L1127

The method use an UTXO finder which memorizes the transactions that have been looked up:
https://github.com/bosagora/agora/blob/a9018c440550e464ae6154e03936decc47a5e7b1/source/agora/consensus/state/UTXOCache.d#L146-L150

So the check is in `isInvalidReason`.

> To make things even worse, UTXOCache.updateUTXOCache seems to add every double spend transaction to the UTXO cache, making double spend attacks possible, but correct me if I am misreading the code.

Indeed, the UTXOCache doesn't have any protection, but the assumption is that the consensus protocol has validated it before.

**Comment by ferencdg** [comment]
right, I wouldn't have expected UTXO 'finder' to memozie used utxos during 'finding', so didn't check
