### ISSUE TITLE
The endpoint on the administrator page of a remotely installed node is vulnerable to security.

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#2283]
The administrator page contains two endpoints that provide QR codes.
If a node is remotely installed and the user access it from a local PC using a browser, everyone can access it.
Therefore, the two endpoints on the administrator page must be modified so that only authorized people can access them.
The two endpoints are as follows.
/admin/login_qr
/admin/encryption_key_qr
 ex) /admin/encryption_key_qr?app=VOTERA&height=100

**Comment by Geod24** [comment]
What is your suggestion here ? Currently there is no support for authentication, and the current guideline would be to bind it to a VPN interface. But I agree that's not the most user-friendly setup.

**Comment by MichaelKim20** [comment]
End-users may not be aware that endpoints can be exposed. It would also be better to convey a solution or clear usage guidelines for this part early on because it may not know what the consequences will be when it is exposed and abused.

**Comment by Geod24** [comment]
I suppose the easiest way to address this would be via HTTP Basic Auth. That should be fairly straightforward to implement, and as long as SSL is used, secure. Do you have any other suggestion ?
