### ISSUE TITLE
Misusing Schnorr signatures causes leakage of the Validator's private key

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2284]
![image](https://user-images.githubusercontent.com/19815616/126098869-0b52ef74-6de5-44f5-a888-d61fc51485b3.png)

An attacker can easily calculate any validator's private key by 

1. observing signatures on any 2 blocks from the same validator during the 1008 block enrollment cycle AND
2. observing preimages on the same 2 blocks AND
3. observing the block hashes on the same 2 blocks

All those information above are publicly available to anyone.
After observing those information, the following 2 modular equations can be created:

s<sub>10</sub> = rc + p<sub>10</sub> + (c<sub>10</sub>*v)
s<sub>11</sub> = rc + p<sub>11</sub> + (c<sub>11</sub>*v)

s<sub>10</sub> = signature on block at height 10
p<sub>10</sub> = preimage for block at height 10
c<sub>10</sub> = block hash for block at height 10
v = private key
rc = unknown constant for the 1008 block enrollment cycle

those 2 equations can be solved for rc and v

here is a D problem to demostrate

```D
unittest
{
    import agora.consensus.data.genesis.Test: GenesisBlock;
    import agora.crypto.ECC: Scalar, Point;
    import agora.crypto.Schnorr;
    import agora.utils.Test;
    import std.format;
    Hash random_seed1 = "seed10".hashFull();
    Hash random_seed2 = "seed11".hashFull();
    Hash preimage10 = "preimage10".hashFull();
    Hash preimage11 = "preimage11".hashFull();
    const TimeOffset = 1;
    const Validators = genesis_validator_keys.length;
    // Generate two blocks
    auto block10 = GenesisBlock.makeNewBlock(
        genesisSpendable().take(1).map!(txb => txb.sign()), TimeOffset, random_seed1, Validators);
    auto block11 = block10.makeNewBlock(
        genesisSpendable().take(1).map!(txb => txb.sign()), TimeOffset, random_seed2, Validators);
    Scalar v = genesis_validator_keys[0].secret;
    assert(v.isValid(), "v is not a valid Scalar!");
    Point V = v.toPoint();
    const Scalar rc = Scalar(hashMulti(v, "consensus.signature.noise", 0));
    const Scalar r10 = rc + Scalar(preimage10);
    const Point R10 = r10.toPoint();
    const Scalar r11 = rc + Scalar(preimage11);
    const Point R11 = r11.toPoint();
    // Two messages
    Scalar c10 = block10.hashFull();
    Scalar c11 = block11.hashFull();
    assert(c10 != c11);
    Signature sig10 = block10.header.createBlockSignature(v, preimage10);
    Signature sig11 = block11.header.createBlockSignature(v, preimage11);
    // Verify signatures
    assert(verify(sig10, c10, V));
    assert(verify(sig11, c11, V));
    // Calculate the private key
    // v = (s10 - s11 + p11 - p10) / (c10 - c11)
    Scalar inverseBlockDiff = c10 - c11;
    inverseBlockDiff = inverseBlockDiff.invert();
    Scalar private_key_calculated = (sig10.s - sig11.s + Scalar(preimage11) - Scalar(preimage10)) * inverseBlockDiff;
    assert(private_key_calculated == v,
        format!"Key %s is not matching key %s"
        (private_key_calculated.toString(PrintMode.Clear), v.toString(PrintMode.Clear)));
}
```

**Comment by ferencdg** [comment]
The suggested solution to this is that each validator should commit to 1008 public random numbers during the enrollment. The secret random numbers corresponding to the commited public random numbers can be generated by h(v, "blocksig", height)

Those public numbers should be part of our block headers, but after validaton of the block signature, light clients might choose to discard those commited random numbers to save space and memory. This is similar how seggregated witnesses are discarded in Bitcoin after validation.

**Comment by hewison-chris** [comment]
The test looks valid. Good find. 
However, I think the best solution might be to use a new secret (never shared) for the noise of each block and go back to passing `(R, s)` instead of just `s`. This will prevent the ability to subtract away the repeated unknown as shown in your test.
The combined signature is then `(R1 + R2 + ... , s1 + s2 + ...)` and can be validated also without storing each individual `R`.

**Comment by ferencdg** [comment]
> The test looks valid. Good find.
> However, I think the best solution might be to use a new secret (never shared) for the noise of each block and go back to passing `(R, s)` instead of just `s`. This will prevent the ability to subtract away the repeated unknown as shown in your test.
> The combined signature is then `(R1 + R2 + ... , s1 + s2 + ...)` and can be validated also without storing each individual `R`.

I was suggesting storing the R1, R2 in the header, so we can punish validators signing the same block twice (they are commited to R1, R2), otherwise your solution and mine is the same, and I aggree that generating new random number(maybe by using h(v, "blocksig", height), but not necesseraly as we have them stored in the header during enrollment) is the correct way.

**Comment by ferencdg** [comment]
> > The test looks valid. Good find.
> > However, I think the best solution might be to use a new secret (never shared) for the noise of each block and go back to passing `(R, s)` instead of just `s`. This will prevent the ability to subtract away the repeated unknown as shown in your test.
> > The combined signature is then `(R1 + R2 + ... , s1 + s2 + ...)` and can be validated also without storing each individual `R`.
> 
> I was suggesting storing the R1, R2 in the header, so we can punish validators signing the same block twice (they are commited to use R1, R2...), otherwise our solution and mine is the same.

**Comment by Geod24** [comment]
The test case is valid and it's an issue. I am looking into ways to tweak the algorithm so that the issue can be fixed without adding more data.

For reference, a key property of the `R` derivation is that it makes the signature protocol non-interactive. Remember that for the Schnorr multisig scheme to work, all validators must sign using the same `R`, which in typical scheme requires a setup phase.

**Comment by hewison-chris** [comment]
~This attack can be prevented by multiplying the secret commitment made when enrolling by the pre-image rather than adding them together.~
