### ISSUE TITLE
Name registry should have persistence

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2290]
Currently, restarting the name registry means loosing all data.

**Comment by ferencdg** [comment]
validators periodically re-register though, maybe in every 30 secs cannot remember exactly

**Comment by Geod24** [comment]
Yes, but it's up to the validator implementation to do it. Persistence is a pretty basic feature we should definitely provide.

**Comment by ferencdg** [comment]
Sure I can add new persistence support, my plan was to add it when it is really necessary. Otherwise I could have added feautres like indexing too :)
