### ISSUE TITLE
Agora eventually get stuck when using SSL

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2293]
This seems to be an issue with Vibe.d.

```
Jul 19 13:49:59 eu-002 docker[4032574]: HTTP connection handler has thrown: Accepting SSL tunnel returned an error: non-recoverable socket I/O error: 11 (Resource temporarily unavailable)
```

Looking at the code where the error is triggered:
> https://github.com/vibe-d/vibe.d/blob/1f830a8241041c39c61bbdcde37fe4bc40c13432/tls/vibe/stream/openssl.d#L464-L473
> https://github.com/vibe-d/vibe.d/blob/1f830a8241041c39c61bbdcde37fe4bc40c13432/tls/vibe/stream/openssl.d#L262

The man says:
> If the underlying BIO is non-blocking, SSL_accept() will also return when the underlying BIO could not satisfy the needs of SSL_accept() to continue the handshake, indicating the problem by the return value -1. In this case a call to SSL_get_error() with the return value of SSL_accept() will yield SSL_ERROR_WANT_READ or SSL_ERROR_WANT_WRITE

And I didn't see any handling for those.

From @omerfirmak :
> I don't think vibed is calling `SSL_shutdown` properly.
> https://github.com/vibe-d/vibe.d/blob/1f830a8241041c39c61bbdcde37fe4bc40c13432/tls/vibe/stream/openssl.d#L278
> ```
> Jul 19 13:49:59 eu-002 docker[4032574]: HTTP connection handler has thrown: Accepting SSL tunnel returned an error: non-recoverable socket I/O error: 11 (Resource temporarily unavailable)
> ```
> i think this was the first  time it errored yesterday, so our sockets are non-blocking
> but openssl can still return `SSL_ERROR_SYSCALL` for an `EAGAIN`
> ```
> SSL_ERROR_SYSCALL
>    Some non-recoverable, fatal I/O error occurred. The OpenSSL error queue may contain more information on the error. For socket I/O on Unix systems, consult errno for details. If this error occurs then no further I/O operations should be performed on the connection and SSL_shutdown() must not be called.
>    This value can also be returned for other errors, check the error queue for details.
> ```

**Comment by omerfirmak** [comment]
Client's side of the story.
```
Jul 26 11:32:59 eu-002 docker[648301]: --------------------
Jul 26 11:32:59 eu-002 docker[648301]: HTTP client request:
Jul 26 11:32:59 eu-002 docker[648301]: --------------------
Jul 26 11:32:59 eu-002 docker[648301]: POST /handshake HTTP/1.1
Jul 26 11:32:59 eu-002 docker[648301]: User-Agent: vibe.d/1.17.1 (HTTPClient, +http://vibed.org/)
Jul 26 11:32:59 eu-002 docker[648301]: Connection: keep-alive
Jul 26 11:32:59 eu-002 docker[648301]: Accept-Encoding: gzip, deflate
Jul 26 11:32:59 eu-002 docker[648301]: Host: na-001.bosagora.io:4826
Jul 26 11:32:59 eu-002 docker[648301]: Accept: application/json
Jul 26 11:32:59 eu-002 docker[648301]: Content-Type: application/json; charset=UTF-8
Jul 26 11:32:59 eu-002 docker[648301]: Content-Length: 78
Jul 26 11:32:59 eu-002 docker[648301]: --------------------
Jul 26 11:32:59 eu-002 docker[648301]: HTTP client waiting for response
Jul 26 11:32:59 eu-002 docker[648301]: OpenSSL error at submodules/vibe.d/tls/vibe/stream/openssl.d:1315: error:80000001:lib(128):func(0):reason(1) (Error reading from underlying stream: Read operation timed out)
Jul 26 11:32:59 eu-002 docker[648301]: 2021-07-26 11:32:59,888 Trace [agora.network.Client.boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8] - Request 'getNodeInfo' to https://na-001.bosagora.io:5826 failed: Connecting TLS tunnel: error:80000001:lib(128):func(0):reason(1) (2147483649)```

**Comment by omerfirmak** [comment]
I've failed to reproduce this and manual code review didn't ring any bells. Marking this as blocked for the time being, I will revisit it after tackling some other issues to reset.

**Comment by Geod24** [comment]
```
2021-08-02 13:42:56,149 Trace [agora.network.Client.boa1xrval7gwhjz4k9raqukcnv2n4rl4fxt74m2y9eay6l5mqdf4gntnzhhscrh] -
Request 'getNodeInfo' to https://na-002.bosagora.io:7826 failed: Peeking TLS stream: error:80000001:lib(128):func(0):reason(1) (2147483649)
2021-08-02 13:42:56,156 Trace [agora.network.Client.boa1xrval6hd8szdektyz69fnqjwqfejhu4rvrpwlahh9rhaazzpvs5g6lh34l5] - Request 'receivePreimage' to https://na-002.bosagora.io:6826 failed: Peeking TLS stream: error:80000001:lib(128):func(0
):reason(1) (2147483649)
2021-08-02 13:42:58,233 Trace [boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8] - Received Preimage: { utxo: 0x3b44...ba77, hash: 0xfdd2...31a1, height: { value: 8297 } }
2021-08-02 13:42:58,809 Trace [boa1xrval5rzmma29zh4aqgv3mvcarhwa0w8rgthy3l9vaj3fywf9894ycmjkm8] - Received Preimage: { utxo: 0x7bac...ea8f, hash: 0x1b8f...7254, height: { value: 8297 } }
2021-08-02 13:42:59,337 Trace [agora.network.Client.boa1xrval7gwhjz4k9raqukcnv2n4rl4fxt74m2y9eay6l5mqdf4gntnzhhscrh] -
Request 'receivePreimage' to https://na-002.bosagora.io:7826 failed: Connecting TLS tunnel: error:80000001:lib(128):func(0):reason(1) (2147483649)
2021-08-02 13:43:00,654 Trace [agora.network.Client.boa1xrval7gwhjz4k9raqukcnv2n4rl4fxt74m2y9eay6l5mqdf4gntnzhhscrh] - Request 'getNodeInfo' to https://na-002.bosagora.io:7826 failed: Connecting TLS tunnel: error:80000001:lib(128):func(0):reason(1) (2147483649)
2021-08-02 13:43:00,661 Trace [agora.network.Client.boa1xrval6hd8szdektyz69fnqjwqfejhu4rvrpwlahh9rhaazzpvs5g6lh34l5] - Request 'receivePreimage' to https://na-002.bosagora.io:6826 failed: Connecting TLS tunnel: error:80000001:lib(128):fun
c(0):reason(1) (2147483649)
```

**Comment by Geod24** [comment]
~Looks like the node crashed twice then was stuck when it came back up.~
EDIT: That's wrong too, the whole server crashed.
 ~Could it be related to SO_REUSEPORT ?~ No we run in a container.

**Comment by Geod24** [comment]
Found https://github.com/vibe-d/vibe.d/pull/2589 while looking into another issue.

**Comment by Geod24** [comment]
This was probably because of #2387 . We don't have the issue anymore.
