### ISSUE TITLE
Leaking validator's private key caused by signature catchup

### ISSUE THREAD

**Issue by ferencdg** [bosagora/agora#2299]
this is a spinoff from issue https://github.com/bosagora/agora/issues/2251

issue #2251 was only about signing multiple ballot messages at the same height, but during a conversation with Chris, it seems private key leak can happen during signature catchup too:
https://github.com/bosagora/agora/issues/2251#issuecomment-878044494

there are some solutions suggested on the original ticket:
1. try to remember what a validator signed during balloting (potential problem might be: https://github.com/bosagora/agora/issues/2251#issuecomment-878064165)
2. remove signature catchup (potential problem is that it might decrease the total signature count on blocks)

**Comment by hewison-chris** [comment]
[PR2270](https://github.com/bosagora/agora/pull/2270) for issue #2251 has option 2 implemented in first commit. I can extract it out into a new PR and link to this issue if you like.

**Comment by ferencdg** [comment]
I think no need to extract, I think we can just reference that your PR solves this issue too with fixes: #2299
