### ISSUE TITLE
DMD bug: Array comparison mismatch for `immutable[]` vs `[]`

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#232]
See https://github.com/bpfkorea/agora/blob/9d2c958fc34f8cd4fcd3d4ef95e28b62aa8f4f36/source/agora/common/Deserializer.d#L114-L131

**Comment by Geod24** [comment]
Now that we have a deserializer that is capable to deserialize to `const`/`immutable` it is less of an issue, but should still be reported upstream.

**Comment by Geod24** [comment]
@AndrejMitrovic : Do we have a tracker ID for this ?

**Comment by AndrejMitrovic** [comment]
I'm not sure I ever filed this one. But it's got to be a known bug somewhere..

**Comment by Geod24** [comment]
This needs to get merged into #561 once we get a tracker ID.

**Comment by Geod24** [comment]
Got it: https://issues.dlang.org/show_bug.cgi?id=21012
Moving to #561
