### ISSUE TITLE
Possible OB1 error with SCP Logger

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2338]
Tested with https://github.com/bosagora/agora/commit/d7d44f752b83762abaed02b0620563562582c947
<img width="739" alt="Screen Shot 2021-07-29 at 16 56 43" src="https://user-images.githubusercontent.com/2180215/127454015-15638a91-13da-4997-940f-2b59c715ede7.png">

**Comment by kchulj** [comment]
What is that in line 6?

**Comment by Geod24** [comment]
Looks like we get garbage on the C++ side already:
```diff
diff --git a/source/scpp/src/util/Logging.cpp b/source/scpp/src/util/Logging.cpp
index 57fa6f4f5..2516c703b 100644
--- a/source/scpp/src/util/Logging.cpp
+++ b/source/scpp/src/util/Logging.cpp
@@ -19,6 +19,8 @@ DLogger::DLogger(int level, std::string const& loggerName)

 DLogger::~DLogger()
 {
-    agora::writeDLog(mLoggerName.c_str(), mLevel, mOutStream.str().c_str());
+    auto str = mOutStream.str();
+    std::cout << "From C++: " << str << std::endl;
+    agora::writeDLog(mLoggerName.c_str(), mLevel, str.c_str());
 }
 }
```

<img width="834" alt="Screen Shot 2021-07-30 at 15 46 34" src="https://user-images.githubusercontent.com/2180215/127612409-ce4dd102-5a8e-4971-b1da-3fcbcb0e455c.png">

**Comment by linked0** [comment]
We might have to have a constructor having the following code.
```
mOutStream.str("");
mOutStream.clear();
```

**Comment by Geod24** [comment]
From the look of it, I might have bungled `toStrKey`:
https://github.com/bosagora/agora/commit/10ca6285367ae9ed7b08c3d19f625f44e49998a9
