### ISSUE TITLE
Simplified Payment Verification (SPV)

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#239]
As a user, I want to be able to verify payment from a "simple device", such as a phone, without relying on having to download the full blockchain state and validate everything.

This will be addressed by making a block verifiable, then providing a Merkle Path within this block.

**Comment by Geod24** [comment]
CC @MichaelKim20 @TrustHenry : Since we have both Merkle path verification and block signature, I think all that is needed is the implementation on your side. When do you think you can get to it ?

**Comment by Geod24** [comment]
So questions that this bring:
- Does Stoa have the required APIs for us ? Currently we have the API in Agora, but we want clients to interact with Stoa.
- Does Stoa expose a way to only get the block header ?
- What policy do we apply in the client for block header retention ?
- How much consensus rules can we and should we check in the client (most important question) ?
- Provided an implementation that does periodic polling on a hash, how much story point would an implementation be ?
