### ISSUE TITLE
NetUtils' `getAllIPs` returns an empty array on the servers

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2395]
Tested on the server as part of #2392 , I got an empty array. This might be due to Agora running in Docker though.
One solution would be to integrate https://github.com/Kripth/my-ip .
This is a blocker for the deployment of TestNet.

**Comment by mkykadir** [comment]
I've tested this on our test servers and it works, but on my computer (under WSL2) it returns an empty array.
