### ISSUE TITLE
Genesis block/validator creation

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#241]
As a developer, I need a genesis block and an initial validator set in order to build a chain.

**Definition of Done:**
- [x] The genesis transaction is hardcoded
- [x] There is at least one freezing transaction in genesis
- [ ] The private key of the freezing transaction is controlled by the foundation

**Comment by Geod24** [comment]
This is now more of a generic "CoinNet deployment checklist" since only coming up with the private key is left, so it's not worth its own issue. The other two points have been addressed.
