### ISSUE TITLE
Registry: Implement secondary zones

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2449]
A registry should be able to be non-authoritative, however we need to see how this is best implemented, especially taking https://github.com/bosagora/agora/pull/2443 into account.

**Comment by Geod24** [comment]
Dome useful links:
- https://datatracker.ietf.org/doc/html/rfc1035#section-3.2.1
- https://datatracker.ietf.org/doc/html/rfc1035#section-6.1.3

**Comment by mkykadir** [comment]
Secondary type will enable us to provide backups and reducing load on registry nodes. Caching type can be implemented with a new issue (non-authoritative).
