### ISSUE TITLE
Define and implement rules for transaction replacement

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#245]
Transaction replacement is what happens when a new transaction is received that compete with  another transaction in the MemPool.
In this case, some design could allow the transaction with higher fees to win.
We need to come up with our rule on this. Initially we will allow a replacement fee to occur if the fee is 20% higher than the previous one, rounded up to the next digit.

**Comment by AndrejMitrovic** [comment]
I believe this might be possible to implement in parallel or before https://github.com/bpfkorea/agora/issues/1435, but the two are highly correlated.

**Comment by Geod24** [comment]
I think we should keep it simple: Allow replacement if the fee is 20% higher than the previous one, rounded up to the next digit.

**Comment by Geod24** [comment]
The rules have been defined and passed to the foundation, the implementation is pending.

**Comment by ferencdg** [comment]
I was thinking about why this simple transaction replacement will not work. The simple transaction replacement would just replace the conflicting transaction, if the fee is 20% or more and **forget** the original transaction. However what happens if

transactions X,Y,Z use the same input:

Node A:
receives transaction X with fee 1.99
receives transaction Y(conflicting with X) with fee 2 -> Y will be discarded

Node B:
receives transaction Y with fee 2
receives transaction X(conflicting with Y) with fee 1.99 -> X will be discarded

Node A will only remember transaction X, while Node B will only remember transaction Y.

We also doesn't query other nodes for unknown transaction during a candidate check, those unknown transactions are retrieved independently of the candidate checks.

In a more complex case it might happen that 
1/3 of nodes have transaction X(fee 1.98)
1/3 of nodes have transaction Y(fee 1.99)
1/3 of nodes have transaction Z(fee 2.00)

and they will never reach consensus.

------
if you have to remember all transactions, then the attackers can DoS Agora regardless of this arbitrary 20% rule(which was supposed to save us from DoS).

**Comment by ferencdg** [comment]
how about this instead? 

1. If a node receives a transaction and it conflicts with an other transaction, it will **gossip** the new transaction only if the fee is 20% higher than the existing one.
2. If a node receives a transaction and it conflicts and has a higher fee than the existing transaction(doesn't have to be 20% higher, just simply higher), then it replaces it.
3. If a node receives a candidate which has an unknown transaction, it will ask its neighbours.
3.1 the unknown transaction has a fee smaller than the transaction we know -> we will never add it to the transaction pool
3.2 the unknown transaction has a fee higher than the transaction we know -> we will add it to the transaction pool(we will not gossip regardless of how much higher)

**Comment by omerfirmak** [comment]
> I was thinking about why this simple transaction replacement will not work. The simple transaction replacement would just replace the conflicting transaction, if the fee is 20% or more and **forget** the original transaction. However what happens if
> 
> transactions X,Y,Z use the same input:
> 
> Node A:
> receives transaction X with fee 1.99
> receives transaction Y(conflicting with X) with fee 2 -> Y will be discarded
> 
> Node B:
> receives transaction Y with fee 2
> receives transaction X(conflicting with Y) with fee 1.99 -> X will be discarded
> 
> Node A will only remember transaction X, while Node B will only remember transaction Y.
> 
> We also doesn't query other nodes for unknown transaction during a candidate check, those unknown transactions are retrieved independently of the candidate checks.
> 
> In a more complex case it might happen that
> 1/3 of nodes have transaction X(fee 1.98)
> 1/3 of nodes have transaction Y(fee 1.99)
> 1/3 of nodes have transaction Z(fee 2.00)
> 
> and they will never reach consensus.
> 
> if you have to remember all transactions, then the attackers can DoS Agora regardless of this arbitrary 20% rule(which was supposed to save us from DoS).

IIRC, currently `TransactionPool` accepts double-spend TXs. So we should not discard a transaction that is using the same inputs but add it to the pool regardless of the fee it includes. Transaction replacement should come in at the time of nominating, not before. Validator should pick the best candidate and nominate that one.

To be fair, `TranscationPool` should probably have a upper limit of how many double-spent TXs it accepts.

See https://github.com/bosagora/agora/blob/bcd14f2c6a3616d7f05ef850dc95fae3eb386760/source/agora/node/TransactionPool.d#L727-L795

**Comment by ferencdg** [comment]
> To be fair, `TranscationPool` should probably have a upper limit of how many double-spent TXs it accepts.

I think we should discard the double spend transaction with lower fees and keep let's say the 100 double spend TX with the **highest** fees, instead of the 100 **oldest** transactions: just to avoid the situation when an attacker send 3 distinct groups of 100 transactions to 3 groups of validators and those 3 groups of validators would never agree.

What do you think?

**Comment by ferencdg** [comment]
I still don't get though what the original idea with the 20% fee was(it might just be an old ticket). Should we only gossip double spend transactions whos fee is at least 20% higher than our highest fee double spend transaction?

**Comment by omerfirmak** [comment]
> > To be fair, `TranscationPool` should probably have a upper limit of how many double-spent TXs it accepts.
> 
> I think we should discard the double spend transaction with lower fees and keep let's say the 100 double spend TX with the **highest** fees, instead of the 100 **oldest** transactions: just to avoid the situation when an attacker send 3 distinct groups of 100 transactions to 3 groups of validators and those 3 groups of validators would never agree.
> 
> What do you think?

Sounds perfectly reasonable to me.

**Comment by ferencdg** [comment]
after talking to Omer, here is the new suggestion of how this should work

1. If a node receives a transaction and it conflicts with an other transaction, it will gossip the new transaction only if the fee is 20% higher than the existing one.

2. If a node receives a transaction and it conflicts and has a 20% higher fee than the existing transaction, then it adds that transaction to the transaction pool.

3. If a node receives an envelope with a candidate in it and the candidate has an unknown transaction, it will ask its neighbours about that transaction. Regardless how big or small the fee is, we will add the transaction to the transaction pool.

4. Each node should propose the double spend transaction with the highest fee, and if there are multiple one with the same fee, then the one with the smallest hash.

possible attack:
Attacker would connect to 10.000 nodes and send the 10.000 different double spend transaction with the SAME fee
a. every node would store only 1 of those transactions in the transaction pool, so it would not blow up thanks to point 2 above.
b. the network would not be overwhelmed thanks to point 1
c. the consensus would not be stuck thanks to point 3.
d. point 4 should reduce the time to reach the consensus and also make this kind of attack expensive

There is a small risk of point 3 triggering the transaction pool to grow to big, but the consensus algoritm would probably finish before that even happens. Alternatively we could put a limit on the number of double spend transactions in the transaction pool, but then we would risk the consensus algoritm to be stuck or delayed for a very long time(thanks to newly arrived transactions evicting existing ones)

Apart from the above we would also need at some point to implement some algorithm to slow down propagating 'penny' transactions, the same way bitcoin does.

let me know if you would like to see any change

**Comment by MichaelKim20** [comment]
@Geod24 What is the plan to implement Agora's transaction cancellation function?
I asked a question because Wallet included a cancellation function.
