### ISSUE TITLE
Allow smooth transition from TokenNet to CoinNet for service providers (e.g. exchanges)

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#252]
Currently we have a bunch of "service providers" which are already integrated with TokenNet, e.g. a few exchanges, CoinMarketCap, and other reputation tools. Moving away from TokenNet and the well supported ERC20 infrastructure means a lot of integration work, some of which should be completed before we flip the switch.

Some of this will be handled by the API server we are currently (2020-07-01) developing.

Tags: token migration

**Comment by Geod24** [comment]
We have made a plan for this internally.
