### ISSUE TITLE
Registry: Relax rules to allow valid stakes to register

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2524]
Currently, only enrolled validators may register. However, this means that nodes are not immediately reachable when they enroll, and there is a delay in between the moment a block is externalized and nodes can get an address to contact those new peers.
If the block interval is too low, or one's retry delay too high, it means a node might miss one or more consensus rounds.

**Comment by omerfirmak** [comment]
Assigning this to myself to be done in this sprint.
