### ISSUE TITLE
Deploy monitoring tools

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#255]
Once we have publicly deployed nodes in place (#249), we will need to put in place tools to monitor that everything works correctly. Things like [Grafana](https://grafana.com/) will allow us to monitor metrics such as (those are examples):
- Machine metrics: memory & CPU usage, network bandwidth, ...;
- General node health status: Transaction pool size, disk errors, rejected transactions...
- General blockchain health data: Deviation from the expected time for blocks, average time from pool to block, etc...

Some  example of what others do:
- https://www.lopp.net/bitcoin-information/statistics-metrics.html
- https://bitnodes.io/
- https://ethernodes.org/
- https://ethstats.net/

**Comment by Geod24** [comment]
We have most of that covered, and whatever's left should be opened as a separate issue in infrastructure.
