### ISSUE TITLE
Block Validation should check the presence of a slashing transaction

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2554]
Currently, when a node is slashed, we do not check if there is a slashing transaction in the block, we just consider them slashed because we might have externalized the block.

https://github.com/bosagora/agora/pull/2552/files#r721920118

**Comment by omerfirmak** [comment]
I dont think we have the slashing TX in the block. We just update the UTXO set.

https://github.com/bosagora/agora/blob/9ecdd8af6626cf354bd358426b6d8284fe44c522/source/agora/consensus/Ledger.d#L508-L517

We cant really create a valid TX that can spend the validator stake, right? There is no way we can sign the input.
This brings up the question of how the outputs of the slashing TX we use here could be used, with no record of them in the blockchain.

**Comment by omerfirmak** [comment]
An idea;

We could make slashing penalty a part of the Coinbase TX. 

1. Validator pays the `SlashPenaltyAmount` as TX fee while freezing their stake.
2. Network withholds that amount until either the validator is no longer enrolled or is slashed.
3. If validator gets slashed, that amount will be included in the Commons Budget output of the next payout block.
4. If cycle ends Validator will be paid back in the next payout block.

If validator enrolls again with no gap in the enrollment, network will keep the `SlashPenaltyAmount` as collateral, so same UTXO can still be used.
