### ISSUE TITLE
Dedicated foundation nodes

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#256]
As a pre-requisite to deploy CoinNet, we will need to deploy some nodes operated by the Foundation.

Since those nodes will have access to a significant amount of BOA funds, they should each live in their own server.
Once we get a good enough view of the resource consumption of a BOA node (which TestNet will give us), we can estimate the hardware need for each node.

A few things:
- Those servers will most likely be Linux server;
- They will have full-disk encryption;
- They will be monitored by the monitoring tools ( #255 );
- The number of server is a policy decision to be taken by the Foundation: currently I'd say 6-8, but depends on the network;

**Comment by Geod24** [comment]
That's a DevOps task, so for me so far.

**Comment by Geod24** [comment]
We already have an operating environment, any future improvement can be broken down in its own task in the relevant repo.
