### ISSUE TITLE
Normalize URLs used through Agora

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2566]
Currently, we pass URL around as string, which can lead to issues such as #2498 .
We also have multiple type of interfaces, which means we need to instantiate a different client depending on the schema.

What we should do:
- Always use a unified (canonical) representation when we print URLs as string;
- Use a specific schema for the TCP connection, e.g. `agora://<domain>[:port]/`, where the default port is `2826`;
- Support `http` and `https` schema, and instantiate the client appropriately;
- Always emit the trailing slash;
- Only emit the port if it differs from the default port for the protocol (e.g. if we see `http://foo.bar:80` we normalize it to `http://foo.bar/`;

Any other things you can think of @mkykadir ?

**Comment by mkykadir** [comment]
Vibe's `URL` construction from plain URL string [only expects](https://github.com/vibe-d/vibe.d/issues/2618) percent encoded strings. We can still use Vibe's implementation by extending it to percent encoding URL's. I mostly expect plain URL strings from our configuration file. We should consider percent encoding for normalization process.

**Comment by Geod24** [comment]
Depends on https://github.com/vibe-d/vibe.d/pull/2627 and https://github.com/vibe-d/vibe.d/pull/2624
