### ISSUE TITLE
Fix "Could not listen to address" spurious message on startup

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2572]
![photo_2021-10-11_14-51-01](https://user-images.githubusercontent.com/2180215/136739547-2bd76756-53d5-4f12-b1dc-b28d08399385.jpg)

This triggers because Vibe.d automatically listens to "all interface" and so tries to listen to both `[::]:$PORT` and `0.0.0.0:$PORT`, and only one succeeds. The fix is most likely to provide the bind address explicitly.

**Comment by mkykadir** [comment]
This is the way how Vibe.d handles dual-stack, I believe. Dual-stack is on by default on Linux, thus providing `::` host would resolve the issue and socket is still accessible from `0.0.0.0`. But dual-stack is off for Windows by default, thus Vibe.d's method is required for IPv4 accesses. I don't know MacOS.
