### ISSUE TITLE
Nodes' `shutdown` functions crash when node is not completely `start`ed

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2596]
`scope(failure)`s may cause node's to shutdown and `shutdown` functions rely on successful `start`. Failure can be caused within node's `start` functions since they are not `nothrow` nor `@safe`. We can check for completeness of `start` in `shutdown` but making `start`  error proof might be easier.

**Comment by Geod24** [comment]
You mean this pattern we use in tests:
```D
network.start();
scope(exit) network.shutdown();
```

Because this will never call `shutdown` if `start` throws, so it might just be a lack of reporting from `start` ?

**Comment by mkykadir** [comment]
I've encountered with this issue once (during conversion of Address alias change), but cannot reproduce it now.

`Flash`'s `shutdown` was accessing `NULL` due to uninitialized `periodic_timer` . It seems like I caused an early return from `start`.
