### ISSUE TITLE
PROD test environment gets stuck sometimes at block heights for `Coinbase` payouts

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#2603]
Agora version v0.24.0 was deployed and first got stuck at block height 3743, this is the block before payout cycle 26.
After 3 days it started generating blocks until getting stuck again as payout cycle 69 was about to end at height 9935.

**Comment by hewison-chris** [comment]
PROD environment is stuck again at block 2303. 
As 2304 is 16th payout block there must still be something wrong with reaching consensus during the payout blocks.

**Comment by Geod24** [comment]
Fixed it seems!
