### ISSUE TITLE
Add rate limitation for non-validator nodes

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#262]

**Comment by Geod24** [comment]
Closing this in favor of the following two issues:
- Deploying Foundation nodes ( #256 ): For this, we could put an HAProxy or similar in front of the node to avoid (D)DoS.
- Inbound connection banning in Vibe.d ( #202 ): We currently have the BanManager, which is a good step towards fixing this issue. However we need to have handling at the connection level for this to be really useful in a real-world scenario.
