### ISSUE TITLE
Validator stake can be spent to prevent slash penalty

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#2622]
If someone spends their frozen stake and starts melting, we can no longer penalize them in case they get slashed.
This relates to #2597

**Comment by Geod24** [comment]
How would they get slashed if their stake is melting ? Only if we move it to CoinBase right ?

**Comment by omerfirmak** [comment]
> 
> 
> How would they get slashed if their stake is melting ? Only if we move it to CoinBase right ?

Yeah, we can't. #2597 prevents stake to be melted during the validation cycle.
