### ISSUE TITLE
Setup Windows build

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#264]
Setup a build process to have Agora compile and run tests on Windows (probably through Github actions). We should test at least DMD, and hopefully LDC as well.

DoD:
- [x] Agora is built and tested on Windows on each pull requests and push to `v0.x.x`

**Comment by Geod24** [comment]
So, more details about this:
1) We should definitely use Github actions
2) All the libraries we use are compatible with Windows, but most of the work will be on setting them up
3) We can add it on PR only as a first step (https://github.com/bpfkorea/agora/blob/v0.x.x/.github/workflows/github_pr.yml)

**Comment by Geod24** [comment]
Github actions documentation: https://help.github.com/en/actions
One of the issue you will face is that we use G++ to build our C++ code: https://github.com/bpfkorea/agora/blob/c7314c21700c526d6ee496090694bef46dc9da54/source/scpp/build.d#L51

**Comment by AndrejMitrovic** [comment]
Github might have a gcc compiler on Windows too (probably via MinGW). For example: https://github.com/onqtam/doctest/blob/875052e18cf5f5f0b9176e59f847b6205f3efb78/.github/workflows/main.yml#L46

**Comment by Geod24** [comment]
Done in #624

**Comment by Geod24** [comment]
Note: It is not tested on `push` currently, but that's a minor detail, and I will refactor the Github workflow so it is in the near future.
