### ISSUE TITLE
Node to node encryption

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#266]
As a user, I need all my node traffic to be sent encrypted in order to safeguard my privacy.

Currently, we have a single way to receive / exchange data: HTTP REST queries.
In the future, we want to move to a binary protocol, but should still be using SSL to transmit data.
Some method might still be exposed via REST and it should be over HTTPS.

**Comment by Geod24** [comment]
Probably based on the validator's key and https://libsodium.gitbook.io/doc/key_exchange
See #1897

**Comment by ferencdg** [comment]
would it be possible to have some of the enpoints configured as not encrypted? For example the crawler in #251 could be implemented in a much simpler/more efficient way if we had no encription on the FullNode.getNetworkInfo method. Also if we ever want to implement #1934, then encryptions would need to be optionally disabled.

**Comment by Geod24** [comment]
It probably needs to be its own interface then.
