### ISSUE TITLE
Move some system test to CircleCI

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#269]
As a developer, I need to offload some of the Travis work to CircleCI in order to be able to add more tests without waiting for too long.

**Comment by bpalaggi** [comment]
A good candidate would be system tests, as anything that touches Docker is inherently slow.

https://circleci.com/docs/2.0/building-docker-images/

**Comment by Geod24** [comment]
This is done

**Comment by Geod24** [comment]
- [x] https://github.com/bpfkorea/agora/pull/233
- [x] https://github.com/bpfkorea/agora/pull/284
- [x] https://github.com/bpfkorea/agora/pull/291
