### ISSUE TITLE
`Channel.onSettleTxExternalized` does not check the settlement transaction

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2704]
https://github.com/bosagora/agora/blob/b8b67a8548ee3b4d6699641b864f1f90964f396c/source/agora/flash/Channel.d#L829-L835

**Comment by omerfirmak** [comment]
That comment is probably outdated.

https://github.com/bosagora/agora/blob/b8b67a8548ee3b4d6699641b864f1f90964f396c/source/agora/flash/Channel.d#L1661-L1666 

The order we check for the special TXs is important as well, so checking if it is a settle TX in `onSettleTxExternalized` { only, as well } has no point imo.
