### ISSUE TITLE
Do we correctly handle receiving envelopes with a slot_idx > ledger block height + 1

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#2754]
what if `slot_idx >> height + 1`? then we are validating for a state that we dont know

_Originally posted by @omerfirmak in https://github.com/bosagora/agora/pull/2750#discussion_r772146405_

**Comment by hewison-chris** [comment]
I think we should consider if we handle this scenario correctly during nomination, not just limited to checking if half signed the last block.

**Comment by omerfirmak** [comment]
For some reference see https://github.com/bosagora/agora/pull/1495#discussion_r558036529

Particularly; 

```
That is indeed what Stellar does actually. They only return kMaybeValidValue here, which is the case where the value is fully validated but ledger is not fully caught up. https://github.com/stellar/stellar-core/blob/54b03f755ae5d5aa12a799c8f1ee4d87fc9d1a1d/src/herder/HerderSCPDriver.cpp#L237
```

**Comment by omerfirmak** [comment]
Done in #2760
