### ISSUE TITLE
Ledger should not accept any block if previous height was not signed by majority of validators

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#2772]
We do check if signatures of previous height have reached majority while validating nominated values, but same should be applied to the blocks we catch up on.

Additionally if the last block we have in storage was not signed by majority (which we allow thru externalization), we should still try to catch up on that height and if we get a block that was signed by majority, we should be able to replace the block in our storage.

A malicious node could sign multiple blocks at the same height, we should come up with a scheme that discourages or handles that scenario as well.

**Comment by Geod24** [comment]
> we should be able to replace the block in our storage.

I assume that part is not done yet ? Reverting changes made to the validator set and UTXO set is going to be very hard, isn't it ?

**Comment by omerfirmak** [comment]
Yeah that part is missing, I am hoping sqlite to have a snapshot-like feature so that we can easily revert all the changes. If not we will probably need to keep the an in-memory diff that last block would cause on the state and commit that to DB only when next block is externalized, which means the previous block reached majority sigs.

**Comment by hewison-chris** [comment]
After some discussion it has been decided to look into how to only externalize when a majority of block signatures have been collected. Maybe between the `ballot` phases of `prepare` and `commit` the signatures can be gossiped and the `commit` only `emitted` once the majority is reached. Then when the `externalize` happens the nodes can externalize with a block which has a majority.

**Comment by hewison-chris** [comment]
The solution implemented was to sign the block when the SCP `Externalize` single event occurs. The next nomination round then waits until the `pending block` has a majority of signatures and is written to the ledger (externalized).
