### ISSUE TITLE
SQLite errors are always logged from `TransactionPool`

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2822]
One example;

```
Error [agora.consensus.pool.Transaction] - SQLite error: (1) no such table:
```

also `TransactionPool` [makes generic SQLite configurations](https://github.com/bosagora/agora/blob/fbf7ad19ae6cf36d2c7fd93d096ef9a170fc800d/source/agora/consensus/pool/Transaction.d#L83) which should be moved somewhere else.

**Comment by Geod24** [comment]
I think we should just propagate the `Exception` here. I believe this should be fairly trivial to do ?

**Comment by mkykadir** [comment]
Exception is still propagated but an `Error` also gets logged even the point caused the exception might not want a log.

**Comment by Geod24** [comment]
Where does it come from ?

**Comment by mkykadir** [comment]
Currently no errors logged for that but #2703 will utilize the example error provided in this issue for configuration changes between registry types and gets `Error` logs during node initialization.
