### ISSUE TITLE
`ensure` doesn't print current stack trace always

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2864]
Sometimes `ensure` dumps previous `ensure`'s back trace, this sometimes happens between different `unittest`s within a module. Currently single instance of an `Exception` object [is used](https://github.com/bosagora/agora/blob/7fdff995445b6f1ba695fe9e46500c75f00f1eca/source/agora/common/Ensure.d#L26) within `ensure`. Even throwing new instance [here](https://github.com/bosagora/agora/blob/7fdff995445b6f1ba695fe9e46500c75f00f1eca/source/agora/common/Ensure.d#L111) resolves the issue, main idea was to avoid this allocation.

**Comment by Geod24** [comment]
Does it happen outside of unittests ?

**Comment by mkykadir** [comment]
> Does it happen outside of unittests ?

~I've only encountered with this during unittests.~ I've tried on a simple local project and it also happens during runtime.

**Comment by mkykadir** [comment]
https://github.com/dlang/druntime/blob/9ab527d064e236f1cb9b59d6592811c97c5d0c92/src/rt/deh.d#L43-L44

After first `ensure`,  `t.info is null` check is failing thus trace context is not updated. D is following DWARF style; I am checking if there is any limitation for this.

**Comment by mkykadir** [comment]
Created [this](https://github.com/dlang/druntime/pull/3742) for ^

**Comment by Geod24** [comment]
We can use the workaround for now tho.
