### ISSUE TITLE
Implement peer re-negotiation

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2868]
It is possible for one of our peers to change stake:
https://github.com/bosagora/agora/blob/14459dd88a04797457a51f6e793d8b827b8d2d91/source/agora/node/Validator.d#L337-L339

For example, in the following set of events:
- Node starts with a pubkey, registers as validator because of #2867 ;
- A stake is created, the node picks it up and try to enroll (if `recurring_enrollment` is enabled);
- The stake might get destroyed, and another one created, and the node will pick it up, too;

At any point, the node might establish connections, meaning it can be seen from different clients with different, potentially outdated, stakes.
Currently there is no way to re-negotiate a connection (re-do the 'handshake'), nor is there a clean way to tear-down all connections and restart them.

**Comment by Geod24** [comment]
To do this, we might have to dig into both the RPC client and Vibe.d.
It's acceptable to only implement it for the RPC client for now if necessary, but it will need to *also* work with Localrest.

The first step I was looking into was subclassing `RestInterfaceClient`, but it's only useful if we can have a persistent connection, which means storing the `HTTPClient`, which is not currently the case:
https://github.com/vibe-d/vibe.d/blob/b3818391b397616b20dd0c9b842e369b1e74a6d6/web/vibe/web/rest.d#L2051-L2053

Called from:
https://github.com/vibe-d/vibe.d/blob/b3818391b397616b20dd0c9b842e369b1e74a6d6/web/vibe/web/rest.d#L822-L824

Which is a method we could `override`, but currently we'd need to copy-paste a lot of code to make it work.

**Comment by omerfirmak** [comment]
> nor is there a clean way to tear-down all connections and restart them.

I am wondering if LocalRest channels could be used to make this easier to implement, a dynamic set of peers.
