### ISSUE TITLE
Generate `SRV`/`URI` record on node registration

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#2869]
The registry needs to automatically generate `SRV` records when `postValidator` / `postFlashNode` are called, as defined in https://github.com/bosagora/agora/blob/14459dd88a04797457a51f6e793d8b827b8d2d91/doc/DNS.md#locating-another-node

**Comment by mkykadir** [comment]
Will CNAME and A records still meaningful for us after this with the current Config fields (which expects `Address`)? Or, we might ease configuration field from `Address` to (i.e.) `string` and then work on that.

**Comment by Geod24** [comment]
Depends on the way we want to go. I think we can eliminate `SRV` records because they don't support the path component of the HTTP interface. So provided we generate `URI` record, do we want to have it under `boa1....coinnet.validators.bosagora.io.` or `XXX.boa1...coinnet.validators.bosagora.io.`.
`XXX` could be anything, so we could use `_agora` to somewhat mimic the `SRV` approach. If we do this, then having `boa1...` be either a `CNAME` (if we're provided with a domain name) or an `A` record (if we're provided with an IP) can make sense.

**Comment by Geod24** [comment]
Under this scheme, you would have the following:

1) `agora://192.168.0.1/`
    - `$KEY.$REALM` : A record (`192.168.0.1`);
    - `_agora.$KEY.$REALM` : URI record (`agora://$KEY.$REALM`);
2) `agora://best.validator.example.com:1234/api/`
    - `$KEY.$REALM` : CNAME record (`best.validator.example.com`);
    - `_agora.$KEY.$REALM` : URI record (`agora://$KEY.$REALM:1234/api/`);
    
The alternative is much simpler: Just store the `URI` that is provided. But it will not play nicely with other services (e.g. admin interface / votera).

**Comment by mkykadir** [comment]
It seems like this will require some architectural changes over Registry. I think it is better to have #2933 beforehand.
