### ISSUE TITLE
Expected Address schema should be limited

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2882]
Currently we can even have addresses starting with `ftp`, this will cause problems with the addition of the `URI` records #2869  for the registry. We should only expect addresses with schemes among `http`, `https` and `agora` within Agora.

**Comment by Geod24** [comment]
What about `dns://` ? :)

Instinctively, I'd say that should be solvable by checking it in https://github.com/bosagora/agora/blob/f5f801eaf7961b2a7df0d19b876bcffb55f38dd4/source/agora/common/Types.d#L79-L84
