### ISSUE TITLE
DNS TCP buffer is not enough for AXFR zone transfer

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2935]
Currently we're [using](https://github.com/bosagora/agora/blob/f55909e30fc22df2be88acb1ce777690b34b5bfc/source/agora/node/Runner.d#L395) 4096 bytes buffer from stack, which might not be enough for zone transfer when we have increasing number of records (current test condition is just 32 records).

Buffer might needed to be increased or zone transfers happen through IXFR.

**Comment by Geod24** [comment]
IXFR is definitely a plus, but I don't see how we can scale the buffer to something reasonable.
The whole reason we have a buffer is to get the size we have to send. Since the length is limited to 2 bytes, we could *just* have a 65534 bytes buffer and call it a day. But I wonder what happens when the zone size exceeds that limit.

**Comment by mkykadir** [comment]
IXFR might not be a solution for this issue. Because initial request will still be a full-zone transfer (even using IXFR) and sometimes IXFR may result in bigger packet size than AXFR (due to including older RRs in the response). I will check for TCP buffer size instead.

**Comment by mkykadir** [comment]
I think we can (should) respond with multiple DNS messages as [in the RFC 5936](https://datatracker.ietf.org/doc/html/rfc5936#section-2.2)

**Comment by mkykadir** [comment]
Currently transfers over UDP  [uses](https://github.com/bosagora/agora/blob/676ad915df7947607fdf117ba15749a13ff89348/source/agora/node/Runner.d#L324) dynamic memory allocation while serializing the message. TCP transferring avoids that and uses area from stack. Splitting a DNS message into several TCP segments still require knowing length of the full serialized message since first two bytes of the first segment must have full message length. Thus, this is not achievable with current approach. We can either switch over to dynamic memory allocation as in the UDP or increase the buffer size.
