### ISSUE TITLE
A default interface needs to be defined as a fallback

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2972]
Currently one can configure an Agora node have either HTTP or RPC interface or have both of them. Even this eases node configuration we need to define and inform users about a default interface schema that an another Agora node expects as a fallback. Currently network manager [needs](https://github.com/bosagora/agora/blob/25d0eb36fad62f5b3b2c439bc713ab55a84418d1/source/agora/network/Manager.d#L1060) full URL address from either `network` configuration or Registry to connect a peer. This is a problem for A and CNAME records in Registry since they don't have schema information. We need to define a default schema for those conditions. Consider our environment which always expects a HTTP interface available behind CNAME records.

Web browsers' behavior can be considered as an analogy. They generally fallback to HTTPS schema by default when user doesn't provide any, thus A record from a DNS is enough.

**Comment by omerfirmak** [comment]
In our production env, we probably need URI records since we use non-default ports for RPC interfaces

**Comment by Geod24** [comment]
Not sure I follow ? We should reconstruct the `Address` from the `A` / `CNAME` record + `URI` / `SRV`, shouldn't we ?
Also this `assert` needs to turn in an `enforce`

**Comment by mkykadir** [comment]
> Not sure I follow ? We should reconstruct the `Address` from the `A` / `CNAME` record + `URI` / `SRV`, shouldn't we ? Also this `assert` needs to turn in an `enforce`

URI record would be enough within Agora itself. I am working on a solution for incorporating both REST and DNS interfaces on `Address` usage. Currently, since POST endpoint requires an `Address`, GET also requires that. DNS and GET use same underlying methods.

**Comment by mkykadir** [comment]
Since #3047 , this is not needed within Agora network.
