### ISSUE TITLE
Every node is required to provide a `registry_address`

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#2989]
I don't think this was intended, `DNSResolver` has default DNS resolvers configured thus it shouldn't be required to have `registry_address` field for every node.

https://github.com/bosagora/agora/blob/133499d7c8083398e147be90bcb2874d86487cbc/source/agora/network/Manager.d#L695-L696

**Comment by Geod24** [comment]
Yeah, we need https://github.com/bosagora/agora/issues/2873

**Comment by mkykadir** [comment]
This also causes `DNSResolver` to send DNS request to HTTP endpoint of the registry node.

**Comment by Geod24** [comment]
Mistakes were made. Big ones. Working on a fix.
