### ISSUE TITLE
Make sure double-spend transactions are not added to the Pool

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#301]
## Current behavior

A double-spend transaction is a transaction which tries to spend the same unspent `Output` which another transaction also spends.

In the implementation of full block verification [in this PR](https://github.com/bpfkorea/agora/pull/193), the filtering of double-spend transactions was done in the Ledger class itself, [as seen here](https://github.com/bpfkorea/agora/blob/095cde407384d2afa9482162c240bb989af2dfe0/source/agora/node/Ledger.d#L217).

## Problem

Because the filtering of double-spends is done at the Ledger level **after** the transactions are added to the TransactionPool, this means the TransactionPool will always keep the double-spend transactions in its storage. This enables a form of DDoS, as the pool may end up growing indefinitely with double-spend transactions.

## Wanted behavior

Filter out double-spend transactions before they are added to the TransactionPool.

**Comment by linked0** [comment]
My implementations will be as follows
1. The checking code will be in the acceptTransaction function of Ledger class. The transaction parameter of the function will be compared against each Transaction object of the Transaction pool, by checking values of both hashes and those of both indices of the ’inputs’ member variables of the both Transaction objects. If The transaction parameter has same hash and index equal to those values of any transaction in the pool, It will be discarded and the rest of the function will not be executed.
2. I will use the unittest code having the comment “test behavior of receiving double-spend transaction” already written in agora/test/Ledger.d

Any comment would be helpful.

**Comment by Geod24** [comment]
Comparing the transaction hash won't work, because there can be an infinity of transactions that spends the same input.

**Comment by AndrejMitrovic** [comment]
There is way to do this in a more optimal way:

The UTXO set can in addition to tracking UTXOs also track referenced UTXOs by the transactions in the pool. `findUTXO` would have to be updated, to return false if a transaction tries to spend a UTXO which will already be spent by another transaction in the pool.

**Comment by AndrejMitrovic** [comment]
@Geod24 suggested to update the Pool instead of the UTXO set. That makes more sense, so I would suggest taking that approach if possible.

**Comment by linked0** [comment]
Henry suggested new approach in which we use new table for the information about a previous transaction and an index of the outputs(which actually is an UTXO). My first approach is to iterate all transactions of the pool by checking the information of the transaction, but I think it might impact the performance because the process involves deserialization as many times as the count of the transactions. We now have only 8 transactions maximum, but it will increase in the future. So, we need another new table with the schema having columns such as hash of previous transaction, index of outputs of the transaction, and the hash of transaction which is used to delete the rows when the transaction is removed from the tx_pool table. 

Is Henry's suggestion similar to Mathias' suggestion?

**Comment by MichaelKim20** [comment]
In @Geod24's opinion, it's important to filter out the same transaction Input.
But it's unclear whether the filtering range is a pool or an entire block.
I think 'pool' would suffice for the filtering range.

**Comment by MukeunKim** [comment]
> 따라서

**Comment by MichaelKim20** [comment]
Oh, that was a mistake. I'm sorry.

**Comment by AndrejMitrovic** [comment]
> But it's unclear whether the filtering range is a pool or an entire block.

This is unrelated to blocks. It's only about filtering Transactions from entering the Transaction Pool if there is already another transaction inside the pool which spends one or more of the same Outputs.

**Comment by linked0** [comment]
After discussing with Andrej and Michael, I have decided to make a map object for storing pairs of a previous hash and a index of the arrived transactions. In the middle of making block with transactions of the transaction pool, the stored information about each transaction on the map object will be deleted.

Any opinion would be helpful.
