### ISSUE TITLE
Consensus can get stuck in PREPARE phase

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#3014]
Some nodes fail to commit to a Ballot and we get stuck in PREPARE phase forever. A system wide restart generally unsticks the network.

**Comment by hewison-chris** [comment]
This could be solved by https://github.com/bosagora/agora/issues/3086

**Comment by omerfirmak** [comment]
I will give increasing timeouts a chance. Default implementation returns `roundNumber.seconds` so we mostly hit the timeout in the first couple of rounds and starting completely over. I am hoping that this would help both with our slow consensus and getting stuck problem.

```
        milliseconds computeTimeout(uint32_t roundNumber);  // Slot in the vtable
```

**Comment by hewison-chris** [comment]
But at some point we will still need to timeout and make progress after some kind of automatic reset. 
So I think maybe both are needed.

**Comment by Geod24** [comment]
Should be fixed by https://github.com/bosagora/agora/pull/3111
