### ISSUE TITLE
FullNode cannot find other peers when just `registry` is enabled

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#3030]
NetworkManager is responsible for discovering other peers. When a FullNode is started from scratch with just `registry` configuration enabled and no `network` peer is configured; it loops over

```Doing periodic network discovery: 0 required peers requested, 0 missing, known 6``` 

message and cannot find any peer. Main [cause](https://github.com/bosagora/agora/blob/6b59d77a4bb8231b3b86304ad4aed4c182a36c08/source/agora/network/Manager.d#L537) of this is `registry_client` is not initialized within `NetworkManager`, it is [only](https://github.com/bosagora/agora/blob/6b59d77a4bb8231b3b86304ad4aed4c182a36c08/source/agora/network/Manager.d#L505) initialized when node is `Validator`.

**Comment by Geod24** [comment]
Fixed in: https://github.com/bosagora/agora/pull/3053
