### ISSUE TITLE
Implement Schnorr signature encoding according to SEC1 v2 (v2.3)

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#304]
See section v2.3 of this paper: https://www.secg.org/sec1-v2.pdf
This is not urgent, but required before we release publicly, as we're dependent on Libsodium's internal state at the moment.

Related to #208

**Comment by hewison-chris** [comment]
I spent some time researching the need to use a different encoding (SEC1 v2) for the signature as generated by the [libsodium](https://github.com/jedisct1/libsodium) library. From what I can see the checks in the [verify code](https://github.com/jedisct1/libsodium/blob/3f2701839458cb8dd19bf11badda2e50128b36b6/src/libsodium/crypto_sign/ed25519/ref10/open.c#L31) are to prevent the [malleability](https://crypto.stackexchange.com/questions/14712/non-standard-signature-security-definition-conforming-ed25519-malleability/) of the signature.

**Comment by hewison-chris** [comment]
In my opinion we should continue to use the libsodium 64 byte encoding of the Signature (R, s).

**Comment by Geod24** [comment]
Agreed. According to what @hewison-chris found, the points are already stored in canonical form.
