### ISSUE TITLE
cpu does not support invariant TSC

### ISSUE THREAD

**Issue by greathugegithub** [bosagora/agora#3070]
Hello , I use Microsoft surface
![image](https://user-images.githubusercontent.com/18609287/154447619-0ef315f6-e44e-41c6-a0aa-0aa0dd290970.png)
### 
I follow your script "docker run bosagora/agora --testnet"
but I got error is  "cpu does not support invariant TSC" 
please see below image
![image](https://user-images.githubusercontent.com/18609287/154448488-d7d4372f-1bb3-4ee2-aaa0-f5df44ca15d9.png)

**Comment by omerfirmak** [comment]
Should be fixed the next release

**Comment by Geod24** [comment]
Can you test with https://github.com/bosagora/agora/releases/tag/v0.35.2 ?
You can do so by doing `docker pull bosagora/agora`.

**Comment by mkykadir** [comment]
It is working now after `v0.35.2`

#3072
