### ISSUE TITLE
Agora should reject unknown CLI arguments

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#3073]
To prevent someone using `-testnet` and the like and it not having any effect.

**Comment by mkykadir** [comment]
Currently unrecognized options prevent Agora to be started,

```
agora --unrecog --testnet
Error parsing command-line arguments '"agora" "--unrecog" "--testnet"': Unrecognized option --unrecog
```

**Comment by Geod24** [comment]
Indeed, it's already handled correctly. Looks like I misdiagnosed the issue, thanks for checking!
