### ISSUE TITLE
No transactions in blockexplorer on active validator 

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/agora#3168]
I pulled latest, froze 40k BOA and running a validator node with "docker run -p 2826:2826 -v $(pwd):/config.yaml bosagora/agora --testnet". The validatorseed is in the config.yaml file and runs now for a few days. I still dont see any transactions on the blockexplorer:
https://testnet.boascan.io/address/details/boa1xppkpvglwdc85ykjnwaws7plakj4qtqpx5205s4p2npsxjksaam5gu03g2q
I tried 3 different validator seeds in the webwallet. 
I cant see active validators in the webwallet, how do i troubleshoot this?
Its running on docker in a headless ubuntu server. port 2826 is forwarded.

**Comment by Geod24** [comment]
To get a validator, you need to request it at faucet (https://faucet.bosagora.io/). Did you do that ?

**Comment by Geod24** [comment]
I did it for you, you should now be able to enroll normally.

**Comment by RoscoPColtrane1** [comment]
I froze 40k on the wallet adress, i dont think i used the validatoradress. maybe that was it. I will leave it running. I should see transactions (rewards) soon. If so, this issue can be closed. Thx.

**Comment by RoscoPColtrane1** [comment]
If this was really the problem we can conclude the software is noob-proof now and i will feel stupid for a week ;)

**Comment by RoscoPColtrane1** [comment]
hi, i still dont see transactions, the node is running with the seed in de configfile. https://testnet.boascan.io/address/details/boa1xppkpvglwdc85ykjnwaws7plakj4qtqpx5205s4p2npsxjksaam5gu03g2q

**Comment by omerfirmak** [comment]
Your validator was never enrolled as far as I can see. Can you share your config file? (dont forget to redact your seed)

**Comment by RoscoPColtrane1** [comment]
Sure, here is the configfile:
[config.yaml.txt](https://github.com/bosagora/agora/files/8286290/config.yaml.txt)

**Comment by omerfirmak** [comment]
Can you make your port 8080 public, so I can inspect the state of your node?

**Comment by RoscoPColtrane1** [comment]
Lets start with inspecting it myself :) : http://127.0.0.1:8080  , browser says "unable to connect"
if i curl like this: curl http://127.0.0.1:2826/blocks/0
curl: (1) Received HTTP/0.9 when not allowed
Looks like its an ports issue in docker. do i need to open port 8080 in docker too to see the webserver?, like -p 8080:8080?
What tests are needed to see if ports are functional? thx

**Comment by omerfirmak** [comment]
Yeap, you need “-p 8080:8080“.

Try accessing http://127.0.0.1:8080 and you should get a 404 error.

**Comment by RoscoPColtrane1** [comment]
Done. you can acces port 8080 now.

**Comment by RoscoPColtrane1** [comment]
The node stopped eventually with an peer error, so i pulled latest again. Now it starts with same error: warnings: agora.node.FullNode] - agora.node.FullNode.FullNode.catchupTask: Could not perform catchup yet because we have no peer.
I will let it run for a while.

**Comment by omerfirmak** [comment]
@RoscoPColtrane1 , `v0.38.0` was deployed to the network, you should update your node and clear your `data` and `.cache` directories.

**Comment by RoscoPColtrane1** [comment]
ok, i pulled latest again, i always delete the images/containers/volumes when i run a new docker. i didnt mount the data directory or .cache file separately, like the config file. So it should be destroyed when it builds a new one. thx

**Comment by Activatorq1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14156445/

**Comment by RoscoPColtrane1** [comment]
this issue can be closed
