### ISSUE TITLE
FullNode: `acceptHeader` is never invoked for missing block signature updates

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#3199]
https://github.com/bosagora/agora/blob/b947ae2e0b2188a662b74dc9de2beea7d522a26b/source/agora/network/Manager.d#L993-L994

potential signature count is equal to signature count for a (just) FullNode since `extra_sigs` is just returning 0; thus `acceptHeader` can never be invoked.

https://github.com/bosagora/agora/blob/b947ae2e0b2188a662b74dc9de2beea7d522a26b/source/agora/node/FullNode.d#L605

**Comment by mkykadir** [comment]
It will be invoked when it finds header from another peer with full signature.

**Comment by hewison-chris** [comment]
> It will be invoked when it finds header from another peer with full signature.

Or more than it had.
