### ISSUE TITLE
Nominator: Nominate hash of the Tx set instead of set of TX hashes

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#3211]
as the load on the network increases we get bigger and bigger envelopes since we need to communicate more TX hashes.
Furthermore, more TXs in the network means more unique values nominated because of desync pools across different nodes.

So our network traffic increases worse than linearly, compared to the increase in TX count we are trying to externalize.

So instead of nominating Set!Hash for tx set, we should be nominating a single hash of the whole TX set and allow peers to download that TX set from us.

**Comment by Geod24** [comment]
> So instead of nominating Set!Hash for tx set, we should be nominating a single hash of the whole TX set and allow peers to download that TX set from us.

But with a `Set!Hash` we can do set reconciliation (take the common subset), something which we can't do with a single Hash.

**Comment by omerfirmak** [comment]
> 



> > So instead of nominating Set!Hash for tx set, we should be nominating a single hash of the whole TX set and allow peers to download that TX set from us.
> 
> But with a `Set!Hash` we can do set reconciliation (take the common subset), something which we can't do with a single Hash.

We will have a copy of the TX set it represents at hand tho, so we can do anything we did before. Just think of it as if it was a pointer. We just wont be transmitting same hashes over and over again in every envelope.
