### ISSUE TITLE
RPC: Revamp to implement a LocalRest-like request handling

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/agora#3253]
Currently, we support only a single request in-flight per connection. LocalRest does this differently and can handle multiple requests thru a single connection. LocalRest's approach is more robust in certain edge cases where a request to node A from node B triggers a new request to node B.

**Comment by omerfirmak** [comment]
We can even move to UDP for better scalability, any opinions? @bosagora/core

**Comment by hewison-chris** [comment]
> We can even move to UDP for better scalability, any opinions? @bosagora/core

As we have retries at the application level I suppose the fact that UDP is not as reliable as TCP should not be an issue.
