### ISSUE TITLE
Implement the endpoints for Web Admin Interface

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/agora#3280]
We provides the `Admin` interface now in [Admin.d](https://github.com/bosagora/agora/blob/v0.x.x/source/agora/api/Admin.d). But the requirement for the endpoints has changed so we support the change in Agora.

**Comment by linked0** [comment]
[This PR](https://github.com/bosagora/agora/pull/2478) is for the Web Admin interface that uses the Agora Admin endpoints.

**Comment by linked0** [comment]
Completed with PR [#3294](https://github.com/bosagora/agora/pull/3294)
