### ISSUE TITLE
Root log is not propagated to console

### ISSUE THREAD

**Issue by mkykadir** [bosagora/agora#3295]
Even following config, logs are not displayed on console; since #3243 

````
logging:
  root:
    level: Info
    console: true
    file: log/root.log
````

**Comment by linked0** [comment]
I have used the `additive: true` for the problem, it is just a workaround tho.

**Comment by mkykadir** [comment]
> I have used the `additive: true` for the problem, it is just a workaround tho.

Yeah, I don't know if this is an undocumented change in behavior but;
[this](https://github.com/bosagora/dtext/commit/931a14e91f1f8cf1b9f2ec7e12687ef2579222bb) causes

**Comment by mkykadir** [comment]
> Likewise, setting the root logger as additive most likely
means child loggers should be additive too,
hence propagating all options make more sense.

I believe there was a behavioral change thus, `additive` is required by default now. We can close this or reconsider. What are your thoughts? @hewison-chris

**Comment by hewison-chris** [comment]
> > Likewise, setting the root logger as additive most likely
> > means child loggers should be additive too,
> > hence propagating all options make more sense.
> 
> I believe there was a behavioral change thus, `additive` is required by default now. We can close this or reconsider. What are your thoughts? @hewison-chris

Perhaps the default should be `additive` so that it behaves as expected.
