### ISSUE TITLE
Change GossipProtocol.hasTransactionHash() to check tx hash in the pool

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#345]
The periodic getBlocksFrom() call does not add transactions from the blocks to the `GossipProtocol`, so `hasTransactionHash()` will fail even if a node contains a transaction in its ledger.

**Comment by Geod24** [comment]
But [`hasTransactionHash`](https://github.com/bpfkorea/agora/blob/e21d0573c6feaf8fb2d181370788dcec77c35f05/source/agora/node/GossipProtocol.d#L89) only checks the TxPool, not the ledger.

**Comment by AndrejMitrovic** [comment]
Ah yeah. Well there is another issue, we never remove items from the Gossip cache..

**Comment by AndrejMitrovic** [comment]
> But hasTransactionHash only checks the TxPool, not the ledger.

From what I understand, the reason `hasTransactionHash` was introduced to a avoid costly network operation when sending a tx that a node already contains.

If a tx is in a node's pool there's no need for another node to send it the tx again. But if the tx is in the blockchain there is also no need for another node to send it because that transaction won't be accepted (it double-spends UTXO).

Currently `hasTransactionHash` acts as a permanent storage of all seen transaction hashes. Well, except that it doesn't serialize its data to disk..

Question then:
- Should it only return true if a tx is in the node's tx pool?
- Or should it still keep the set of all tx hashes it's ever seen, but we should persist that data across restarts?

**Comment by Geod24** [comment]
> Should it only return true if a tx is in the node's tx pool?

Yes

> Or should it still keep the set of all tx hashes it's ever seen, but we should persist that data across restarts?

No

**Comment by MichaelKim20** [comment]
We should persist that data across restarts?.
When we start a node, if we don't have to maintain historical data,
We'd better use the cache.

**Comment by MichaelKim20** [comment]
Of course I'll handle it in the Transaction Pool!

**Comment by AndrejMitrovic** [comment]
> We should persist that data across restarts?.

As @Geod24 said in https://github.com/bpfkorea/agora/issues/345#issuecomment-536819178, we don't have to persist data. We just have to check if the transaction hash is in the TransactionPool.

**Comment by TrustHenry** [comment]
@Geod24 @AndrejMitrovic 
How about a new function in TransactionPool?
The new function is `SELECT key, val FROM tx_pool WHERE key = ? ` in the TransactionPool DB, and Tx hash result have value.

Or there may be a method to find the same hash with Foreach using `TransactionPool.opApply`
Please give me your opinion on what looks like a good.

**Comment by AndrejMitrovic** [comment]
> How about a new function in TransactionPool?

Yes, a `hasTransactionHash` inside of the Pool is a good approach.

> Or there may be a method to find the same hash with Foreach

That would be a linear search, it's better to do a `SELECT` with a `WHERE` statement like you suggested at first.

**Comment by MichaelKim20** [comment]
I think it's better to use 'Set!Hash' inside the TransactionPool.
I think we can get rid of the attack point from the outside.

**Comment by AndrejMitrovic** [comment]
It's more optimal to use a `Set!Hash`, however it comes with a cost:

- You need to serialize/deserialize the Set!Hash data manually, it's not part of the SQLite database.
- You need to make sure the Set!Hash and the Transaction pool are in sync when adding / removing items.
- You need to add a checksum when serializing/deserializing the Set!Hash, otherwise the data in the Set!Hash loaded from disk cannot be trusted. SQLite already has checksums of the data it stores, it's hidden from the D code.
- If loading the Set!Hash fails or the checksum fails, you have to rebuild the Set!Hash from the TransactionPool.

It's not a bad idea, It's just something to keep in mind.

I would also suggest doing some profiling: Write an optimal SQL statement for checking if a transaction key is inside the database. Then, compare that with performance of lookups in the `Set!Hash`. How much is the performance difference? Is it worth the coding complexity of using a Set!Hash?

**Comment by MichaelKim20** [comment]
I think you understood what I thought differently.

**Comment by TrustHenry** [comment]
> The new function is `SELECT key, val FROM tx_pool WHERE key = ? ` in the TransactionPool DB, and Tx hash result have value.

I will proceed in this way.

**Comment by MichaelKim20** [comment]
> It's more optimal to use a `Set!Hash`, however it comes with a cost:
> 
> * You need to serialize/deserialize the Set!Hash data manually, it's not part of the SQLite database.
> * You need to make sure the Set!Hash and the Transaction pool are in sync when adding / removing items.
> * You need to add a checksum when serializing/deserializing the Set!Hash, otherwise the data in the Set!Hash loaded from disk cannot be trusted. SQLite already has checksums of the data it stores, it's hidden from the D code.
> * If loading the Set!Hash fails or the checksum fails, you have to rebuild the Set!Hash from the TransactionPool.
> 
> It's not a bad idea, It's just something to keep in mind.
> 
> I would also suggest doing some profiling: Write an optimal SQL statement for checking if a transaction key is inside the database. Then, compare that with performance of lookups in the `Set!Hash`. How much is the performance difference? Is it worth the coding complexity of using a Set!Hash?

When the node is restarted, it seems that you want to keep the old data. 
Then we'd better use SQL.

**Comment by AndrejMitrovic** [comment]
What I'm worried about is replicating what SQLite already does by having an internal Set which duplicates the work already done by SQLite.

@Geod24 could you provide some feedback here to these comments?

**Comment by AndrejMitrovic** [comment]
I think this should be marked as resolved, unless @Geod24 thinks otherwise.

**Comment by TrustHenry** [comment]
<img width="927" alt="스크린샷 2019-10-11 오후 5 06 37" src="https://user-images.githubusercontent.com/48541289/66637423-f3e4b600-ec4d-11e9-823c-649693f55920.png">
