### ISSUE TITLE
Add test cases for transaction validation that aren't covered

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#360]
According to the coverage report, those cases are not covered:
- Transactions without input
- Input overflow (duh)
- Combined input
- Unknown transaction type
- Mixed inputs

Needs to cover both payments and freeze Txs.

**Comment by Geod24** [comment]
Coverage report: https://codecov.io/gh/bpfkorea/agora/src/v0.x.x/source/agora/consensus/Validation.d

![image](https://user-images.githubusercontent.com/2180215/65927568-219f5300-e435-11e9-85ac-ad7240e61259.png)

**Comment by linked0** [comment]
I can't tell between combined input and mixed input. Actually, I found out that combined input means that the freezing count and the input length of tx in the code are not equal. Would you please give more information about mixed input?

**Comment by linked0** [comment]
After IRL(in real life) conversation with Mathias, It is confirmed that combined inputs and mixed inputs are same things.
