### ISSUE TITLE
Log exceptions directly instead of using `scope (failure) assert(0);`

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#363]
The `scope (failure)` trick that we use right now is swallowing information about the origin of the exception. For example:

```D
void test()
{
    scope (failure) assert(0, "-- Second exception");
    test2();
}

void test2()
{
    throw new Exception("-- First exception");
}

void main()
{
    test();
}
```

```
$ rdmd test.d

core.exception.AssertError@test.d(3): -- Second exception
----------------
??:? _d_assert_msg [0x10218a236]
??:? void test.test() [0x10217cc23]
??:? _Dmain [0x10217cba8]
```

The information about the first exception is lost.

Also if I do this:

```D
void main()
{
    try
    {
        test();
    }
    catch (Throwable ex)
    {
        writeln(ex);
        writeln(ex.next);
    }
}
```

I get:

```
core.exception.AssertError@test.d(5): -- Second exception
----------------
??:? _d_assert_msg [0x10eb5030a]
??:? void test.test() [0x10eb37d1b]
??:? _Dmain [0x10eb37c5c]
null
[Finished in 0.7s]
```

What happened to the chained-exceptions feature? Is it not implemented on OSX? :/

**Comment by Geod24** [comment]
Well, those asserts are never supposed to be triggered. If they are, it should be a proper `catch`.

**Comment by AndrejMitrovic** [comment]
Right. But why is the first exception thrown away? It sucks for debugging.

**Comment by Geod24** [comment]
Yeah that's a quirk. But is this issue valid ?

**Comment by Geod24** [comment]
I think we're done with this. We mostly use `scope (failure)` in network unittests to print the network logs.
We also have a couple instances here and there as "last chance" when a critical error happens and we log a message, but since `Exception.toString()` is not `nothrow`, we use the `scope (failure)` hack.
