### ISSUE TITLE
Implement a VirtualClock to make tests more efficient and reliable

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#389]
We already use something similar for our BanManager tests, where we override the BanManager's clock routine to return a "fake" clock time. Stellar-core does something similar for its entire test-suite, and especially for the SCP tests. With a virtual clock we can make tests more efficient, and we can simulate arbitrary delays without having to physically wait for the wall clock time to advance.

**Comment by Geod24** [comment]
Is this becoming more of a priority now that we have SCPD ?

**Comment by AndrejMitrovic** [comment]
> Is this becoming more of a priority now that we have SCPD ?

In short: yes, for testing failures. We don't have those tests yet in Agora, but I plan to add them.

Here's some info for the whole team:

So timer's in SCP are only used to track communication failures within a given time-frame. SCP basically does this (pseudocode):

```
// See Slot.d : timerIDs
startTimer(BALLOT_PROTOCOL_TIMER, &onFailure, 1.seconds * attempt_number);  

... // actually attempt this ballot, this might take some time

// kills the timer before it has the chance to fire
stopTimer(BALLOT_PROTOCOL_TIMER);  
```

Where `onFailure()` would really just restart the whole process but also increment `attempt_number` to gradually increase the timeout. In SCP parlance, there can be multiple rounds of voting for a given slot (block height), these rounds are the Ballots (BallotProtocol). In our yellow paper the "voting round" means a completed externalized block (which may consist of multiple ballots / multiple voting rounds).

**Comment by AndrejMitrovic** [comment]
Resolved.
