### ISSUE TITLE
Add automatic size checks between C++ and D types (structs, etc)

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#4]
Long term goal: Make this check automatic

_Originally posted by @Geod24 in https://github.com/bpfkorea/agora/pull/2#discussion_r286777408_

**Comment by AndrejMitrovic** [comment]
Ugh.. it doesn't link to the diff?

**Comment by Geod24** [comment]
This applies to the SCP classes and the XDR struct, mostly.

**Comment by AndrejMitrovic** [comment]
Thanks.
