### ISSUE TITLE
See if we should bring in unit-threaded or another testing framework

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#402]
There might be benefits to bringing in a testing library, such as named unittests, potentially faster builds, stats, parameter permutation, and so on.

**Comment by Geod24** [comment]
We have our own framework (localrest) and we saw that going multi-threaded led to tons of issue, so I don't think that's something we will be exploring any time soon. In fact, we're more likely to roll out our own based on the concurrency improvements made by @omerfirmak .
