### ISSUE TITLE
Design and implement enrollment process

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#406]
As a developer, I need the enrollment process described in the yellow paper to be implemented in order to build other issues (transaction filter, quorum balancing) on top of the random function.

Definition of done:
- [x] Nodes enroll by committing <K, X, N, R, S>
- [x] There is a function that derives randomness from `X`;
- [x] There is a function that derives randomness from the sum of all `X`;
- [ ] ~On each round, `X` is propagated and checked for validity (is it registered on the chain?);~
- [x] On each round, `R` is used for signature (see #365)

Description:
```
K: A hash of a frozen UTXO;
X: The nth image of their source of randomness;
N: A number within bounds [0; (Balance(K) % 40,000) * 2016 * 2 (tentative value)];
R: The initial R used for signing;
S: A schnorr signature for the message H(K, X, N, R) and the key K, using R.
```

Three approaches of using frozen UTXO in enrollment process
```
1) Disallow freezing if Public key ∈ Frozen set
  - Useful
2) Use everything
  - Unfreeze one(Flash!)
  - Complicates unfreezing
  - Harmless
3) Provide UTXO hash + idx on a set
  - Slight complication
  - Wanted
```

**Comment by AndrejMitrovic** [comment]
Quick question: So when a node generates a random key, what it actually generates is a scalar n, and then it commits to the Nth hash of n, and also the public key generated from n. So basically our random value is a source for a point on the curve. Is this correct?

**Comment by AndrejMitrovic** [comment]
> A signature for the message H(K, X, N, R) and the key K, using R.

Should this be using `r` (the private random key), rather than `R` (the public key)?

**Comment by AndrejMitrovic** [comment]
I modified the issue to make it explicit: S is the schnorr signature of `H(K, X, N, R)`, just like in https://github.com/bpfkorea/agora/blob/a0e12c8abff3269293ab61e652c5ec68627ee02e/source/agora/common/crypto/Schnorr.d#L154-L158

**Comment by AndrejMitrovic** [comment]
> Nodes enroll by committing <K, X, N, R, S>

The `R` is already available in the signature S, no? In [here](https://github.com/bpfkorea/agora/blob/a0e12c8abff3269293ab61e652c5ec68627ee02e/source/agora/common/crypto/Schnorr.d#L96). It seems like it doesn't have to be included separately in the enrollment transaction, unless I'm missing something?

**Comment by Geod24** [comment]
That's correct.

**Comment by linked0** [comment]
The definition of done has these items as follows.
- There is a function that derives randomness from X;
- There is a function that derives randomness from the sum of all X;

Can you describe in detail about "deriving randomness"?
Thanks :)

**Comment by AndrejMitrovic** [comment]
> N: A number within bounds [0; (Balance(K) % 40,000) * 2016 * 2 (tentative value)];

@Geod24 I think you meant a division here, not a modulo? So if you stake 80k, in this (example scheme) you would be able to sign for four weeks instead of two. Of course the actual formula may be fine-tuned later.

**Comment by AndrejMitrovic** [comment]
@Geod24 I think we need to add a division operator to `Amount`. (maybe an explicit one via `bool div (...)` rather than an operator overload)

**Comment by AndrejMitrovic** [comment]
Hmm or I guess we could just use `Amount.integral()` to do the math.

**Comment by linked0** [comment]
**Data structure and class**
* EnrollmentManager and EnrollmentData
> EnrollmentManager: Handles data and process for enrollment.
> EnrollmentData: Defines data for enrollment process.
> The code of this has been proposed by PR at 13th Nov.
* Validator enrollment data set
> The class named ValidatorSet.
> Manages enrollment process.
> Stores information for validators’ enrollment data(EnrollmentData objects).

**Functions(API)**
* enrollValidator
> A node propagates the enrollment data in order to be a validator.
* getValidatorSet
> If the vaidator set is missing, a node can request for the data to the neighboring nodes.

**Not determined**
* How to implement the process in which a node propagates the X and other nodes checks the X for validity.

**Comment by linked0** [comment]
You can see the current state of my resolving this issue.
[linked0 github commit](https://github.com/linked0/agora/commit/b4b2e0619e12b682bd0afeac215a03a45580e79f)
Any commnet would be helpful.
Never mind about the binary files uploaded mistakenly.

**Comment by AndrejMitrovic** [comment]
The enrollment needs to be recorded on the blockchain. When a node enrolls for N blocks, which means it will validate the next N blocks, the `N` needs to begin from somewhere. It begins to be counted from the moment the enrollment transaction becomes a part of the blockchain.

**Comment by linked0** [comment]
Thank you for your comment, Drey.
After I discussed about this with Henry, I came to totally agree with you. I think the information about the validators should be stored in a Block.
By Mathias' opinion that I said, I meant he did not want to make another transaction type. So your opinion and Mathias' are different part of this issue.

**Comment by AndrejMitrovic** [comment]
> By Mathias' opinion that I said, I meant he did not want to make another transaction type. 

Did he suggest alternatives? Because I don't see how it can be done without creating a new transaction type.

**Comment by linked0** [comment]
> Did he suggest alternatives? Because I don't see how it can be done without creating a new transaction type.

Another API for Node like putTransaction. So, I'm writing the API function named enrollValidator(enroll as Validator). But I'm realizing that making new transaction type could be better way to implement. What do you think about a Block saving non-transactional information into block body? I'm concerned about a block could be kind of a mess by saving the validators' information at block body. It's a just a concern not an objection to saving the information to the block body part.

**Comment by AndrejMitrovic** [comment]
> Another API for Node like putTransaction. 

I think you could proceed with what he suggested. Unfortunately he's not here so I can't ask him questions about it, but I'm sure he has a good reason why he suggested an API endpoint.

**Comment by linked0** [comment]
Summarized points from discussion with Drey & Henry
* Implementing new transaction type should be avoided.
* The API endpoint will be made for enrolling as a validator.
* The validators' information should be saved into block header not into block body. (EDITED)

@Geod24 What do you think about those summarized points?

**Comment by AndrejMitrovic** [comment]
Aha, I understand the intention better now. I was confused about the storage of the enrollment. A new API endpoint makes sense.

> into the Block not into block body.

You mean "BlockHeader and not Block"?

**Comment by linked0** [comment]
> You mean "BlockHeader and not Block"?

Yes, that's right.
The words I used are confusing.

**Comment by AndrejMitrovic** [comment]
Then I would say proceed with the plan of having the new API, it sounds good to me.
