### ISSUE TITLE
Lift compile-time restriction on hashing / serialization / deserialization

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#432]
Currently we have restrictions on hashing, serialization, and deserialization, like this:
https://github.com/bpfkorea/agora/blob/c38249d20122430b68a7d7d58bc8d12f1bf46868/source/agora/common/Hash.d#L122-L125

The "common" approach would have been to use `tupleof` to just iterate over all struct members. But this approach could easily be misused, by hashing/serializing some private elements of the record, such as a cached value.

However this has led to a lot of repetitive code, and even helpers to work around it: https://github.com/bpfkorea/agora/blob/c38249d20122430b68a7d7d58bc8d12f1bf46868/source/agora/common/Serializer.d#L21-L41

So should we just do away with the limitation ? Is there another approach that would work better ?

**Comment by AndrejMitrovic** [comment]
how about something like `serializeEasy(data)` which will "just work", and `serializeFull` which requires hand-written support?

**Comment by Geod24** [comment]
When would you use `serializeFull` then ?

**Comment by AndrejMitrovic** [comment]
Well maybe it would be called `serializeSafe` or something. Basically what I mean is, you use `serializeEasy` when you just want to quickly serialize something (really useful during testing), and use `serializeFull` when you need to send data over the network to another node.

Is that distinction useful?

Other solutions might be to use UDAs. Something like `@DontSerialize` and having a single serialization function that works with .tupleof on all the fields.

**Comment by Geod24** [comment]
> when you just want to quickly serialize something

Do we have case where we want to serialize something that is not serialized outside of `unittest` ?
In my experience, it only happens during development / while working on the type itself. YMMV.
If it's for testing, we could just `version (unittest)` it.

> Other solutions might be to use UDAs.

For clarify, what I suggest is to call `serialize` if it's implemented, otherwise default to `tupleof`.

**Comment by AndrejMitrovic** [comment]
> In my experience, it only happens during development 

Yes, my thoughts are the same.

> For clarify, what I suggest is to call serialize if it's implemented, otherwise default to tupleof.

Aha. Ok with me.
