### ISSUE TITLE
Create one command for building & testing all targets on all compilers locally

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#490]
As mentioned in the Sprint retro, we should have one command that lets us test all the compiler combinations locally. This way, developers avoid having to wait for the CI system to see if there is anything wrong with the code. The CI might be overloaded or slow at some points.

It could also be useful to create a local git hook, so the tests run automatically when a user tries to `git push` to their branch. This part is completely optional to the developer if they want to use it.

**Comment by Geod24** [comment]
Was thinking more about the `git` hook and it might be quite painful, as the tests usually take several minutes.

**Comment by AndrejMitrovic** [comment]
Actually I'd also like to be able to do `./ci/system_integration_test.d --unittest` to just run the unittests in Docker. Maybe it shouldn't be `./ci/system_integration_test.d` specifically, but that's the  module that deals with docker stuff.

**Comment by Geod24** [comment]
Closing as we have two commands that are easy to run, and the tests are heavy enough that this issue doesn't make much sense anymore.
