### ISSUE TITLE
Implement broadcasting preimage

### ISSUE THREAD

**Issue by lunalee1012** [bosagora/agora#492]
After registering as a validator in round R, a node must broadcast the preimage every round from round R + 1 based on the white paper. It ensures true randomness of the network without ability to manipulate data.

But, as described in the white paper, a node could regularly broadcasts multiple preimages in order to survive network outages. It might be efficient to broadcast multiple preimages periodically 
 at certain intervals instead of in every round. 

Definition of Done:
- [x] The enrollment manager saves all preimages while hashing random number n times before enrollment.

- [x] A node broadcasts preimages and the round #s of the preimages through the gossip protocol.

- [x] The enrollment manager saves the received preimages and the round numbers into the DB.

How to implement:
- The enrollment manager saves preimages into the DB in creating enrollment data and make registering(=enrolling) preceed with Q(=12) preimages.(The proper value of Q should be searched)

- An API point called `revealPreimages` in every P(=1) hours with Q preimages.(The proper value of P should be searched)

- The enrollment manager saves the preimages and round numbers of other validators into the DB.

- The enrollment manager checks the validity of preimages received through the API and set an flag for an invalid validator into the DB or propagate the information of the invalid validator (it could be  another new issue)

**Comment by AndrejMitrovic** [comment]
Also, according to the Yellow paper, a node can reveal multiple preimages in advance. This is in order to survive network outages.

**Comment by linked0** [comment]
Based on @AndrejMitrovic comment, I changed the API name to `revealPreimages`.

**Comment by AndrejMitrovic** [comment]
> Also, according to the Yellow paper, a node can reveal multiple preimages in advance. This is in order to survive network outages.

Actually it doesn't have to reveal "multiple" ones. It just has to reveal the preimage for a specific block height.

For example, if a Node wishes to reveal preimages for the range of blocks #100 to #200, It could reveal the preimage for block height #200. Because it is a preimage, other nodes can figure out the preimage at block height #100 by hashing the preimage of block height #200 a 100 times.

Does it make sense to you?

**Comment by linked0** [comment]
It really makes sense. Thank you.
