### ISSUE TITLE
Enrollment data should be written to the block.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora#493]
Writing Enrollment data to a block determines the height of the block that can participate in the validation as a validator.
Validators needed for the consensus process can be determined and the number of validators between nodes can be set.

Definition of Done:

- [x] The Enrollment data should be recorded only in the enroll start block.

- [x] When writing to a block, it must be sorted in ascending order by UTXOkey of the enrollment data.

- [x] The node store the enrolled block height.

How to implement

- create a Query to import the elements from the Enrollment manager.

- The conditions for this must be taken in order of the UTXOkey's ascending order with the null height of the block.

- Record the target enrollments at block generation.

- When the enrollment data is stored in a block, the height of that block must be renewed in the DB of the node.

**Comment by Geod24** [comment]
> ascending order by UTXOkey

Do you mean ascending order of the hash, or something else (e.g. value) ?

**Comment by TrustHenry** [comment]
> > ascending order by UTXOkey
> 
> Do you mean ascending order of the hash, or something else (e.g. value) ?

That's right.
It is  Enrollment.utxo_key or It's a utxo hash and a hash of index.

**Comment by Geod24** [comment]
Done in https://github.com/bpfkorea/agora/pull/504 and some related PRs.
