### ISSUE TITLE
Build single-binary networks

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#510]
This is an idea I want to leave here for discussion.

Currently, we have 2 kinds of tests:
- Unittests, which use `localrest` to simulate a network.
- Full fledged network tests, using `docker-compose` (see tests/system).

However, full-fledged integration tests are quite expensive (require to spawn a container, no sharing of data, etc...). One possibility to test network would be to be able to generate a single binary which  exposes a network via the usual Node API, but internally uses LocalRest for networking.

With a sensible CLI, it could also possibly allow to test multiple network configurations (e.g. introducing bad nodes) without recompilation.

**Comment by Geod24** [comment]
So currently we have system integration tests (https://github.com/bpfkorea/agora/tree/v0.x.x/tests/system) which spawns 3 docker images of the node, with 3 different configuration files (https://github.com/bpfkorea/agora/tree/v0.x.x/tests/system/node under {0,1,2}/config.yaml), and a runs a test defined [here](https://github.com/bpfkorea/agora/blob/v0.x.x/tests/system/source/main.d). The full pipeline is run via [`ci/system_integration_test.d`](https://github.com/bpfkorea/agora/blob/v0.x.x/ci/system_integration_test.d)

However, spawning 3 docker images is expensive and won't scale very well. One thing we'd like to do is to have an intermediate between the LocalRest tests we have in `source/agora/test` and the full-fledge (complete) system integration tests described here.

This can be done by having a special main that creates nodes based on its arguments. All it would need is the ability to read multiple config files, and instantiate multiple `Node` as a result. A good starting point is to look at [this code](https://github.com/bpfkorea/agora/blob/c7314c21700c526d6ee496090694bef46dc9da54/source/agora/node/main.d#L70-L89).

**Comment by Geod24** [comment]
Also it is probably best to make it another "target", or configuration. This is what we are currently doing with `agora-cli`: https://github.com/bpfkorea/agora/blob/c7314c21700c526d6ee496090694bef46dc9da54/dub.json#L41-L71

**Comment by MichaelKim20** [comment]
@Geod24 I am going to use LocalRest to create nodes according to the config file.
Is it correct to use LocalRest?

**Comment by Geod24** [comment]
When we discussed the topic in our sprint planning, I thought so.
However, using LocalRest would prevent the client talking to any node, so all things considered I don't think it should use it.

**Comment by Geod24** [comment]
Done in #592
