### ISSUE TITLE
`isQuorumSetSane` is not informative

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#515]
Currently, when this check fails, there is no mention on *why* (which check) it fails, nor what data made it fail.

**Comment by AndrejMitrovic** [comment]
https://github.com/stellar/stellar-core/issues/new/choose

:P

**Comment by AndrejMitrovic** [comment]
Technically this will be resolved by the quorum selecting algorithm, because it will not be a user-facing error anymore.

**Comment by Geod24** [comment]
We will still use it as a sanity check, won't we ? So it'll be more of an enhancement, but could *still* be useful (especially while developing said algorithm)

**Comment by AndrejMitrovic** [comment]
Yeah but then we have to rewrite the function itself, it's not returning any error codes sadly. So it might be a PR to upstream.
