### ISSUE TITLE
std::invalid_argument sometimes thrown in the test suite

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#553]
```
Running ./build/agora-unittests 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  invalid public key type
Program exited with code -6
The command "./ci/run.sh" exited with 2.
```

Just witness it in an unrelated PR (not touching anything that is sent to C++).
Triggered with DMD 2.090.1, rest was green. I think the compiler version is irrelevant, except in proving it's spurious. Retriggering the CI fixed the failure.

Pretty sure it was introduced by https://github.com/bpfkorea/agora/pull/545

**Comment by AndrejMitrovic** [comment]
This might be related for reproducing the issue https://github.com/bpfkorea/agora/pull/641

The failure is different - `std::runtime_errror`, but might be related.

**Comment by MichaelKim20** [comment]
> This might be related for reproducing the issue #641
> 
> The failure is different - `std::runtime_errror`, but might be related.

I checked, too. Let me first check which 'unittest' is the problem.

**Comment by MichaelKim20** [comment]
@Geod24 I found out what kind of commit caused this problem.
https://travis-ci.com/github/bpfkorea/agora/jobs/290233020
I pressed the restart button and the message was erased.
How can I replicate these errors?

**Comment by MichaelKim20** [comment]
The error message occurred here.
There are four of these in this file.
https://github.com/bpfkorea/agora/blob/fb3d2e28a624a3632b169d649853e554c82dcfea/source/scpp/src/crypto/SecretKey.cpp#L218

**Comment by MichaelKim20** [comment]
This is the original message.
[invalid_argument.txt](https://github.com/bpfkorea/agora/files/4328640/invalid_argument.txt)

**Comment by Geod24** [comment]
~@MukeunKim : Could it be related to https://github.com/bpfkorea/agora/issues/640 ?~
~Since you mentioned it's a problem with data exchange.~

Discussed with @AndrejMitrovic , it's a no.

**Comment by Geod24** [comment]
This has been solved by the recent improvements in serializer and consensus.
Thanks @MukeunKim for going through the history!
