### ISSUE TITLE
[C++] Some types definitions are missing copy constructor

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#559]
The most important being, obviously, `vector`. `shared_ptr` is affected too, and anything that use RC.
I'm going to go over them soon, but there are a few upstream bugs I need to sort out first.

**Comment by omerfirmak** [comment]
I think all of our STL bindings, apart from `std::vector`, now have proper copy ctors.

**Comment by omerfirmak** [comment]
this is blocking us from going forward with `std::vector` bindings https://issues.dlang.org/show_bug.cgi?id=22505

**Comment by omerfirmak** [comment]
https://github.com/dlang/druntime/blob/1a2f2158345ece9fc3eec098a55519644bf6dfd0/src/rt/lifetime.d#L2066

this only does postblitting (if possible) after extending the array, no check for elaborate copy ctors.

**Comment by omerfirmak** [comment]
This is now blocked, waiting for a new compiler release to include both https://github.com/dlang/phobos/pull/8316 and https://github.com/dlang/phobos/pull/8315

**Comment by omerfirmak** [comment]
done in #2668
