### ISSUE TITLE
Make Enrollment Part of Consensus

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#565]
Currently in the consensus protocol the nodes are reaching consensus on a set of transactions. However, now we have another data type which has to be placed in the block, the `Enrollment`.

The nodes need to reach consensus on Enrollments too, and not just transactions. 

Therefore the Nominator needs to be changed.

Definition of Done:

- [x] Consensus should be made on a transaction set and any enrollments
- [x] If consensus is reached (externalized), create the block with the transaction set and the enrollments, and write it to the Ledger.

-----

In the future this may be changed to vote on hashes instead, rather than passing around lots of data (Transaction data, Enrollment data). But this is a more complex task, so it should become its own issue.

**Comment by Geod24** [comment]
Done in #620
