### ISSUE TITLE
Move `hasPreimage` / `getPreimage` from Validator API to Full Node API

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#566]
Related: https://github.com/bpfkorea/agora/issues/567

Currently `hasPreimage` (to be changed to `getPreimage`) is part of Validator's API.
It should be part of the full node API, as preimage need to be known to full node in order to verify signature (and it also increases data availability for them).

**Comment by Geod24** [comment]
Edited

**Comment by Waqar09-star** [comment]
how can i start agora node loacally and preform transations. Is there any testnet fucet for this blockchain
