### ISSUE TITLE
Remove usage of internal state in network tests

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#581]
Our network tests are not supposed to use internal state of the nodes, they are intended to be black box testing.
However, we currently have 7 functions exposed in the API: https://github.com/bpfkorea/agora/blob/0cdc928b09eddec41f78a2c1a36459dac532a9c6/source/agora/test/Base.d#L427-L450

Out of those 7, two of them are just exposing functions which are normally private.
While not great, it is fine and justifiable.
The extra `printLog` function is also self-evident: If a test fails, we can call it to get some extra information.

The following 4 are much less obvious: `metaAddPeer`, `createEnrollmentData`, `getPreimage` and `updateEnrolledHeight`.
The later was added very recently, and the comment about it is in the test that uses it:
https://github.com/bpfkorea/agora/blob/0cdc928b09eddec41f78a2c1a36459dac532a9c6/source/agora/test/EnrollmentManager.d#L140-L142

Definition of done:
- [ ] The documentation about `TestAPI` to include the dos and donts
- [ ] Each function exposing internals documents why it needs to be there
- [ ] Hopefully, some of the functions are removed from the public API. I can't think of a reason to have `getPreimage` and `createEnrollmentData`. I remember `metaAddPeer` had a justification in the PR, and `updateEnrolledHeight` is a temporary solution.

**Comment by linked0** [comment]
The `getPreimage` and `updateEnrolledHeight` will be deleted after merging #504 . A PR could be made by me about those functions after the merging. And new function `getPreimage` will be added by resolving the issue #567 .

**Comment by Geod24** [comment]
I don't understand, why is #504 a blocker for `getPreimage` ?
`updateEnrolledHeight` I can see why.

**Comment by linked0** [comment]
As you know, in order to test and call the `revealPreimage`, the `getPreimage` is needed. After #504 is merged, `start_block_height` is set and EnrollmentManager can determine whether it reveal  a pre-image at each round and a Node object can get a pre-image from EnrollmentManager. The `start_block_height` can be calculated after the updateEnrolledHeight is called.
