### ISSUE TITLE
gh-pages is being tested by CircleCI

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#584]
CircleCI should only test tags and vN.A.B branches.

<img width="1304" alt="Screen Shot 2020-02-24 at 10 40 29" src="https://user-images.githubusercontent.com/2180215/75124384-2ae5d080-56f2-11ea-85df-c687363d75b0.png">

**Comment by Geod24** [comment]
Just switched the following option on, let's see if it has the expected impact:

<img width="1003" alt="Screen Shot 2020-02-27 at 13 32 52" src="https://user-images.githubusercontent.com/2180215/75412496-f417f080-5965-11ea-9848-9407fbcda340.png">

**Comment by TrustHenry** [comment]
<img width="892" alt="스크린샷 2020-02-27 오후 1 38 17" src="https://user-images.githubusercontent.com/48541289/75412667-891ae980-5966-11ea-88ac-b07e935a691f.png">
I applyed it.

**Comment by Geod24** [comment]
Fixed. The UI still shows them, but they don't show as failed.
