### ISSUE TITLE
Split up the Full Node and Validator functionality into two separate classes

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#586]
Currently the `Node` class contains functionality for both a Full Node and Validator. 

The `nominator` instance should not be visible for Full Nodes, because they are not part of consensus.

Ideally we would have something like this:

```D
module agora.node.FullNode; 

import agora.api.FullNode;
class FullNode : API { ... }
```

```D
module agora.node.Validator; 

import agora.api.Validator;
import agora.node.FullNode;

class Validator : FullNode, API { ... }
```

Notice how Validator **is a** FullNode, and provides additional functionality through the agora.api.validator API interface. Also notice that `: API` in the `agora.node.FullNode` and `agora.node.Validator` modules are **different**. One refers to the one in `agora.api.FullNode`, and another refers to `agora.api.Validator`.

Definition of done:

- [x] Split the classes into two
- [x] Each class should ideally live in its own module, e.g. FullNode.d, Validator.d
- [x] Based on the configuration of the node, either `FullNode` or `Validator` should be instantiated when we want to start a node.
- [x] Fields which only belong in the Validator class should not be present in the FullNode class. For example, the `Nominator` instance should only be visible in the Validator class.
- [x] The test-suite has tests for both FullNode and Validator. It should be possible to instantiate a mix set of nodes (some are FullNode, some are Validator) and make the tests still work.

**Comment by TrustHenry** [comment]
> Based on the configuration of the node, either FullNode or Validator should be instantiated when we want to start a node.

The configuration part determines whether it operates as FullNode or Validator based on the `node.is_validator` : boolean value.

**Comment by AndrejMitrovic** [comment]
Some things that need to be thought about with regards to the test-suite:

- `TestNode` in the test-suite. Currently it's defined as `public class TestNode : Node, TestAPI`. But you will probably have to change this. Maybe you will have `TestFullNode` and `TestValidatorNode`, or maybe you could add a template parameter to TestNode like so: `public class TestNode (BaseAPI) : BaseAPI, TestAPI`. Experiment and see what is the best option.
- `TestAPIManager.createNewNode`.  It currently instantiates a `TestNode` and then appends it to the `this.nodes` array. But If we have two different node types we might have to split them into two. Maybe `this.full_nodes` and `this.validators`. Tests in the test-suite will have to be fixed too.

**Comment by TrustHenry** [comment]
We thought publickey was not required in Fullnode.
But in NetworkManager.d, we are using the publicKey to identify nodes.
https://github.com/bpfkorea/agora/blob/2b787c8fde8999854347072134e0bc9c34e58399/source/agora/network/NetworkManager.d#L66
We have to think again here.
Do you want to continue using the publickey to identify the node client or is there another alternative? e.g.) IP address

**Comment by AndrejMitrovic** [comment]
It appears we don't really use the PublicKey, so yes you could change it to use the address of the node.

**Comment by TrustHenry** [comment]
> It appears we don't really use the PublicKey, so yes you could change it to use the address of the node.

Using IP addresses makes it easy to troubleshoot
However, there can be a disadvantage of having only one node configuration on the same IP.

**Comment by AndrejMitrovic** [comment]
The address should already contain the port. So you can just use it as a string (it's currently defined as a string).

**Comment by TrustHenry** [comment]
We can avoid duplicating the same node address by using node address and port.
I think there could be another problem with node address and port duplication in the virtual and real networks, but I won't consider it this time because it's more complicated. Also, IPV6 response

**Comment by AndrejMitrovic** [comment]
What do you mean "duplication"?

**Comment by TrustHenry** [comment]
The duplicate I wrote here means that IP and Port are the same.
But there's no problem if we only use RealNetwork, or RealIP.
For a moment, I thought of a mix of virtual and real networks.
If so, we thought MAC addresses were a better alternative.
However, it seems to go beyond the topic of this issue, so I will make a new PR by modifying the node address and port.

**Comment by AndrejMitrovic** [comment]
I understand. This is beyond my level of expertise though.
