### ISSUE TITLE
Network manager needs to be reworked

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#587]
When we implemented it the goal was to support Full Nodes (first milestone). Full Nodes connect to a minimum number of clients via the `min_listeners` config option.

But Validators should not have this config option. The minimum number of clients it connects to is the number of nodes in its quorum configuration. They do not care about connecting to random Full Nodes, it is Full Nodes which care about connecting to Validators & other Full Nodes.

Also from #644:

There are various sets inside, and it's all a bit too complicated to reason about:

- todo_addresses
- known_addresses
- connecting_addresses

In addition to that, some of the initialization in `start()` should be moved to the constructor so the class is always in a ready-to-go state. Otherwise it's possible some incoming requests are routed to the NetworkManager while `start()` hasn't yet been called, which leaves it in an inconsistent state.

**Comment by AndrejMitrovic** [comment]
Another issue: we are currently not handling connection failures. See also https://github.com/bpfkorea/agora/pull/643

**Comment by AndrejMitrovic** [comment]
I will fold https://github.com/bpfkorea/agora/issues/644 into this one.

**Comment by Geod24** [comment]
Also, currently the quorum set is derived before the network discovery, which needs to be reworked to allow for adjusting the qset in real time: https://github.com/bpfkorea/agora/blob/5ffc4574b99ebafc7817801ad2770ea2253cd126/source/agora/consensus/protocol/Nominator.d#L111

**Comment by AndrejMitrovic** [comment]
I will add to the notes that I'm currently working on this too. But as always, the other bugs keep slashing my tires. :>

**Comment by AndrejMitrovic** [comment]
This has a race condition:
 https://github.com/bpfkorea/agora/blob/9d56a9e080b9978111e9e1e5a3735881e7fb00e2/source/agora/network/NetworkManager.d#L380

There may be multiple fibers trying to connect to the very same address.

This will all be fixed once this is redesigned to make it side-effect free. Only the main fiber should handle adding / removing peers from its maps, and this fiber should spawn other worker fibers to connect to each client. And it will know not to spawn multiple fibers for the same client.

For example currently this error is sometimes visible:

> Full error: core.exception.AssertError@source/agora/test/Base.d(510): Trying to access node at address 'Validator #3 (GCAW...HKP5)' without first creating it

The error is a bit misleading actually. The validator **was** registered, but then it got unregistered. And because of the current design in NetworkManager, it seems we call `getClient` very often.

I'll assign this to myself tomorrow.
