### ISSUE TITLE
Get rid of ocean's BitArray in BitField

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#600]
Ocean's `BitArray` is just a pain to work with, and a thorn in our side.
It lacks attribute, duplicates most of what `BitField` is doing, and doesn't expose proper `const`-correct constructors.

**Comment by AndrejMitrovic** [comment]
Yes. But the Phobos implementation had its own quirks that lead to some issues with serialization. I did not have luck finding alternatives..

**Comment by Geod24** [comment]
I was thinking of just rolling our own, it shouldn't be too much work.

**Comment by AndrejMitrovic** [comment]
I considered that too. But I didn't have much time left in the sprint, so I picked ocean's sloppy implementation. (I think that code even dates back to Tango probably).

**Comment by Geod24** [comment]
I'll get to it soon, because it was blocking progress on the deserialization work.
