### ISSUE TITLE
System integration test need `SecretKey` of nodes as arguments

### ISSUE THREAD

**Issue by MichaelKim20** [bosagora/agora#630]
The system integration test need addresses of nodes.
and It needs `SecretKey` too

The `config.yaml` is recommended, but since the dockers do port forwarding, additional node addresses should be specified even if `config.yaml` is used.
Therefore, it is necessary to implement a method of entering the address and secret-keys as an argument together.

**Comment by Geod24** [comment]
Why does it need the secret keys ?

**Comment by TrustHenry** [comment]
In order to test an enrollment in a system integration test, it is necessary to sign an enrollment message.
The system integration test code does not seem to have a way to get the secret key of config.

**Comment by TrustHenry** [comment]
This only test for behavior that is visible to non-validators as a result of their own action.
We close this issue because we only do the black box test here.
