### ISSUE TITLE
SCP: Handle uninitialized envelopes gracefully

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#657]
According to [this log](https://app.circleci.com/pipelines/github/bpfkorea/agora/1442/workflows/69e16bb6-a530-4e59-a028-2a0b94c87267/jobs/1562/parallel-runs/0/steps/0-106), [this assert](https://github.com/bpfkorea/agora/blame/40dd4a19da9a83dff73f42c39edb3312e411bca0/source/scpd/types/Stellar_SCP.d#L118) is reached from [this place](https://github.com/bpfkorea/agora/blob/4523cf091d7ac29426a943c0618727434f738796/source/scpp/src/scp/Slot.cpp#L149).

Of course we only see it happening when SCP has a fatal error, so it's hard to test. Sending an envelope with the wrong `type` might just do it.
This is especially sneaky because of the way logging happens: it seems the message is not flushed by docker early enough (?), see:
```
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626252403Z 2020-03-05 06:04:19,624 Fatal [SCP] - SCP context:
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626466511Z 2020-03-05 06:04:19,625 Fatal [SCP] - {
[30 or so lines later...]
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626764975Z       [
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626769022Z          1583388259,
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626773106Z          "{ENV@GA3DM |  i: 1 | PREPARE | D: c04b99 | b: (1,4ff40d) | p: (1,4ff40d) | p': (<null_ballot>) | c.n: 1 | h.n: 1 }",
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626364261Z core.exception.AssertError@source/scpd/types/Stellar_SCP.d(118): Assertion failure
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626777689Z          true
node-2_1_82f4bdff35b4 | 2020-03-05T06:04:19.626801221Z       ],
```
Here we can see that the "Assertion failure" message should be between the first two lines, but it is not.

**Comment by Geod24** [comment]
@omerfirmak : If you could take a look at the other data structures that could potentially trip asserts that'd be great.

**Comment by omerfirmak** [comment]
Checked to see if other `fromString`/`fromBinary` functions could introduce bad objects and they seemed OK to me. Code that handles existing objects should still fail hard IMO, we should only be able recover from creating bad ones.
