### ISSUE TITLE
SCP binding structure layouts might not match

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#661]
Currently we have:

```D
static assert(BallotProtocol.sizeof == 136);
```

However, using one of the tricks in https://stackoverflow.com/questions/20979565/how-can-i-print-the-result-of-sizeof-at-compile-time-in-c I think I found a mismatch:

```C++
template<int s> struct Wow;
struct foo {
    int a,b;
};

static void test ()
{
    Wow<sizeof(stellar::BallotProtocol)> wow;
}
```

Emits:

```
/mnt/c/dev/agora/source/scpp/src/scp/BallotProtocol.h: In function ‘void test()’:
/mnt/c/dev/agora/source/scpp/src/scp/BallotProtocol.h:281:42: error: aggregate ‘Wow<160> wow’ has incomplete type and cannot be defined
  281 |     Wow<sizeof(stellar::BallotProtocol)> wow;
```

So the size is actually 160, if this is to be believed.

I think the root cause of these mismatches is our current definition of C++ wrappers like `map` & `set` in https://github.com/bpfkorea/agora/blob/dbd8a5cff0758cf13e59790dcbcc5100b63ba065/source/scpd/Cpp.d#L118-L122

This doesn't seem to be correct. On the C++ side the size of a `std::map` is 48 bytes. But on the D side it's `void*[3]` which is 24 bytes.

Am I wrong here? And is there a `pragma(msg` or something I can use in C++? There is `static_assert`, but funnily enough it doesn't print out the value when the assertion fails (duh).

CC @Geod24

**Comment by AndrejMitrovic** [comment]
I think it probably doesn't matter much because we are passing everything by reference rather than by value.

I've just tried to change the `map` & `set` sizes on the D side, and nothing changes. The tests still pass.

**Comment by Geod24** [comment]
Because passing by value simply does not work :D

**Comment by Geod24** [comment]
#505 should solve this, hence closing as duplicate.
