### ISSUE TITLE
`BanManager.banFor` accepts negative values

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#665]
https://github.com/bpfkorea/agora/blob/dbd8a5cff0758cf13e59790dcbcc5100b63ba065/source/agora/common/BanManager.d#L155-L186

Shouldn't it take `ulong` instead of `long` ?
Also we should probably check that the value fits in a `time_t` (it fails on x86).

**Comment by AndrejMitrovic** [comment]
~It should also use the monotonic clock.~

Edit: this comment was outdated. Please see #1226 for the associated issue.
