### ISSUE TITLE
[upstream] DUB does globbing before preGenerateCommands

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#671]
See upstream issue and related: https://github.com/dlang/dub/issues/1857

This would be so much nicer: https://github.com/bpfkorea/agora/pull/670

**Comment by omerfirmak** [comment]
Upstream PR: https://github.com/dlang/dub/pull/2035
With this, https://github.com/bpfkorea/agora/pull/670 can be merged

**Comment by Geod24** [comment]
Yay
