### ISSUE TITLE
Add validation checking code for pre-images being revealed

### ISSUE THREAD

**Issue by linked0** [bosagora/agora#694]
In current implementation of managing enrollments and pre-images, there is no code checking validity of pre-images. The validator set(`ValidatorSet`) must check validity of pre-images being received from several validators.

Definition of Done:
- [x] The validator set checks incoming pre-images with enrollment data

How to implement:
* The validator set hashes a random seed of an enrollment by the difference in the height between the random seed and the incoming pre-image, and compares the hash value and one of the pre-image.
* The `Enrollment` structure must have the height of its random seed for checking the validity.

**Comment by Geod24** [comment]
Fixed by https://github.com/bpfkorea/agora/pull/851
