### ISSUE TITLE
Logging should not expose any secret keys

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#719]
```
node-2_1_37a10f21eb7b | 2020-04-02T01:15:19.329464369Z 2020-04-02 01:15:19,329 Trace [agora.node.Node] - Config is: { banman: { max_failed_requests: 10, ban_duration: 86400 }, node: { is_validator: true, min_listeners: 2, max_listeners: 10, address: "0.0.0.0", port: 4826, key_pair: { address: GA3DMXTREDC4AIUTHRFIXCKWKF7BDIXRWM2KLV74OPK2OKDM2VJ235GN, secret: 0xad53d56c28a7d573fcd7a534b3f1a2117e5156898b4a3c9322c0c520715e36364bdcf8f0442d0de2ff5f954e092c4d1cbc43ae832b336eb7e80da9a7ba45c911, seed: SAI4SRN2U6UQ32FXNYZSXA5OIO6BYTJMBFHJKX774IGS2RHQ7DOEW5SJ }, retry_delay: 1500, max_retries: 5, timeout: 1000, data_dir: ".cache" }, admin: { enabled: false, address: "127.0.0.1", port: 2827 }, network: ["http://node-0:2826", "http://node-1:3826"], dns_seeds: [], quorum: { threshold: 2, nodes: [GBUVRIIBMHKC4PE6BK7MO2O26U2NJLW4WGGWKLAVLAA2DLFZTBHHKOEK, GBJABNUCDJCIL5YJQMB5OZ7VCFPKYLMTUXM2ZKQJACT7PXL7EVOMEKNZ, GA3DMXTREDC4AIUTHRFIXCKWKF7BDIXRWM2KLV74OPK2OKDM2VJ235GN], quorums: [] }, logging: { log_level: 0 } }
```

> secret: 0xad53d56c28a7d573fcd7a534b3f1a2117e5156898b4a3c9322c0c520715e36364bdcf8f0442d0de2ff5f954e092c4d1cbc43ae832b336eb7e80da9a7ba45c911, seed: SAI4SRN2U6UQ32FXNYZSXA5OIO6BYTJMBFHJKX774IGS2RHQ7DOEW5SJ

This is a security issue. If someone finds a bug in Agora and wants to file a bug then they might provide us with a log dump. The log should not emit any private keys.

Rather than just removing its output, I can think of alternatives:
- Emit a hashed version of the key. It may help with logging in case that key appears in multiple error messages.
- Emit a shortened pretty-printed version of the key.

@Geod24 any thoughts?

**Comment by Geod24** [comment]
> Emit a hashed version of the key. It may help with logging in case that key appears in multiple error messages.

True. Sounds like a plan.
