### ISSUE TITLE
Merge the catchup code and the startup code for enrollment/preimage/utxo_set

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#734]
Currently the periodic catch does this:
https://github.com/bpfkorea/agora/blob/05bfe591aec457544bfe9fc8b799f592d4d6b303/source/agora/network/NetworkManager.d#L208-L239

While the constructor of `Ledger` does this:
https://github.com/bpfkorea/agora/blob/05bfe591aec457544bfe9fc8b799f592d4d6b303/source/agora/node/Ledger.d#L93-L117

There's an obvious duplication here, that we should address.

**Comment by linked0** [comment]
There are two options to implement it.
@Geod24 Do you mean the first option as the goal of this issue?

**First option**
```
public void startPeriodicCatchup (Ledger ledger, bool delegate() @safe isNominating) 
{ 
   this.taskman.runTask( 
   () 
   { 
       // periodic task 
       while (1) 
       { 
           while(auto block = this.ledger.getNextBlock()) <======                                                                         
               ledger.acceptBlock(block);                 <======
                                                                          
           this.getBlocksFrom( 
               ledger.getBlockHeight() + 1, 
               blocks => blocks.all!(block => 
                   // do not alter the state of the ledger if 
                   // we're currently nominating 
                   !isNominating() && ledger.acceptBlock(block))); 

           this.taskman.wait(2.seconds); 
       } 
   }); 
} 
```

After writing the code above, we can delete the code about reading block, and updating utxos and validators, in the constructor of the `Ledger`.

**Second option**
```
private void rebuildUTXOAndValidatorSet (ref Block gen_block)
{
    foreach (height; 0 .. this.last_block.header.height + 1)
    {
        Block block;
        this.storage.readBlock(block, Height(height));
        this.acceptBlock(block);
    }
}
```

With the code, we can remove the duplicate function calls from the `rebuildUTXOAndValidatorSet`, which are already called in the `validateBlock` and `addValidatedBlock` which are called in the `acceptBlock` in turn.

**Comment by linked0** [comment]
The PR #1505 is approved and merged as the final code of this issue by @Geod24. So I close this.
