### ISSUE TITLE
Change the way we store Enrollments

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#735]
Currently we add `Enrollment` to the `EnrollmentManager` when they are received but before they are validated:
https://github.com/bpfkorea/agora/blob/05bfe591aec457544bfe9fc8b799f592d4d6b303/source/agora/node/Node.d#L507-L518

Then consensus is made on them. This has a few issues:
- It is impossible to replace an enrollment, lest the user change their key (so there's a 2 week waiting period);
- This table is never cleaned up;
- We mix the data we use before and after consensus, which is error-prone.
- `addValidatedBlock` does not add Enrollments, only update their height, which mean catch-up is broken.

It would be best to have those two data set apart, and only have active enrollments in the EnrollmentManager. The separation should probably be similar to transaction pool / UTXO set.

Definition of Done:
- [x] Make the way to sotre Enrollments like the way similar to to transaction pool / UTXO set.
- [x] Clean up the table when a enrollment is expired.

**Comment by linked0** [comment]
Among the issues to be resovled, some issues as follows can be split into another issue.
- It is impossible to replace an enrollment, lest the user change their key (so there's a 2 week waiting period);
- This table is never cleaned up;

Those can be handled after chaning the way we store the Enrollments. So I will create new issue named like "Add the feature to change or delete enrollments stored".

**Comment by linked0** [comment]
After the PR #748 , there will be more PRs for tasks as follows.

- [x] Refactor the relations between classes related to the enrollment process and other classes that use the classes(including the change of the name and function modifier of member functions.
- [x] Refine the API endpoints related to the enrollment process, for example, `getPreimage`.
- [ ] Remove table in the `EnrollmentManager`.
- [x] Refine test code in the `test.EnrollmentManager` package.

**Comment by Geod24** [comment]
@linked0 : I think we can reasonably consider this closed. Could you open issues for any remaining tasks so they can be addressed in the next sprint ?

**Comment by linked0** [comment]
> @linked0 : I think we can reasonably consider this closed. Could you open issues for any remaining tasks so they can be addressed in the next sprint ?

There is one remaining task which is to remove the table from the `EnrollmentManager`. I will create an issue and address it in the next sprint.
