### ISSUE TITLE
Problem with @safe and hashing self-referential structs

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#738]
```D
@safe unittest
{
    struct Foo
    {
        Foo[] foo;
    }

    Foo foo;
    hashFull(foo);
}
```

> source/agora/common/Hash.d(181,17): Error: `@safe` function `agora.common.Hash.hashPart!(Foo).hashPart` cannot call `@system` function `agora.common.Hash.hashPart!(Foo).hashPart`

The problem is:

- hashPart for arrays is @safe:
https://github.com/bpfkorea/agora/blob/05bfe591aec457544bfe9fc8b799f592d4d6b303/source/agora/common/Hash.d#L178

But it calls https://github.com/bpfkorea/agora/blob/05bfe591aec457544bfe9fc8b799f592d4d6b303/source/agora/common/Hash.d#L126

And this one is not `@safe`.

cc @Geod24

**Comment by AndrejMitrovic** [comment]
Safety should be inferred here, hashPart is templated. But somehow it's not safe..

**Comment by Geod24** [comment]
Upstream bug ? Can you reduce it ?

**Comment by AndrejMitrovic** [comment]
I'll reduce it soon.

**Comment by AndrejMitrovic** [comment]
https://issues.dlang.org/show_bug.cgi?id=20724

**Comment by Geod24** [comment]
Moved to #561
