### ISSUE TITLE
Change SCP's Signature definition to be a fixed-size type

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#744]
Currently it's implemented as an std::vector: `opaque_vec!64`. It seems rather pointless to have to allocate memory just in order to be able to pass pointers to it, when the referenced memory should always be 64 bytes (in its current implementation).

We should replace this definition with a fixed-length array, matching the one in `agora.common.Types`, which is a `BitBlob!512`, in other words fixed-length array of 64 bytes.

This is blocking #548.

**Comment by Geod24** [comment]
Do you know why it's this way ? Did upstream want to abstract the signature size, originally ? That's my best guess.

**Comment by AndrejMitrovic** [comment]
I wish I knew why. It really doesn't seem efficient to do it this way. But maybe they are more explicit with acquire/release of memory and they don't want to increase the size of the SCPStatement structure?

**Comment by MichaelKim20** [comment]
I have confirmed that the declaration was made as follows.
``` C++
using Signature = xdr::opaque_vec<64>;
```
I will change it as follows.
``` C++
using Signature = xdr::opaque_array<64>;
```

**Comment by MichaelKim20** [comment]
@AndrejMitrovic Do you think this is completely resolved now?

**Comment by AndrejMitrovic** [comment]
Yes, feel free to close it.
