### ISSUE TITLE
Block with height 0 also needs to be verified

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#747]
This code verifies that the first block equals the genesis block:

https://github.com/bpfkorea/agora/blob/1dcc4de9cfb7adfe317c2571c2b5cd3777683156/source/agora/consensus/Validation.d#L852-L855

But it also assumes that the definition of `GenesisBlock` is correct. It should verify all the rules we have in place: merkle root, transaction limit, etc..

**Comment by Geod24** [comment]
Prerequisite to https://github.com/bpfkorea/agora/issues/821

**Comment by TrustHenry** [comment]
Currently, the Genesis block is divided into two networks:

```
/// Genesis block as used by most unittests
private immutable Block UnitTestGenesisBlock =
{
    header:
    {
        prev_block:  Hash.init,
        height:      0,
        merkle_root: UnitTestGenesisMerkleRoot,
    },
    txs: [ UnitTestGenesisTransaction ],
    merkle_tree: [ UnitTestGenesisMerkleRoot ],
};
```

```
/// The genesis block as defined by CoinNet
private immutable Block CoinNetGenesisBlock =
{
    header:
    {
        prev_block:  Hash.init,
        height:      0,
        merkle_root: CoinNetGenesisMerkleRoot,
    },
    txs: [ CoinNetGenesisTransaction ],
    merkle_tree: [ CoinNetGenesisMerkleRoot ],
};
```

**Comment by TrustHenry** [comment]
Items that can be verified in the Genesis block are:

- merkle_root
- height
...

**Comment by AndrejMitrovic** [comment]
signature verification, double spends, and that any enrollments refer to freeze tx's in that block.
