### ISSUE TITLE
Bindings for `std::unordered_map` are wrong

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#753]
```c++
#include <unordered_map>
char (*__kaboom)[sizeof(std::unordered_map<int, int>)] = 1;
```
(Trick taken from https://stackoverflow.com/a/35261673/1021344)

This will print:
```console
clang++ uno.cpp
uno.cpp:3:8: error: cannot initialize a variable of type 'char (*)[40]' with an rvalue of type 'int'
char (*__kaboom)[sizeof(std::unordered_map<int, int>)] = 1;
       ^                                                 ~
1 error generated.
```

So the size is 40. However our bindings only have [*a single pointer*](https://github.com/bpfkorea/agora/blob/eb4ab3b0083c72fa2b7eb815ad2cd7a7290ffad4/source/scpd/Cpp.d#L85-L107).

That's on OSX with the latest clang++. I expect things to be wrong on other platforms too.

**Comment by AndrejMitrovic** [comment]
Yes we use a fake wrapper. We `new` it on the C++ side and return a pointer, and then the D struct just stores that pointer.

The issue with the binding was, how do you know for sure how big the aggregate is? You would need to know the internals, or introspect with sizeof() at the C++ side. And each stdlib / platform might be different..

**Comment by Geod24** [comment]
Was there something in the bindings that was dependent on the size ? Because that issue potentially affects all containers, but from what I've seen with `vector` for example, it's not a problem. Vector is just 3 pointers, and I expect `unordered_map` to behave the same. Druntime also has pointers for hashmap so that the size is constant. The only time it becomes an issue is, I think, the special case that is made for `std::vector<bool>`.

**Comment by AndrejMitrovic** [comment]
Ah on second look it's used as a field in `QuorumTracker`. Yeah we should fix the bindings.

It's not causing any issues right now because it's always passed by ref.

**Comment by AndrejMitrovic** [comment]
> Vector is just 3 pointers, and I expect unordered_map to behave the same. 

Internally it's implemented as a hashtable. But that implementation by itself is complicated, e.g.:

```C++
  template<typename _Key, typename _Value, typename _Alloc,
	   typename _ExtractKey, typename _Equal,
	   typename _H1, typename _H2, typename _Hash,
	   typename _RehashPolicy, typename _Traits>
class _Hashtable
: public __detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal,
			       _H1, _H2, _Hash, _Traits>,
  public __detail::_Map_base<_Key, _Value, _Alloc, _ExtractKey, _Equal,
			 _H1, _H2, _Hash, _RehashPolicy, _Traits>,
  public __detail::_Insert<_Key, _Value, _Alloc, _ExtractKey, _Equal,
		       _H1, _H2, _Hash, _RehashPolicy, _Traits>,
  public __detail::_Rehash_base<_Key, _Value, _Alloc, _ExtractKey, _Equal,
			    _H1, _H2, _Hash, _RehashPolicy, _Traits>,
  public __detail::_Equality<_Key, _Value, _Alloc, _ExtractKey, _Equal,
			 _H1, _H2, _Hash, _RehashPolicy, _Traits>,
  private __detail::_Hashtable_alloc<
__alloc_rebind<_Alloc,
	       __detail::_Hash_node<_Value,
				    _Traits::__hash_cached::value>>>
```

So what's the easiest thing to do here? Try to bind to all of this stuff, or just declare `align(1): ubyte[40] _data;`?

**Comment by AndrejMitrovic** [comment]
These are some of its fields:

```C++
private:
  __bucket_type*		_M_buckets		= &_M_single_bucket;
  size_type			_M_bucket_count		= 1;
  __node_base		_M_before_begin;
  size_type			_M_element_count	= 0;
  _RehashPolicy		_M_rehash_policy;

  // A single bucket used when only need for 1 bucket. Especially
  // interesting in move semantic to leave hashtable with only 1 buckets
  // which is not allocated so that we can have those operations noexcept
  // qualified.
  // Note that we can't leave hashtable with 0 bucket without adding
  // numerous checks in the code to avoid 0 modulus.
  __bucket_type		_M_single_bucket	= nullptr;
```

**Comment by Geod24** [comment]
@omerfirmak : I guess that's a good place to start ?
