### ISSUE TITLE
System integration test continues test even if linking failed

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#766]
While testing #756 we've noticed that the system integration test does not seem to check for errors when it's building Agora. For example, when running:

```
$ ./ci/system_integration_test.d
```

In the list of errors is:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...
```

And the the rest of the errors:

```
> node-0_1  | 2020-04-20T05:52:13.184020300Z 2020-04-20 05:52:07,162 Trace [agora.network.NetworkClient] - Not Found (404)
```

Obviously we cannot connect to a Node if the Node binary wasn't even compiled or ran.

**Comment by Geod24** [comment]
Is it the node or the client that fails to link ? Regarding the client, it's... A feature. But if it was the node, then it's definitely a bug.

**Comment by AndrejMitrovic** [comment]
It's very hard to tell apart.

Also, I really dislike this whole exclude modules stuff.. It's hacky and it's wasting everyone's development time chasing down these bugs non-stop.

**Comment by AndrejMitrovic** [comment]
Aha, so this might be the issue of the client not linking, whereas the 404s are from the nodes communicating with each other.

Henry and me will continue debugging the 404 error.

Currently the system integration tests work like this:

- Build the agora nodes
- Run the agora nodes
- Build & Run the system integration test module

How about we change it to:
- Build the agora nodes
- Build the system integration test executable (if it fails to link, this is the only error we'll see)
- Run the nodes
- Run the system integration test

I added a call to `waitForDiscovery` recently, so this change should be fine I think?

**Comment by Geod24** [comment]
@AndrejMitrovic : Should we still pursue this ? Nodes are spawned first to reduce run time (nodes need to initialize their state which is slower than compiling). I don't think it makes sense to change it. Thoughts ?
