### ISSUE TITLE
Constructor failure isn't logged anywhere in the tests

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#769]
If the call to a Node's constructor fails it will not be emitted anywhere in the test-suite output. The issue is in the current design of `printLogs` in `Base.d`. It actually calls each node's `printLog()` method to print out the log, but this method won't be available if the node's ctor fails (the node will be null).

In reality we don't actually need the node object itself, because all of the logs are `static`. It's just that we needed some way of accessing them from the unittest thread(s).

**Comment by Geod24** [comment]
It's logged now, but maybe not the full logs. Such a failure should be extremely rare though, so do we need the full logs ?

**Comment by AndrejMitrovic** [comment]
No we don't need the full logs.
