### ISSUE TITLE
system integration test node is connecting to itself

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#772]
While writing a test with 8 **total** nodes, I've noticed this in the log:

> node-0_1  | 2020-04-27T01:55:50.623040704Z 2020-04-27 01:55:50,621 Info [agora.network.NetworkManager] - Discovery reached. 8 peers connected.

And also: 

> node-0_1  | 2020-04-27T01:55:49.167923309Z 2020-04-27 01:55:49,137 Info [agora.network.NetworkManager] - Established new connection with peer: GBCVDA6EJDTC76WP552UX4NM7ENRX6AK4JW27GKVHVOCLRWOGQES3UPP

This is the node's key, so the node is connecting with itself. It probably has something to do with IP filtering (banning).

I've also noticed the nodes are using several different address types to connect to:

```
ode-0_1  | Establishing connection with http://0.0.0.0:7826...
node-0_1  | Establishing connection with http://node-0:2826...
node-0_1  | Establishing connection with http://node-6:8826...
node-0_1  | Establishing connection with http://node-1:3826...
node-0_1  | Establishing connection with http://0.0.0.0:8826...
node-0_1  | Establishing connection with http://0.0.0.0:3826...
node-0_1  | Establishing connection with http://node-5:7826...
node-0_1  | Failed to connect to 172.21.0.8:6826: refused
node-0_1  | Failed to connect to 172.21.0.6:4826: refused
node-0_1  | Failed to connect to 172.21.0.7:5826: refused
```

So it tries connecting with `node-*:*`, `0.0.0.0:*`, and `172.21.0.*:*`, the latter of which are probably IPs assigned by docker.

**Comment by Geod24** [comment]
The nodes now ban themselves, so this issue has been solved.
