### ISSUE TITLE
Test Server Needed For Admin Interface

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/agora#788]
We need to create a test server in order to test the Admin Interface.

**Comment by TrustHenry** [comment]
Which test server does it use?

**Comment by bpalaggi** [comment]
@TrustHenry This will use a new server that @Geod24 will set up sometime in the near future.

**Comment by Geod24** [comment]
Deployed on my private server for the time being. It's essentially an endpoint that calls [`parseConfigString`](https://github.com/bpfkorea/agora/blob/432ee2d659856b172a21c33c3e39270b9741b996/source/agora/common/Config.d#L201-L207) and returns the Exception's message if any.

Moving to testing until we hear back.
