### ISSUE TITLE
Replace setGenesisBlock / genesis config with hardcoded blocks

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#821]
As discussed with @Geod24 today. We should come up with an alternative to user-configurable genesis blocks. Initially we went with this solution to allow having a different genesis block for unittests / integration tests / testnet / coinnet. 

The problem is that a corrupt config file or just a user typo could cause the node to use a different genesis block.

One alternative was to use `version()` blocks and then build Agora with `-version=CoinNet`, `-version=TestNet`, but that is problematic because we then need to ship multiple binaries.

A better alternative suggested by @Geod24 is to have a runtime choice between several pre-configured genesis blocks. 

So instead of having `config.genesis_block`, we would have `./agora --mode=coinnet` | `./agora --mode=unittest` or something to that effect. It could also be a config option, but the point is that it's not a hex dump of a block but a choice with a limited pre-configured number of options.

**Comment by Geod24** [comment]
So:
```sh
$ agora --testnet
# OR
$ agora --well-know-net
# The default is
$ agora --mainnet
```

Or something similar. I think we should keep `testnet` for, heh, testnet, because that's what people expect, and use a very unambiguous and non-similar name for the integration test (it's most likely to be only written in scripts, and will stand out).

**Comment by AndrejMitrovic** [comment]
Do we want it to be a default? We probably don't want to accidentally run on mainnet by mistake.

I remember the days [at our prev employer] where we would `scp` binaries and then run them, but without it being obvious we're running on a test system or a live one. There were a few times when we ran test apps on the live system by mistake. :P

**Comment by Geod24** [comment]
We should brainstorm it. I think the main difference between agora and the case you mentioned is the intended audience: `agora` is likely to be run by non-developer, hence the defaults need to "just work" as much as possible. But if we make the error message obvious enough I guess it could work, too.

**Comment by Geod24** [comment]
Raising to prio-high because it's blocking us AFAIU.

**Comment by AndrejMitrovic** [comment]
Some notes about this issue:
- Any time we change the built-in integration test genesis block, it may end up breaking all existing tests.
- We need to include Enrollments in the genesis block, it's hard to pre-determine how many so it works well with all tests (including the network tests).
