### ISSUE TITLE
Implement a lock on the caching directory

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#829]
It is way too easy to start two instances of the node in the same working directory and accidentally corrupt data. And someone could hypothetically spend a couple hours investigating why.

**Comment by AndrejMitrovic** [comment]
Ocean already has support for locking, so we could take advantage of that.

**Comment by AndrejMitrovic** [comment]
> someone could hypothetically spend a couple hours investigating why

ouch :>

**Comment by Geod24** [comment]
> ouch :>

Well there *was* still [a bug](https://github.com/bpfkorea/agora/pull/831), but my life would have been easier if there was only one.

**Comment by Geod24** [comment]
> Ocean already has support for locking, so we could take advantage of that.

Does it work on Windows though ?

**Comment by AndrejMitrovic** [comment]
lol I forgot about that
