### ISSUE TITLE
Add checks for signed long overflow 

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#830]
While working on #826 I've tried to pass `ulong.max` to SQLite in the call to:

```D
this.db.execute("DELETE FROM validator_set WHERE " ~
                    "enrolled_height <= ?",
                    block_height - Enrollment.ValidatorCycle);
```

However this errors with:

```
2020-05-13 17:19:53,67 Error [agora.consensus.ValidatorSet] - Database operation error: Conversion positive overflow
```

The database is defined as:

```D
this.db.execute("CREATE TABLE IF NOT EXISTS validator_set " ~
    "(key TEXT PRIMARY KEY, val BLOB NOT NULL, " ~
    "enrolled_height INTEGER, preimage BLOB)");
```

The `INTEGER` type is actually a signed type in SQLite. There's more info here:
http://jakegoulding.com/blog/2011/02/06/sqlite-64-bit-integers/

We should examine our usage of SQLite and try to add some checks in place, or try to clamp down the value to something SQLite will accept.

**Comment by AndrejMitrovic** [comment]
I found another issue: 

https://github.com/bpfkorea/agora/blob/e72c0fbd60013b02303a705ce3d3718372081440/source/agora/consensus/ValidatorSet.d#L171

This returns a `size_t`. It should return a `ulong`.

**Comment by Geod24** [comment]
Related to: https://github.com/bpfkorea/agora/issues/836#issuecomment-630574825

**Comment by hewison-chris** [comment]
This shows how sqlite3 uses flexible typing:-
```
sqlite> CREATE TABLE big_numbers (i INTEGER);
sqlite> insert into big_numbers values (9223372036854775807);
sqlite> insert into big_numbers values (9223372036854775808);
sqlite> select * from big_numbers;
9223372036854775807
9.22337203685478e+18
sqlite> select typeof(i) from big_numbers;
integer
real
```
After version 3.37.0 you can use `create table strict` to prevent this.
We are using version 3.32 at the moment.
Not sure this is really a problem for us yet? Need to see how it behaves through the driver.

**Comment by hewison-chris** [comment]
No `unsigned integer` type exists in sqlite. We could add `CHECK` constraint that values are not negative.

**Comment by hewison-chris** [comment]
I added this unit test to d2sqlite3/source/tests.d to check when using bind parameters in statement:
```
unittest // INTEGER tests
{
    import std.conv;
    auto db = Database(":memory:");
    db.run("CREATE TABLE big_numbers (i INTEGER);");
    void checkNumber (ulong ul)
    {
        db.execute("INSERT INTO big_numbers VALUES (?)", ul); // throws here if > long.max
        auto results = db.execute("SELECT * FROM big_numbers");
        auto row = results.front;
        assert(row.peek!ulong(0) == ul);
    }
    checkNumber(long.max);
    assertThrown!ConvOverflowException(checkNumber(long.max + 1));
}

```

**Comment by hewison-chris** [comment]
The question is do we need to store numbers greater than long.max? 
```
9223372036854775807 = long.max
49500000000000000 = max coin units (Amount uses this as max valid value)
```

If not then the current behavior is ok because we will throw if it is attempted.

However it may be better if we used a type which is unsigned but with max the same as `long.max`.
Any opinions on this?

**Comment by hewison-chris** [comment]
> I found another issue:
> 
> https://github.com/bpfkorea/agora/blob/e72c0fbd60013b02303a705ce3d3718372081440/source/agora/consensus/ValidatorSet.d#L171
> 
> This returns a `size_t`. It should return a `ulong`.

This has since been updated to return `Height` so is ok now.

**Comment by hewison-chris** [comment]
I checked all our `select` and `delete` queries and none of them would ever need to query with a `ulong.max` (or even value > `long.max`) in the `bind` parameter.
