### ISSUE TITLE
Improve usage of SQLite for UTXO & validator DBs

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#836]
We are currently using SQLite for a bunch of node metadata. The intent was to have something that is extremely reliable. However it lead to less-than-pleasant code.

There are a few issues:
- The code is neither `@safe` nor `nothrow` which forces us to liter the code with `try / catch`, `@trusted`, and `scope (failure) assert(0);`, e.g. [here](https://github.com/bpfkorea/agora/blob/d396373156c94621b3d41cbe124ce8bc2dfca873/source/agora/consensus/data/UTXOSet.d#L409-L414), [here](https://github.com/bpfkorea/agora/blob/d396373156c94621b3d41cbe124ce8bc2dfca873/source/agora/consensus/EnrollmentPool.d#L119-L130), or [here](https://github.com/bpfkorea/agora/blob/d396373156c94621b3d41cbe124ce8bc2dfca873/source/agora/consensus/ValidatorSet.d#L103-L123).
- There is no usage of transactions, so the underlying problem of consistency is not fixed. For example, if we were to crash during `addValidatedBlock` (think power outage), it is very likely our node wouldn't recover from this, nor be able to detect the failure.
- There are some blob being stored in the DB. I don't know if it's the most sensible choice. Should we take the storage overhead and store binary data as hex string ? For hash it would make sense.
- [In the ValidatorSet](https://github.com/bpfkorea/agora/blob/d396373156c94621b3d41cbe124ce8bc2dfca873/source/agora/consensus/ValidatorSet.d#L103-L116), the pre-image info is duplicated. The `random_seed` is actually the first pre-image and could be treated as such. There is an odd mix of relational and non-relational data, were we store some of the data from the enrollment non-serialized, and the whole enrollment serialized as well.

My original thought was to simplify all of this and use memory, and just commit from time to time. @AndrejMitrovic pointed out that SQLite in fact has many advantages, which solve most of our problems. So the fault probably lies in our binding / usage.

Old description:
> At the moment the UTXO DB relies on a SQLite database, which means that the node can fail if there are disk error. That shouldn't happen, instead we should have this data in memory, with the SQLite being a backing store.

**Comment by Geod24** [comment]
This should also apply to the validator DB.

**Comment by Geod24** [comment]
Things to note:
- [updateUTXOCache](https://github.com/bpfkorea/agora/blob/d396373156c94621b3d41cbe124ce8bc2dfca873/source/agora/consensus/data/UTXOSet.d#L106) work on a `Transaction` basis;
- For consistency, we need the full `Block` to be applied to the state. So if we update `UTXOSet` atomically, it's a step up, but we also need to update `ValidatorSet` atomically (with itself and `UTXOSet`) for it to make sense.
- I think it's better to add the block to the chain first, then update state, than the other way around. But updating state shouldn't fail on adding block to the chain (adding block to the chain == store on disk).
- [There's some `assert(0)` to remove](https://github.com/bpfkorea/agora/blob/d396373156c94621b3d41cbe124ce8bc2dfca873/source/agora/consensus/data/UTXOSet.d#L161).

**Comment by AndrejMitrovic** [comment]
> My original thought was to simplify all of this and use memory, and just commit from time to time. @AndrejMitrovic pointed out that SQLite in fact has many advantages, which solve most of our problems. So the fault probably lies in our binding / usage.

Actually on second look some of these data types should really be replaced with in-memory + SQLite for persistence. For example, for the ValidatorSet we already have an upper bound limit of 1000 nodes. It makes sense to keep this small amount of data in memory, and then use SQLite for on-disk persistence.

**Comment by AndrejMitrovic** [comment]
> There are some blob being stored in the DB. I don't know if it's the most sensible choice. Should we take the storage overhead and store binary data as hex string ? For hash it would make sense.

Can you explain why you think it's not sensible?

**Comment by AndrejMitrovic** [comment]
> Can you explain why you think it's not sensible?

Sure. If we store it as hex then we can validate the data. If it's binary and it gets corrupted it's possible we won't know.

**Comment by Geod24** [comment]
Multiple reasons:
- The data exchanged at the network level might not be in the format we want to store it in. For example, in `ValidatorSet`, we store the Enrollment in binary, as well as the pre-image. But having them separated leads to awkward code, because the `random_seed` is essentially the first pre-image and should be treated as such. There is also no need to access the signature past its validation.
- Binary serialization means all-or-nothing: if we serialize an Enrollment and want just, say, the cycle length, we need to `SELECT` it, deserialize it, and return the value. If we use structured data in SQL, it's just a `SELECT`;
- It makes potential database-wide operations hard. This ties up to the previous point. You want to get all preimages ? Well you have to deserialize ALL enrollments.

**Comment by AndrejMitrovic** [comment]
Yeah I realized all of this while refactoring. Thanks for confirming.

**Comment by AndrejMitrovic** [comment]
> There is also no need to access the signature past its validation.

That is not true because we have a `getEnrollment()` API endpoint. However, it is possible to avoid storing both the `random_seed` and the current `preimage`. It's something I'm working on.

**Comment by Geod24** [comment]
It was also a blocker for my refactoring, however I question the utility of this endpoint.
Why would you have `getEnrollment` return already-enrolled validators ? From a consensus PoV, you either care about the block (which contains the Enrollment), or the Enrollments in the pool which you don't have. The ones already enrolled could be useful for a *client*, but is it useful for other consensus-following nodes ?

**Comment by AndrejMitrovic** [comment]
Pretty much the answer is no, we don't need it. The node should extract all enrollments from the block itself. I vote for removing it.

Edit: it looks like this was returning from the pool, not the validator set. https://github.com/bpfkorea/agora/pull/943

**Comment by Geod24** [comment]
So it unblocks us :)

**Comment by AndrejMitrovic** [comment]
Ah damn it looks like it got triggered by the `to help resolve #836` sentence. I'll reopen.

**Comment by bpalaggi** [comment]
Is this still in review or can we close it?

**Comment by AndrejMitrovic** [comment]
The last 3 items are resolved. The 1st item is blocked on upstream PRs (https://github.com/biozic/d2sqlite3/pulls).

**Comment by Geod24** [comment]
@AndrejMitrovic : Not blocked anymore right ?

**Comment by AndrejMitrovic** [comment]
As soon as you merge https://github.com/bpfkorea/d2sqlite3/pull/1 for me buddy.

**Comment by AndrejMitrovic** [comment]
Now that we have the errors properly set, we need to take a look at here: https://www.sqlite.org/rescode.html

And then examine all of our usage of sqlite and see which errors are recoverable, and which are not. We should inspect and fix usages of the `try { sqlite.query } catch (Exception) { return 0; }` pattern.

**Comment by Geod24** [comment]
> As soon as you merge bpfkorea/d2sqlite3#1 for me buddy.

You only had to ask. Another thing: We're seeing some of  this in the integration test logs:
```
node-4_1  | 2020-07-22T11:36:41.357733800Z 2020-07-22 11:36:41,79 Error [agora.common.TransactionPool] - SQLite error: (17) statement aborts at 15: [DELETE FROM enrollment_pool WHERE key = ?] database schema has changed
node-4_1  | 2020-07-22T11:36:41.357754600Z 2020-07-22 11:36:41,83 Error [agora.common.TransactionPool] - SQLite error: (17) statement aborts at 17: [SELECT EXISTS(SELECT 1 FROM validator_set WHERE key = ?)] database schema has changed
```

I *think* it's because we create tables piece-meal in the ctors and do requests before we're done creating them. Maybe fix that too ?

**Comment by AndrejMitrovic** [comment]
I really wonder how it's possible, since all the databases are created in the ctor before they are used..

**Comment by Geod24** [comment]
Maybe the wrapper eagerly prepare statements ? I think if we change `db_path` to be distinct we won't see it again, which would confirm it's the interaction between multiple classes (and why we don't see it in unittests because every `:memory:` instance is distinct).

**Comment by AndrejMitrovic** [comment]
Yeah I see the problem. I'm fixing it.

**Comment by Geod24** [comment]
> Yeah I see the problem. I'm fixing it.

Alex, I'll take "Favorite word combination in the English language" for 500$.

**Comment by Geod24** [comment]
This has been mostly addressed over the past few months, and we now have smaller dedicated issues for the bits remaining.
