### ISSUE TITLE
Preimage validation allows two preimages with the same values

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#844]
```D
unittest
{
    PreImageInfo info_1 = { enroll_key: hashFull(1), hash: hashFull(1) };
    PreImageInfo info_2 = { enroll_key: hashFull(1), hash: hashFull(1) };
    assert(!isValid(info_2, info_1, Enrollment.ValidatorCycle));
}
```

This test should pass. But the `!isValid` check fails.

Currently two preimages with the same distance and hash values are considered valid.

**Comment by Geod24** [comment]
Personally, I don't see it as outright wrong. It might be a bit misleading, and should have been documented, but it shouldn't lead to bugs unless the calling code doesn't handle equality well itself. In any case, I don't mind disallowing it, either.

**Comment by AndrejMitrovic** [comment]
I think it's just a matter of:

```diff
diff --git a/source/agora/consensus/validation/PreImage.d b/source/agora/consensus/validation/PreImage.d
index f347b18b..be96923d 100644
--- a/source/agora/consensus/validation/PreImage.d
+++ b/source/agora/consensus/validation/PreImage.d
@@ -52,7 +52,7 @@ public string isInvalidReason (const ref PreImageInfo new_image,
     if (new_image.enroll_key != prev_image.enroll_key)
         return "The pre-image's enrollment key differs from its descendant";

-    if (new_image.distance < prev_image.distance)
+    if (new_image.distance <= prev_image.distance)
         return "The height of new pre-image is smaller than that of previous one";

     if (new_image.distance > validator_cycle)
@@ -67,6 +67,13 @@ public string isInvalidReason (const ref PreImageInfo new_image,
     return null;
 }
```

Does the node check that it doesn't accept duplicate preimages?

**Comment by linked0** [comment]
I think there is no big problem with the `isValid` function on two pre-images with the same value. I say this because a pre-image should be the pre-image of a current image and there is no reason to use processing time to insert the same pre-image to the validator set.

**Comment by Geod24** [comment]
Closing as WONTFIX since it's not *technically* wrong.
