### ISSUE TITLE
Validator can get stuck trying to connect to expired / discontinued Validators (test-case)

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#854]
Consider this scenario:

- A Validator starts with an empty blockchain
- The actual latest block height in the network is 100_800
- The Validator uses its DNS seed to find the network
- The Validator will keep trying to discover the network until it finds the Validators with the public keys as set in the Enrollments in the Genesis block

In one scenario the Validators which enrolled in the Genesis block could be expired. Those Validators could even be permanently down. Therefore the Validator will never reach the end of the discovery phase and will become stuck.

What likely needs to be changed:
- The catch-up phase should be done alongside the network discovery phase.

This should be solved as part of https://github.com/bpfkorea/agora/issues/587

**Comment by AndrejMitrovic** [comment]
This was resolved, but it just needs a test-case. However it's blocked by #824.

Edit: It's unblocked now.

**Comment by AndrejMitrovic** [comment]
A test-case could be written as follows:
- Start with 4 validator nodes (set A) and 4 outsider validator nodes (set B). [Outsider nodes](https://github.com/bpfkorea/agora/blob/d73adeb283dd76e2d0e4fa650f95c439ea691896/source/agora/test/Base.d#L939)).
- Cycle set to 10
- At block height 9 enroll the 4 outsider nodes from set B. Do not re-enroll the old nodes in set A.
- Shut down set B.
- Delete blockchain data from set B. (You will have to check if data is deleted automatically or if you have to add code for this).
- Start set B.
- At this point the set B nodes will connect to set A nodes and begin retrieving blockchain data. 
- When they receive block height 10 they will see the enrollments and will try to connect to their quorum nodes.
- The test should wait until set B all have block height 10.
- After this the test should call `getNetworkInfo` on set B and verify the network state is `NetworkState.Complete`. It should also check the `addresses` in the `NodeInfo`, all of set B's addresses should be there.
- Then shut down set A.
- Try to generate a new block with only set B.

**Comment by linked0** [comment]
> A test-case could be written as follows:

Thanks a lot.

**Comment by Geod24** [comment]
@AndrejMitrovic : Am I correct in thinking this is fixed ?
