### ISSUE TITLE
Ensure that an already-enrolled Validator starts to validate immediately 

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#855]
As a validator, it is possible that I would boot up when already enrolled (e.g. if the node is a back-up node for another node).

We should have a test that:
- Starts a network with a few nodes;
- Has one node enrolled that is stopped *and wiped clean*;
- Wait at least 2 blocks;
- Restart the node, verify that it catches up, and starts to validate again;

**Comment by AndrejMitrovic** [comment]
> Wait at least 2 blocks;

If a Validator is offline while 2 blocks are externalized, doesn't that imply that the Validator will be slashed? Therefore this Validator shouldn't be able to validate again when it catches up.

**Comment by linked0** [comment]
> > Wait at least 2 blocks;
> 
> If a Validator is offline while 2 blocks are externalized, doesn't that imply that the Validator will be slashed? Therefore this Validator shouldn't be able to validate again when it catches up.

Right, I see what you mean. I'll modify the code of the PR #1110 accordingly.
