### ISSUE TITLE
Race condition in shutdown behavior causing infinite wait time

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#868]
This will likely need some support in LocalRest to get fixed.

I've found the root cause of the infinite wait time during some test runs of Agora. What happened was that there were runaway Node threads which were never shut down. But the work thread (the one running the unittest) **did** send the shutdown signal.

The race condition is as follows:

- Main thread spawns unittest worker threads (parallel() loop)
- A work thread spawns Node threads
- At the exit of the unittest, the work thread sends a shutdown signal to all the Node threads
- At the end of the `parallel` loop, `thread_joinAll()` is called

Here's the problem: the Work thread adds a `ShutdownCommand` instance to the shared message box, and notifies (via a Condition) the Node thread:

https://github.com/Geod24/localrest/blob/65cb7ed942dac913b9f4df5db0305c9d554a6f96/source/geod24/concurrency.d#L1052-L1053

The Node thread will attempt to read from the message box. **However**, because the shutdown call was asynchronous the `unittest` block might have already been exited and the Work thread might have already been killed. So the Node thread has nothing to read anymore.

Note that we do not use `spawnLinked` in LocalRest, so the Node thread never gets a notification that its parent thread was killed.

---

I can see a simple fix for this. We add a blocking parameter to `ctrl.shutdown`, and in that case we will expect to receive a message back when the Node thread exits the event loop here https://github.com/Geod24/localrest/blob/65cb7ed942dac913b9f4df5db0305c9d554a6f96/source/geod24/LocalRest.d#L497

**Comment by AndrejMitrovic** [comment]
Actually there would still be a race condition because the child thread would need to stay alive until the main thread receives the ping back. hmm...

**Comment by Geod24** [comment]
Can't we just join on all the threads that were spawned (not *all* the threads) in `network.shutdown` ?

**Comment by AndrejMitrovic** [comment]
That would work. But we need the thread handles which LocalRest does not expose I think..

**Comment by AndrejMitrovic** [comment]
I found the actual cause. I'll file a different issue.
