### ISSUE TITLE
Use the new TaskManager.setTimer() function

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#872]
These need to be replaced to use setTimer once TaskManager is fixed to use it.

https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/consensus/protocol/Nominator.d#L507-L509

https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/network/NetworkManager.d#L203-L210

https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/network/NetworkManager.d#L235-L246

_Originally posted by @AndrejMitrovic in https://github.com/bpfkorea/agora/pull/871#issuecomment-633762479_

**Comment by Geod24** [comment]
`setTimer` available as of #860

**Comment by TrustHenry** [comment]
https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/network/NetworkManager.d#L203-L210
https://github.com/bpfkorea/agora/blob/bebe6555052b830bff1040847edd035046d24cd4/source/agora/network/NetworkManager.d#L235-L246

Here's the question.
If it look at the existing code, wait after the function is done.
For the new function localrest, first wait and then call delegate.
Would it be okay to do the two things mentioned here after wait and call?

This creates a subtle time difference at the beginning.

**Comment by AndrejMitrovic** [comment]
Please be aware you're pointing to outdated commits.

Also yes, there's a difference. We probably don't want to delay every request. It would be nice to be able to do `start + wait` rather than just `wait + start`.

**Comment by TrustHenry** [comment]
The setTimer() also requires the stop function.

**Comment by TrustHenry** [comment]
Applied code line
2. https://github.com/bpfkorea/agora/blob/07dfc407a31828ee3d0596da29696235c5de5c81/source/agora/node/FullNode.d#L178
3.
https://github.com/bpfkorea/agora/blob/4c6b990955645003f6736d231fc781f366b7588b/source/agora/network/NetworkManager.d#L532
