### ISSUE TITLE
Remove `scope (failure) assert(0)` from Nominator.valueExternalized

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#888]
https://github.com/bpfkorea/agora/blob/35cd603ba7e4e0db798c4b61e31d5ef689041f87/source/agora/consensus/protocol/Nominator.d#L372

Since deserialization can fail, the method has legitimate reasons to error. And it's currently hiding the underlying error, see #886

**Comment by AndrejMitrovic** [comment]
https://github.com/bpfkorea/agora/issues/625
