### ISSUE TITLE
The enrollments of the genesis block must be sorted in ascending order.

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora#890]
https://github.com/bpfkorea/agora/blob/35cd603ba7e4e0db798c4b61e31d5ef689041f87/source/agora/test/Base.d#L1093

The alignment of the enrolls in makeGenesisBlock is descending.

- [x] The enrollments of the genesis block must be sorted in ascending order of the utxo_key.

Prerequisite to #747

**Comment by Geod24** [comment]
Can you expand on why it needs to be ascending and not descending ? I don't see why it matters as long as it's sorted.

**Comment by TrustHenry** [comment]
We want all validators to create a common rule of ConsensusData.
https://github.com/bpfkorea/agora/blob/35cd603ba7e4e0db798c4b61e31d5ef689041f87/source/agora/consensus/data/Block.d#L455-L457
Also, the rules of blocks made after a Genesis block are arranged in ascending order as shown above.

**Comment by Geod24** [comment]
Alright, so it wasn't consistent accross the code base. Great, thanks :)
