### ISSUE TITLE
Turn necessary consensus-critical constant into argument

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#894]
At the moment, we have issues with consensus constants being constant and accessed through the code source. E.g. we have the various genesis values, but also the cycle length.

The problem with such constants is that they might need to be modified to ensure things work correctly at a low cost. E.g. our cycles are 1008 blocks at the moment, which is expensive to generate in a test. Being able to reduce this to a few blocks would make things more scalable.

There's three approaches I can think of:
- Having them with `version` => This is what we're doing currently. It works well when one need not to change those values, or when there's a "common default". E.g. we have a common genesis block for all unittests. However it creates problems for integration testing as we need a special build.

- Having them global with selected with a runtime parameter. This is what we started to do with the genesis block, e.g. #712 , but it also creates some issues, e.g. #813. This issue recently showed again with `ValidatorCycle`.

- Having a global context that is passed around. This would be similar to the idea of "Consensus params" in the BTC implementation: https://github.com/bitcoin/bitcoin/blob/master/src/consensus/params.h but might lead to a lot of context being passed around if overused.

Note that BTC does have a mixture of both 2 and 3: https://github.com/bitcoin/bitcoin/blob/master/src/consensus/consensus.h

**Comment by linked0** [comment]
I think the best way to deal with this issue is to make a configuration for the constants like `ConsensusConfig`. How do you think of it?
If my idea is right, it's related to the issue #520, isn't it?

**Comment by AndrejMitrovic** [comment]
I'm not sure it's related to #520. #520 is unrelated to the protocol (you can change any settings and it would not break the protocol), whereas this issue #894 is about protocol changes.

**Comment by AndrejMitrovic** [comment]
Should the genesis block then also be part of the Consensus parameters?

**Comment by linked0** [comment]
> Should the genesis block then also be part of the Consensus parameters?

Sure, it is a good candidate for the class because it never changes on the network and it’s related to consensus. I can add the genesis block to the class after the related PR is merged and @Geod24  agrees to that.

**Comment by Geod24** [comment]
What is left to do ?
I can think of:
- Moving the Genesis block there: This can be a separate issue for the next sprint;
- Adapting the CLI to parse the argument: That's the only thing I can think of that is required to close this issue.
