### ISSUE TITLE
Integrate the ability to restart a node into TestAPIManager

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#906]
We want to be able to restart nodes to test things like catchup and correct validator behavior, e.g. #893 & #798 
Localrest has this ability since https://github.com/Geod24/localrest/pull/71
However, integrating it in Agora is more than just calling the function, as we need to properly shut down the node (passing it the same delegate as `TestAPIManager.shutdown`) and then restart it.

I have some code for this however it is not currently passing.

**Comment by AndrejMitrovic** [comment]
Probably the network manager still holds a reference to the RemoteAPI instance. I thought about this.. I think a way to fix this is to overwrite the registry in LocalRest with a custom instance of TestAPI which times out on all requests. Then the node will eventually ban this node.

**Comment by Geod24** [comment]
Discussed IRL: When trying to implement restarting, we realized that doing it outside of LocalRest would be a nightmare, because it would force all clients to change their `RemoteAPI` instance (including currently connected node). Hence why `restart` is in LocalRest instead of being `shutdown` + `start` on the client side, so the `RemoteAPI` instance needs not be replaced. The problem might crop back in if we ever want to replace a node, but I think a client side solution for this is better.

The reason I think it's failing is:
1) On the LocalRest side, requests are not cleaned up, the scheduler is just replaced;
2) On Agora side, there might be issues with restart which this uncovered;
