### ISSUE TITLE
Add Enrollments to the hardcoded genesis blocks

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#907]
Depends on #821

Our genesis blocks need to have Enrollments in themselves in order to be valid and usable.
Currently the lack of Enrollment means we have to come up with weird workaround for our tests.
Issues such as #822 ended up being slowed down by this.

**Comment by Geod24** [comment]
Not yet

**Comment by AndrejMitrovic** [comment]
Solved in https://github.com/bpfkorea/agora/pull/984

**Comment by AndrejMitrovic** [comment]
Not really solved.
