### ISSUE TITLE
Should we add the ability to enroll as soon as we freeze ?

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#935]
Question about this: Should we add the ability to enroll as soon as we freeze ?
Pro:
- Genesis does it;
- It allows to potentially solve the censorship issue if paired with a rule that more validators => Higher priority;
Cons:
- Attack vector ?

_Originally posted by @Geod24 in https://github.com/bpfkorea/agora/pull/845_

**Comment by TrustHenry** [comment]
If so, then it's the freeze Tx that the enrollment refers to at the same height of the block.

**Comment by linked0** [comment]
It might be good for the freezing functionality to have a flag to determine that it's for being a validator or not. If a node is intended to be a validator, enrolling as soon as freezing could be good. This is not the exact answer to your question but I'm favor of adding the functionality(enroll as soon as freeze). Anyway, let's think about the attack vector.

**Comment by Geod24** [comment]
Why would you freeze if you don't want to be a validator ?

**Comment by MichaelKim20** [comment]
That's a good idea.
I think we should consider not only the validators of block creation but also the function of Congress voting.

**Comment by linked0** [comment]
> Why would you freeze if you don't want to be a validator ?

I know we have only one use case for frozen UTXO. I just thought there might be use cases for which the UTXO could be frozen. Hmm, I didn't found out the actual cases yet.

**Comment by Geod24** [comment]
Fixed by #989
