### ISSUE TITLE
Refactoring UTXOSet to split this stuff into multiple modules

### ISSUE THREAD

**Issue by TrustHenry** [bosagora/agora#945]
The problem is caused by Genesis importing into validation.Block, which itself imports into UTXOSet which itself imports d2sqlite.

We can divide this into (UTXOSetValue, UTXOFinder) and (UTXOSet, UTXODB)

D2sqlite does not need to be imported depending on the purpose of use of UTXOSet.

**Comment by TrustHenry** [comment]
Prerequisite to #747

**Comment by AndrejMitrovic** [comment]
Resolved. Thanks.
