### ISSUE TITLE
receiveEnvelope() frequently times out

### ISSUE THREAD

**Issue by AndrejMitrovic** [bosagora/agora#970]
Running the `Simple` test with 26 nodes (current max due to the hardcoded keys) fails consistently.

With a bit of logging it seems maybe there is something wrong in how we do event handling.

For example:

```D
public void receiveEnvelope (scope ref const(SCPEnvelope) envelope) @trusted
{
    scope (exit)
        if (sw.peek.msecs > 500)
            printf(format("Timer %s finished at %s\n", counter, sw.peek().msecs).toStringz);

```

produces:

```
Timer 75 finished at 574
Timer 75 finished at 626
Timer 75 finished at 654
Timer 75 finished at 767
Timer 75 finished at 770
Timer 75 finished at 785
Timer 75 finished at 855
Timer 75 finished at 935
Timer 75 finished at 926
Timer 75 finished at 1011
Timer 75 finished at 933
Timer 75 finished at 1055
Timer 75 finished at 1100
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: moved to a bad state (ballot protocol)
```

-----

The bottom-line problem with this code is likely the use of `runTask` when gossiping SCP envelopes to all other nodes. We should try to use the `schedule` primitive instead.

**Comment by AndrejMitrovic** [comment]
So the failure goes completely away if we just disable the ballot protocol timer.

It makes me think there is something wrong with how that C++ delegate captures the shared pointer to the Slot (which stores the BallotProtocol).

**Comment by Geod24** [comment]
Sounds like this would be a pre-requisite for CoinNet, correct ?

**Comment by AndrejMitrovic** [comment]
Folding into #2021
