### ISSUE TITLE
Propagate newly received transactions via ConsensusData to the TransactionPool

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#993]
Currently, when we receive transactions via `ConsensusData` we do not store the transaction in the pool.
It would be wise to do so, and could also allow us to find out some issues (e.g. if we're stuck trying to nominate conflicting values).

Definition of done:
- [ ] When a node with an empty pool receive `ConsensusData` that contains transactions it is not aware of, it stores it in its `TransactionPool`, even if it does not reach consensus;
- [ ] A node does not store transactions which are conflicting;
- [ ] If a transaction conflicts, or was newly added, it is reported in the log (as debug);

**Comment by Geod24** [comment]
Actually this might get obsoleted by #407 , but that is a much larger issue.
Another problem we have is that there is currently little benefit in propagating Transactions beside avoiding this bug, as we will propagate them again here anyway.

**Comment by AndrejMitrovic** [comment]
Ah but I think we should actually move away from storing transactions and enrollments in the ConsensusData. I think it would be better to vote on hashes instead. I think this is how Stellar does it, but for simplicity we went with nominating actual transactions.

**Comment by frextang** [comment]
this  is correct according to scp sepc about nomanite protocol

**Comment by Geod24** [comment]
I agree with @AndrejMitrovic too. But then, it's just another issue: We don't query missing transactions AFAIK. Also, we discussed the possibility of using a predictable algorithm to reduce network load.
